### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by kissmyaxe1234** [THEREALWWEFAN231/Inertia#1004]
**Minecraft Version(s)** 1.16.4

**What is the suggestion** Admin Hack

**Why would this feature be useful** It would be great for hacking?

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by AutistEren** [comment]
1) it's not possible
2) inertia is not a hacked client
3) learn how to use checkboxes

**Comment by kissmyaxe1234** [comment]
shit you

**Comment by constantinDev** [comment]
1. what
2. i dont think you know how that works
3. do you think we can just pull op out of our asses?

**Comment by kissmyaxe1234** [comment]
yeeet

**Comment by THEREALWWEFAN231** [comment]
> 3. do you think we can just pull op out of our asses?
No he expects you to pull it out of your "axe".

Suggestion is unclear. And you expect us to figure out a way to do this. Which is near impossible? I don't even know what the suggestion is 🤷 maybe force op, I don't know, either way not possible.

**Comment by constantinDev** [comment]
I think he wants force op, yes.

**Comment by feliscatusmeows** [comment]
Just trick the admin into installing your backdoored plugin.
