### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gabrielmoreno11fg** [THEREALWWEFAN231/Inertia#1007]
**3.1.3** 
**1.16.4** 
**Windows 10 1809** 
**Fabric, Sodium, Fabric API, Logical zoom** 

**Trying to use baritone wont work, it won't move** 

**Crash-report (None)**

**Final checklist:**

- [x] I know how to properly use check boxes 
- [X] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [X] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by GaiaB0t** [comment]
known issue, baritone does not work with sodium

**Comment by Paralusion** [comment]
baritone issue
