### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by UNordicc** [THEREALWWEFAN231/Inertia#1009]
**Inertia Utility Mod version: 3.1.3** 
**Minecraft version: 1.16.4** 
**Operating system: Windows 10 Home** 
**Optifine/Other mods: Only Inertia** 

**What's the issue: Can't use esc on my Inertia Client, I deleted options.txt to fix it and nothing** 

**Crash report: None**

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by constantinDev** [comment]
So you cant press esc / it doesnt do anything? In what menu are you trying to press esc in?

**Comment by UNordicc** [comment]
It started working rn, but I tried fix it like 2 hours and even launching other client or apps but didn't fixing. Thanks for fast response for my problem. I fix my problem.
