### ISSUE TITLE
Increase Step Limit

### ISSUE THREAD

**Issue by simulatorwinner** [THEREALWWEFAN231/Inertia#1012]
All or 1.12.2-latest

The Step hack only works for 2 blocks, Its limit should be increased to 10 or above as all the clients have atleast 10 limit for step hack

It's use full cause it'll be much elaborate and helpful

**Final checklist:**

- [ ] Increase step hack limit

**Comment by AutistEren** [comment]
use the .value command

**Comment by simulatorwinner** [comment]
ohhhh, but they should totally add a scroll bar for it in click GUI

**Comment by simulatorwinner** [comment]
Uhhh, how does the .value syntax work, for step ?
I did '.value step 0.1 3' it didn't work

**Comment by AutistEren** [comment]
.value step delay 0.1 height 3 
I don't know if its called "height" I can't get on to check rn.

**Comment by simulatorwinner** [comment]
.value step delay 0.1 height 3
doesn't work

**Comment by AutistEren** [comment]
just delete height and see what comes there.

**Comment by simulatorwinner** [comment]
turns out if u do 
.value step delay (it will ask true or false here) nothing over here

**Comment by AutistEren** [comment]
.value step delay true 0.1

**Comment by simulatorwinner** [comment]
.value step delay true 0.1
Couldn't recog/find that setting

**Comment by snoopchallenge** [comment]
press tab on a newer version and you will be able to figure it out

**Comment by simulatorwinner** [comment]
Im on latest...

**Comment by constantinDev** [comment]
`.value step (tab here)`

**Comment by simulatorwinner** [comment]
Pretty sure inertia doesn't have feature to set step limit

**Comment by AutistEren** [comment]
there is but i cant get on and test, tab always works

**Comment by Godeps2891** [comment]
![image](https://user-images.githubusercontent.com/54289108/104095609-140f8480-5298-11eb-92dc-702db7cc8c1d.png)
there's only delay

**Comment by simulatorwinner** [comment]
yea

**Comment by Paralusion** [comment]
duplicate #745
