### ISSUE TITLE
Packet fly Kills you (Bug)

### ISSUE THREAD

**Issue by simulatorwinner** [THEREALWWEFAN231/Inertia#1013]
Inertia Utility Mod version: Only tried on 3.1.3
Minecraft version: idk, but it's definitely in 1.16.4 
Operating system: Windows
Optifine/Other mods: With sodium

What's the issue: Packet Fly hack kills you in single player instead of flying using packets, it even does the hurt cam in creative!

No Crashes

**Final checklist:**

- [ ] Packet Fly Fixed.

**Comment by AutistEren** [comment]
packet fly doesnt work on singleplayer

**Comment by simulatorwinner** [comment]
Ohh

**Comment by snoopchallenge** [comment]
Should still work in singleplayer?

**Comment by simulatorwinner** [comment]
idk

**Comment by simulatorwinner** [comment]
I'm not a Java Dev

**Comment by Paralusion** [comment]
packet fly is not meant for singleplayer
