### ISSUE TITLE
AntiAfk Hack

### ISSUE THREAD

**Issue by simulatorwinner** [THEREALWWEFAN231/Inertia#1018]
All

Because it's very usefull and used extensivly
The AntiAfk Setting should be very customizable, like hit blocks, move, spin, etc

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by AutistEren** [comment]
for spin there is derp in 3.2 😉

**Comment by simulatorwinner** [comment]
Yea, but derp is soo derpy that staff cwill know within sec's that the person is on hacked client

**Comment by AutistEren** [comment]
you could set it to like 0.01 speed but yea we need anti afk

**Comment by snoopchallenge** [comment]
simulator this client is made for anarchy servers but moving would be good

**Comment by Paralusion** [comment]
duplicate #11
