### ISSUE TITLE
Highlight Incompatible Modules

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#1019]
**What is the suggestion**
Highlight no fall & anti hunger if elytra+ is on.

**Why would this feature be useful**
People using the client for the first time are usually confused why their elytra+ isn't working.

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by snoopchallenge** [comment]
it displays in chat?

**Comment by Paralusion** [comment]
duplicate #213
