### ISSUE TITLE
Better Horse Jesus

### ISSUE THREAD

**Issue by BleachDrinker420** [THEREALWWEFAN231/Inertia#102]
**Minecraft Version**
All
**What is the suggestion**
Improve Jesus when riding entities, it glitches you when going from water to land and it doesn't float you up to the top if you mount a entity in water.
**Why it will be useful**
It will be much more useful when traveling over rivers/oceans.

**Comment by THEREALWWEFAN231** [comment]
it should be working fine, what server are you talking about in general

**Comment by BleachDrinker420** [comment]
i'm talking about THE OLDEST ANARCY SERVER IN MINECRAFT

**Comment by Paralusion** [comment]
tested it, works fine for me

**Comment by Paralusion** [comment]
tried: still working fine for me
