### ISSUE TITLE
Book Too Large! bypass

### ISSUE THREAD

**Issue by enderson0** [THEREALWWEFAN231/Inertia#1020]
**Minecraft Version(s)**
Newest paper builds
**What is the suggestion**
A .randombook that bypasses "Book too big!"
**Why would this feature be useful**
For bookbanning on just about every server under the sun, even on latest paper patch
**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
then do .randombook random 50

**Comment by feliscatusmeows** [comment]
or even lower
or you can use .randombook ascii

**Comment by Paralusion** [comment]
@feliscatusmeows has a decent method for this
