### ISSUE TITLE
Split .dupe into .drop and ,quit

### ISSUE THREAD

**Issue by enderson0** [THEREALWWEFAN231/Inertia#1024]
**Minecraft Version(s)**
All
**What is the suggestion**
Split .dupe into .drop and .quit and remove .dupe.
Everyone in the discord keeps yelling about how
'.dupe doesnt work' and Godeps needs a vacation from muting everyone for not reading #rules
**Why would this feature be useful**
.drop all / hand / hotbar are just .dupe without quitting, useful in PVP or keybinds 
.quit will be useful for combat log scripts
**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by Godeps2891** [comment]
stupid suggestion

**Comment by enderson0** [comment]
no

**Comment by THEREALWWEFAN231** [comment]
No.
