### ISSUE TITLE
Theia Results

### ISSUE THREAD

**Issue by RocketNinja15** [THEREALWWEFAN231/Inertia#1027]
I ran Theia on the installer

WebConnectionCheck: CLEAR
URLCheck: {
	WARN: Found URL [null : < : ,  : > : year : month : dayOfMonth : hourOfDay : minute : second : ye] in com/google/gson/internal/bind/TypeAdapters$21
	WARN: Found URL [null : < : ,  : > : year : month : dayOfMonth : hourOfDay : minute : second : ye] in com/google/gson/internal/bind/TypeAdapters$21
	WARN: Found URL [ᔨᔪᔡᕥᔩᔪᔤᔡᔠᔷᕥᔩᔬᔫᔮ : 683349317 : ≠≭≤≱ : -17096172 : 肠肩肴股肣 : 1517191366 : ����������] in inertia/pwSJ
	WARN: Found URL [绵绹绱绶纸综绷绯绶维绷绹综纸维绱绶绳 : 1848016536 : 립맋맱맋맬맱맶맣맮맮맧맰릿맶맰맷맧릤맏맫맬맧맡맰맣매맶맔맧맰맱맫맭맬릿 : -1363363] in inertia/pwSJ
	WARN: Found URL [������������������ : 589815297 : -226234308 : -882662049 : -226234168 : -1034895] in inertia/uWBc
	WARN: Found URL [튞특튲튥튣튾튶틷튔튻튾튲특튣 : 124768983 : 森梪梳梯梮 : 1734240448 :  : 1560276457 : -516477219 : ] in inertia/LZfn
	WARN: Found URL [噱噒噞噜噉噔噒噓 : 22697533 : Ljava/lang/Object; : hh:mm:ss a : 奪奨奣奨奿奬她奨夭奣奨奺夭奦奨奴夭奡奤奣奦 : ] in inertia/LZfn
	WARN: Found URL [奪奨奣奨奿奬她奨夭奣奨奺夭奦奨奴夭奡奤奣奦 : -1220126451 : 菲菅菅菘菅莗菐菒菃菃菞菙菐莗菔菛菞菇菕菘菖菅菓莗菃菒菏菃 : -1799912521] in inertia/huzM
}
CommandCheck: CLEAR
FileDeletionCheck: CLEAR
CoordCheck: CLEAR

Overview:
	com/google/gson/internal/bind/TypeAdapters$21: URLCheck 
	inertia/LZfn: URLCheck 
	inertia/uWBc: URLCheck 
	inertia/huzM: URLCheck 
	inertia/pwSJ: URLCheck 

Theia completed in 600 milliseconds

**Comment by THEREALWWEFAN231** [comment]
Yes? And? I don't get the point of this post, It makes several requests to inertiaclient.com, and some to http://files.minecraftforge.net/ & https://fabricmc.net/.

**Comment by feliscatusmeows** [comment]
Issue is that random characters is much more scary than files.minecraftforge.com fabricmc.net and inertiaclient.com

**Comment by constantinDev** [comment]
> Issue is that random characters is much more scary than files.minecraftforge.com fabricmc.net and inertiaclient.com

Why, Yes, the entire client series is obfuscated to prevent skidding. What is your point?

**Comment by feliscatusmeows** [comment]
Mabye don't obfuscate the string? I mean it's not like anyone will skid an installer nor will it leak anything, assuming all it does is install forge and download inertia to .minecraft/mods

**Comment by constantinDev** [comment]
> Mabye don't obfuscate the string? I mean it's not like anyone will skid an installer nor will it leak anything, assuming all it does is install forge and download inertia to .minecraft/mods

By the looks of it, the installer also contains a compressed version of the client itself, as the inertia package and some of the apis are present. I'm not sure tho

**Comment by feliscatusmeows** [comment]
Either way, wwefan probably shouldn't obfuscate the urls, it's scary.

**Comment by constantinDev** [comment]
> Either way, wwefan probably shouldn't obfuscate the urls, it's scary. 

ooooOoOoO am scared of chinese characters 😦😦😦😳

**Comment by feliscatusmeows** [comment]
For all you know that url could point to Russian hackers, things like inertiaclient.com/InstallerDownload1.16.4jar.php is less scary to somebody who were to do a theia scan than some unicode garbage data.

**Comment by constantinDev** [comment]
> For all you know that url could point to Russian hackers, things like inertiaclient.com/InstallerDownload1.16.4jar.php is less scary to somebody who were to do a theia scan than some unicode garbage data. 

all jokes aside what the fuck is your point? If the jar needs to make a request to the outside world, so be it. After all you can still decompile or wireshark the program if you are that concerned

**Comment by feliscatusmeows** [comment]
Somebody could run theia, see the results and then tell everyone that inertia is a rat.
