### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#1029]
**What is the suggestion**
Zoom, changes your FOV

Settings
Modes: hold/toggle
FOV: changes how much will it zoom in
Allow Scrolling: uses mouse scroll wheel to zoom in and out
Cinematic Mode: uses minecraft's cinematic mode to smooth the mouse movement

**Why would this feature be useful**
Cool utility

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

Edit: i realized this was #584 :(

**Comment by Paralusion** [comment]
duplicate #584
