### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ShadowNinjaXD** [THEREALWWEFAN231/Inertia#1034]
**all**

*Xray bypass, this would break blocks in a pattern revealing the real blocks*

**bypasses xray i mean, bro thats good :Dl**

**Final checklist:**

- [X] I know how to properly use check boxes 
- [X] This is not a suggestion for baritone or other mod

**Comment by ShadowNinjaXD** [comment]
on a side note, i reallly dont know how to do this pls dont judge

**Comment by ShadowNinjaXD** [comment]
i rarely use github

**Comment by constantinDev** [comment]
Already made here: https://github.com/AriliusClient/AntiAntiXray

supports inertia and fabric, so you can just add it to your mods folder. `:aax help` to view help, `G` on your keyboard to scan blocks.

**Comment by constantinDev** [comment]
Side note: `:aax scanall` if the server hides ores and doesnt obfuscate them. Takes longer tho

**Comment by Paralusion** [comment]
duplicate of #42
