### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HalseyWasTaken** [THEREALWWEFAN231/Inertia#1036]
**Minecraft Version(s)**
1.8.9
**What is the suggestion**
Make inertia client for 1.8.9?
**Why would this feature be useful**
Players would be able to play on 1.8.9 with the epic combat too.
**Final checklist:**

- [ ] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
no just use viaversion

**Comment by HalseyWasTaken** [comment]
O ok

**Comment by Paralusion** [comment]
use ViaVersion
