### ISSUE TITLE
Black screen only in inertia (1.12.2) 

### ISSUE THREAD

**Issue by Houzik** [THEREALWWEFAN231/Inertia#1037]
**Inertia Utility Mod version:** 
**Minecraft version: 1.12.2 
**Operating system: windows 7
**Optifine/Other mods: optifine 

**What's the issue: When I join it keeps black screen only in inertia 1.12.2 

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [x] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [ ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Paddyk45** [comment]
I think because you are using windows 7, or male a driver update
