### ISSUE TITLE
.plugins command suggestion

### ISSUE THREAD

**Issue by Cypphi** [THEREALWWEFAN231/Inertia#1038]
**Minecraft Version(s)** all

**What is the suggestion** .plugins (like in LiquidBounce)

**Why would this feature be useful** See the plugins the server uses, useful when trying to dupe on a server and need to know if they have any type of anti duping system. Could also be useful when trying to find out what anticheat they use or whatever

**Comment by Paralusion** [comment]
duplicate of  #264
