### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by azari3333** [THEREALWWEFAN231/Inertia#1042]
**Minecraft Version(s)**
Probably all
**What is the suggestion**
Self destruct module
**Why would this feature be useful**
When someone want to screenshare you, you can simply enable self destruct and nothing of the client will be found also you should add button for it to gui's too because freeze festure of some servers open gui and you cant enable the module
**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by AutistEren** [comment]
this wont be added because you are not supposed to use inertia on servers you are not allowed to, best you can do is type .t ALLOFF

**Comment by feliscatusmeows** [comment]
bruh don't use inertia as ghost client, best u can do is a macro that removes all binds and does .t all_off

**Comment by Paralusion** [comment]
duplicate #270
