### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by azari3333** [THEREALWWEFAN231/Inertia#1043]
**Minecraft Version(s)**
All
**What is the suggestion**
Phase
**Why would this feature be useful**
You can phase trough walls and ceilings
idk if its possible in newer versions but for example skid client has it
**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by Paralusion** [comment]
duplicate of #15
