### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by heywat** [THEREALWWEFAN231/Inertia#1044]
**Inertia Utility Mod version:**
latest 
**Minecraft version:**
1.8.9/1.12 
**Operating system:** 
windows
**Optifine/Other mods:** 
i tried to use optifine but didnt work no other mods

**What's the issue:** 
it crashes EVERY time i play multiplayer (mineplex)   

**Crash-report(if applicable)(Would be very useful also please format):**
it is a crash report

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [x] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [ ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by THEREALWWEFAN231** [comment]
You have to send the crash report so we can figure out what it is.

**Comment by THEREALWWEFAN231** [comment]
Also don't play on mineplex 😔 This isn't a minigame client.

**Comment by heywat** [comment]
> You have to send the crash report so we can figure out what it is.

do u mean after the crash in the launcher ? thats it 

The game crashed whilst ticking entity
Error: java.util.ConcurrentModificationException
Exit Code: -1

**Comment by heywat** [comment]
> Also don't play on mineplex 😔 This isn't a minigame client.

ik bro im not using for mini games tho, and the only reason im playing it is that im banned in hypixel i bought hypixel alts from the altering tho but every time i generate an alt it banes me and give me this (Your account has a security alert, please secure it and contact appeals.) ik it off topic but if you know whats the problem ill be thankfull

**Comment by heywat** [comment]
> You have to send the crash report so we can figure out what it is.

im sorry but its getting really annoying right know it might be the esp ill disable but please fix this as soon as you can.

**Comment by feliscatusmeows** [comment]
he needs the crash report located in .minecraft/logs/latest.log to fix this

**Comment by heywat** [comment]
> he needs the crash report located in .minecraft/logs/latest.log to fix this

i actually just got a new one and it says to report it here but its too long should i send a screen shot and how ?

**Comment by heywat** [comment]
> he needs the crash report located in .minecraft/logs/latest.log to fix this

here it is 
![image](https://user-images.githubusercontent.com/74481108/105570410-4de19000-5d5a-11eb-834e-92e2e40e288d.png)

**Comment by Paralusion** [comment]
viaversion issue
