### ISSUE TITLE
error by client 

### ISSUE THREAD

**Issue by heywat** [THEREALWWEFAN231/Inertia#1046]
**Inertia Utility Mod version:** 
latest
**Minecraft version:** 
1.8.9/1.12.2
**Operating system:** 
windows
**Optifine/Other mods:** 
no

**What's the issue:** 
idk but it kicked me out of the server and (the client) Sayed to post the problem here 

**Crash-report(if applicable)(Would be very useful also please format):**
its too long and i cant copy it so i posted a screen shot instead 
![image](https://user-images.githubusercontent.com/74481108/105570512-e8da6a00-5d5a-11eb-996b-d70e9f23054a.png)

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [ ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by jqww** [comment]
Bro, you didn't even do the checkboxes... also that is a different github dude, please read where you are posting lul.

**Comment by heywat** [comment]
> Bro, you didn't even do the checkboxes... also that is a different github dude, please read where you are posting lul.

ik it was an accident i posted it there too tho, ill just delete this one
