### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by poopkekelord** [THEREALWWEFAN231/Inertia#1048]
**Minecraft Version(s)**
1.16.4

**What is the suggestion**
Add more options for autofarm I want to be able to break crops with a hoe but it doesn't let me and I want the option to turn on and off replacing seeds also I would like to turn on / off auto hoeing land. Also make it like nuker so you can do .autofarm add then a certain crop so it doesn't try to work on all crops

**Why would this feature be useful**
It would be useful to have more options in the autofarm.

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by THEREALWWEFAN231** [comment]
Auto Farm is already improved in 3.2(when ever it releases). Which is basically fully automatic. I'm pretty sure it does what you want.
