### ISSUE TITLE
Suggestion - Disable mod button

### ISSUE THREAD

**Issue by RandomAccountt** [THEREALWWEFAN231/Inertia#1057]
**Minecraft Version(s)**
1.16.5
**What is the suggestion**
Add a button which can disable the mod entirely and remove it from GUIs.
**Why would this feature be useful**
After playing some anarchy, sometimes I like to go on a factions server. Occasionally mods do spot checks where they ask for screenshots of my menus, they see inertia and I get banned. Wurst client has a button hidden in the statistics menu, which when pressed would disable the entire mod. I would like to see something similar in inertia.
**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
Don't use inertia on servers where it isn't allowed, is it that hard to relaunch the game?

**Comment by RandomAccountt** [comment]
This is more of a convenience/QOL sort of thing. I'm fine with restarting my game, but I think this would be a nice touch 👍

**Comment by feliscatusmeows** [comment]
You should not be using this on servers that don't allow it anyways, We do not want to enable the use of this on servers where it is not allowed and this seems like how it would happen.

**Comment by Paralusion** [comment]
duplicate #270
