### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 0Michi** [THEREALWWEFAN231/Inertia#1060]
**Minecraft Version(s)**
1.12.2
**What is the suggestion**
add targetHUD
**Why would this feature be useful**
I use xulu targetHud and its ugly
 **Final checklist:**
- [ x ] I know how to properly use check boxes 
- [ x ] This is not a suggestion for baritone or other mod

**Comment by THEREALWWEFAN231** [comment]
I don't know what target hud is, I assume I do, but I don't know your definition, I have a plan to revamp Combat Info, and I think it's going to be what you want, will it look nice though, I don't know, that is opinion based and we shall find out.
