### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Bluelightningbro** [THEREALWWEFAN231/Inertia#1064]
**Inertia Utility Mod version:** 
**Minecraft version:** 1.16.5
**Operating system:** java
**Optifine/Other mods:** 

**What's the issue:** I cant find baritone 

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [ yes] I know how to properly use check boxes 
- [yes ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [yes ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by TheRedHippo** [comment]
ask in the discord before posting on the github. the prefix for baritone is # or .b
for example, .b goto 1000 1000

**Comment by feliscatusmeows** [comment]
:pain: also there is no inertia 1.16.5

**Comment by Bluelightningbro** [comment]
I was using it on 1.16.5 but downloaded at 1.16.4
