### ISSUE TITLE
Suggestion Better Freecam

### ISSUE THREAD

**Issue by GalaxyLinus** [THEREALWWEFAN231/Inertia#1066]
**Minecraft Version(s)**
all
**What is the suggestion**
Freecam should be working like in Tweakeroo (Actually Show the player with actions etc.)

Video explains it better:
[https://youtu.be/vMsfTeCY4WY](https://youtu.be/vMsfTeCY4WY) 

**Why would this feature be useful**
When you build a afk farm and want to see it from the outside and just visually better

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by AutistEren** [comment]
camera mode for freecam is added in next update

**Comment by THEREALWWEFAN231** [comment]
This is already added in/for 3.2, although you can't see the player unless you are in third person, Idk if I'll change that 🤷

**Comment by feliscatusmeows** [comment]
You should force the player to render, not being able to see where you are would be really bad in many situations.
