### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jumbledsiren** [THEREALWWEFAN231/Inertia#1067]
**Inertia Utility Mod version: 3.1.3** 
**Minecraft version: 1.16.5** 
**Operating system: Windows** 
**Optifine/Other mods: Just Fabric** 

**What's the issue: I tried changing the "Scrolling:" in the Click GUI from "Normal" to "All" and then I scrolled the Render section of the click GUI outside my screen, I can't get it back, the Render section is now outside my screen and I don't have any way to access it back, how do I solve this?** 

**Final checklist:**

- [Yes.] I know how to properly use checkboxes 
- [No, That would've not helped me with my problem.] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [?] I have attempted to reproduce this bug using the latest available release of Inertia.

**Comment by THEREALWWEFAN231** [comment]
.guireset name
.guireset Render
.guireset all
