### ISSUE TITLE
If its possible a .seed function would be nice

### ISSUE THREAD

**Issue by Ttbtwkys** [THEREALWWEFAN231/Inertia#1068]
**Minecraft Version(s)**

**What is the suggestion**

**Why would this feature be useful**

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] This is not a suggestion for baritone or other mod

**Comment by constantinDev** [comment]
and what should that function do exactly?

**Comment by THEREALWWEFAN231** [comment]
Not possible.
