### ISSUE TITLE
Book Ban (Creative)

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#107]
**Quick Description**
Allow users to create book bans if they have access to creative, where it would (preferably) instantly drop

**My Suggestion for Developers**
Would be cool if this was added a a command. Just type the command, and it spews out the book ban infront of you for anyone with horrible karma to pick up.

**Additional Context**
Users may be banned for running this command, since they have to create the ban book first? How are ban books made, if the creator is instantly book banned..?

**Comment by Paralusion** [comment]
book ban is patched

**Comment by SylveonBottle** [comment]
Considering the WWE is for 1.12-1.14, is it patched for all versions?

**Comment by Paralusion** [comment]
All Paper/Spigot server, so any big server yes

**Comment by Paralusion** [comment]
.randombook has been added
