### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AstroFazeGaming** [THEREALWWEFAN231/Inertia#1071]
**Minecraft Version(s)**
1.16.5
**What is the suggestion**
Suggestion: Let you use kill aura while holding the shield or eating, so you don't have to switch between the weapon and the item on your offhand.
**Why would this feature be useful**
You could not take any damage while using kill aura so it would benefit the players a lot if they are being attacked by a player with a sword.
**Final checklist:**

- [x ] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by THEREALWWEFAN231** [comment]
Turn "Eatting"(I know it's spelt wrong) mode to Ignore and it will do what you want.

**Comment by AstroFazeGaming** [comment]
> Turn "Eatting"(I know it's spelt wrong) mode to Ignore and it will do what you want.

Thanks! I didn't notice it before.
