### ISSUE TITLE
Bug Inertia doesn't work with Tweakeroo

### ISSUE THREAD

**Issue by GalaxyLinus** [THEREALWWEFAN231/Inertia#1072]
**Inertia Utility Mod version:** 
Newest
**Minecraft version:** 
1.16.4
**Operating system:** 
Win10 Home / MultiMC
**Optifine/Other mods:** 
Tweakeroo
Baritone is removed

**What's the issue:** 
It crashes on start, the owner of Tweakeroo explained it [github.com/maruohon/tweakeroo/issues/164#issuecomment-7...](https://github.com/maruohon/tweakeroo/issues/164#issuecomment-774019431)
**Crash-report(if applicable)(Would be very useful also please format):**

[https://paste.ee/p/2Bfgp](https://paste.ee/p/2Bfgp)

[(if pasteee expires click here for a copied and pasted version)](https://pastebin.com/NPgB0crc)

**Final checklist:**

- [x ] I know how to properly use check boxes 
- [x ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by THEREALWWEFAN231** [comment]
Tweakeroo doesn't like it when an injection fails, open the tweakeroo jar file(with like winwar or something) edit the mixins.tweakeroo.json file and remove this exactly

`
,
    "injectors": {
        "defaultRequire": 1
    }
`
