### ISSUE TITLE
Manual mode for Note Bot

### ISSUE THREAD

**Issue by MaxAdventures** [THEREALWWEFAN231/Inertia#1073]
**all**

**Note Bot manual mode with just esp and the bot does nothing**

**Why would this feature be useful**
so you can't be detected by the anti cheat it would save so much time 
**Final checklist:**

- 

- [ nope ] I know how to properly use check boxes 

- [ nope ] This is not a suggestion for baritone or other mod

**Comment by THEREALWWEFAN231** [comment]
bruh

**Comment by Paralusion** [comment]
" it would save so much time"
no.
