### ISSUE TITLE
FPS Boost

### ISSUE THREAD

**Issue by Ral721chanel** [THEREALWWEFAN231/Inertia#1074]
Optimize the client for higher fps, I just changed the client and put it back, but when I start it again it goes to 7-10 fps. Before I would go at 30-45 fps as very low at 20 fps. Try to optimize the client so that it has more fps. It's unplayable for me

**Comment by Paralusion** [comment]
either don't use resource intensive modules, or upgrade your PC.. Inertia is already optimized and it is logical that features will have a impact on your frames.

**Comment by feliscatusmeows** [comment]
Solution: install sodium, lithium, phospor

**Comment by Paralusion** [comment]
@feliscatusmeows had a decent solution for this
