### ISSUE TITLE
[Suggestion]Xray with optifine for 1.16.4

### ISSUE THREAD

**Issue by WahidIslamLinad** [THEREALWWEFAN231/Inertia#1078]
**Minecraft Version(s)**
Fabric !.16.4

**What is the suggestion**
Making xray like block esp like forge xray mod.

**Why would this feature be useful**
We cant use optifine with xray on 1.16.4..even i got muted on discord for only asking this question..so i think if xray like block esp is added we can bypass the optifine issue..(inspired from forge Advaced xray mod) 

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
Just use blockesp/use sodium, lithium, and phospor mods instead of optifine. Optifine keeps changing behavior and makes making a xray painful because of how often it changes.

**Comment by THEREALWWEFAN231** [comment]
There are ways to get around the optifine issue, we've done it twice and optifine just keeps changing there code for god knows what reason which breaks our fixes.

**Comment by bosssssssssssssssssssssss** [comment]
> Just use blockesp/use sodium, lithium, and phospor mods instead of optifine. Optifine keeps changing behavior and makes making a xray painful because of how often it changes.
Sodium uses FabricApi and inertia needs chunk reload to activate xray which is a pain so suggest another fps mod please

**Comment by feliscatusmeows** [comment]
no sodium does not require fabric api. It even overrides the fabric api render and allows you to xray with the fabric api.

**Comment by WahidIslamLinad** [comment]
> > Just use blockesp/use sodium, lithium, and phospor mods instead of optifine. Optifine keeps changing behavior and makes making a xray painful because of how often it changes.
> Sodium uses FabricApi and inertia needs chunk reload to activate xray which is a pain so suggest another fps mod please
> 

sodium is a good mod..even better thn optifine on performance..but as a texture pack creator i often have to use optifine..thats why i was telling this

**Comment by feliscatusmeows** [comment]
I don't think anyone wants to spend more time finding out why their mod doesn't with with a proprietary closed-source mod that isn't even made for the same modding platform. Unfortunately you will have to choose between usability or prettyness here.

**Comment by Paralusion** [comment]
known issue: will probably be fixed next update
