### ISSUE TITLE
Antispam

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#108]
**Quick Description**
Remove duplicate messages in the chat to help mitigate flood and advertisements

**The Issue**
Some servers that you join will have adverts that are announced occasionally, and sometimes you'll just find the occasional player who's doing nothing but spamming. AntiSpam could mitigate these advertisements by blocking duplicate messages, and completely hide player spam.

**My Suggestion for Developers**
Check for similar messages in the chat from the same users (user anti-spam), or if they're not detected to be from a user (server advertisements). Have an option to disable/enable either of these options. If detected, just replace the previous message with a [x2], [x3], etc.

**Comment by Paralusion** [comment]
yes, that's handy, if you mean it like this;

before:
Player> some message
Player> some message
Player> some message

After:
Player> some message (x3) (the x3 in gray)
