### ISSUE TITLE
Infinite Aura/Kill Aura TP Mode

### ISSUE THREAD

**Issue by MichalikX** [THEREALWWEFAN231/Inertia#1080]
**Minecraft Version(s)** all

**What is the suggestion** Infinite Aura/ TP Mode For Kill Aura

**Why would this feature be useful** For minigames and servers without anticheat / other
It would work little bit same like Reach TP Mode, but with kill aura.
**Final checklist:**

- [x] I know how to properly use check boxes 

- [x] This is not a suggestion for baritone or other mod

**Comment by Paralusion** [comment]
duplicate of #637
