### ISSUE TITLE
Suggestion: Chat suffix

### ISSUE THREAD

**Issue by Z3R0-cmd** [THEREALWWEFAN231/Inertia#1088]
**Minecraft Version(s)**
all of them
**What is the suggestion**
Add the module "Chat suffix"
**Why would this feature be useful**
bc it is epic and needed in every good client
**Final checklist:**
- Customizable
- Lots of settings to change how it looks
- [ x ] I know how to properly use check boxes 
- [ ] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
Yes I agree we need chat suffix | ʌгᴇѕ+ « ᴋᴀᴍɪ ʙʟᴜᴇ ᴏɴ ᴛᴏᴘ » » ˢⁿᵒʷ⏐ НεᎮнᗩεѕƭυѕ » ʙᴀᴄᴋᴅᴏᴏʀᴇᴅ | ᴍᴇᴏᴡ » ᴜɴɪᴄᴏʀɴɢᴏᴅ.ɢɢ  ꜱᴇᴘᴘᴜᴋᴜ | ʜᴜᴢᴜɴɪɢʀᴇᴇɴ.ɢɢtm » ʙᴀᴄᴋᴄʟɪᴇɴᴛtm » ɴᴏᴜ ʟᴇᴀᴋ  ⏐ ғᴏʀɢᴇʀᴀᴛ ♡ | ӨBΛMΛ ᄃᄂIΣПƬ - ᴇʟᴇᴍᴇɴᴛᴀʀꜱ.ᴄᴏᴍ 》ᴏꜱɪʀɪꜱ | WÔÔKÏÊ ÇLîëÑTtm {ʀᴀɪᴏɴᴋᴇᴋ} ッ Ｒ００Ｔ｜ ᴠᴏɪᴅ ᴄʟɪᴇɴᴛ ｜ ᴋᴀᴍɪ ｜ ʳᴜˢʰᴇʳʰᴀᶜᵏ ｜ ⓌⓌⒺ ｜ ｉｍｐａｃｔ｜ ꜰᴜᴛᴜʀᴇtm ⓖⓞⓛⓓ ｜ 卂丂ㄩ几卂ᴄʟɪᴇɴᴛ ｜ꄘꆂ꒓ꁍꍟꑛꋫꇓ ｜ ʳᴀｔᴄʟɪᴇɴᴛ ｜ ᴀᴘᴏʟʟʏᴏɴ ｜ ᴋᴀᴍɪ ʙʟᴜᴇ ❘ ᴾᴼᴾᴮᴼᴮ ᶜᴸᴵᴱᴺᵀ ⏐ ɢᴀʏ ⏐  c l i e n t |  B a L l C l i E n T

**Comment by Z3R0-cmd** [comment]
lol

**Comment by Z3R0-cmd** [comment]
u forgot w+2 suffix tho

**Comment by THEREALWWEFAN231** [comment]
#606 Chat Suffix is the stupidest "feature".
