### ISSUE TITLE
illegal reflective access operation

### ISSUE THREAD

**Issue by sillysimon** [THEREALWWEFAN231/Inertia#1091]
**Inertia Utility Mod version:** 

Inertia Client 3.1.3 - 1.16.5
**Minecraft version:** 
1.16.5
**Operating system:** 
EndevourOS (Archlinux derivative)
**Optifine/Other mods:** 
none
**What's the issue:** 
I discovered the following in my logs:
```
[16:39:46] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by inertia.InjectedInvoker/0x000000080098c040 (file:/home/simon/.local/share/multimc/instances/1.16.5/.minecraft/mods/Inertia%20Client%203.1.3%20-%201.16.5.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of inertia.InjectedInvoker/0x000000080098c040
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
I don't know much about modding but the message makes it look like there could be a problem with future releases of something (I presume LWJGL because it was the last thing to load before the warning)
**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia. 

Edit:
here the full log: https://hatebin.com/bcajnqbqbq

**Comment by Gav06** [comment]
i normally see that even when playing vanilla

**Comment by THEREALWWEFAN231** [comment]
Huh this should work fine, the log you sent says you are using java 11 and if I recall correctly, Inertia works from java 8-11, it crashes in java 12, but maybe try with a lower java version, I would suggest java 8. You will have to install java 8 if you don't have it already, then make the fabric profile use the java 8 instead of 11.

**Comment by czho** [comment]
Can confirm openjdk 11+ doesn't play nice with Minecraft on linux.

**Comment by Paralusion** [comment]
using Java 8 should fix this
