### ISSUE TITLE
Killaura - Nametagged & specific entities

### ISSUE THREAD

**Issue by Sxmple-DavidSchmidt** [THEREALWWEFAN231/Inertia#1092]
I was looking for a way for me to disable KA for entities with nametags, because I tend to leave it on out of lazyness wich just fucks up my entity based farms every once in a while. Is there a way for me to implement this myself or have you do it? I too would love something along the lines of entities that are attacked in intertia. Something like .killaura entitylist add pigmen. Thanks for the great client!

**Comment by Paralusion** [comment]
use the proper suggestion template
