### ISSUE TITLE
Bug killaura does not attack hoglins

### ISSUE THREAD

**Issue by egsland** [THEREALWWEFAN231/Inertia#1093]
**latest: downloaded today :** 
**1.16.5:** 
**windows OS:** 
**Optifine/Other mods: NOPE** 

**What's the issue: kill aura doesn’t attack hoglins and baby hoglins** 

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [yes ] I know how to properly use check boxes 
- [ yes] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [ yes] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Paralusion** [comment]
would be fixed with #27
