### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by FireBlaster101** [THEREALWWEFAN231/Inertia#1095]
Sodium not working with Baritone on 1.16.5

**Comment by constantinDev** [comment]
no shit sherlock

remove sodium or baritone

**Comment by feliscatusmeows** [comment]
Will be fixed whenever @THEREALWWEFAN231 updates baritone to the latest release, look in the pins of #offtopic in the discord for a fix.

**Comment by Paralusion** [comment]
Baritone related issue
