### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by danzaa** [THEREALWWEFAN231/Inertia#1096]
**Inertia Utility Mod version:3.1.3** 
**Minecraft version:1.16.4** 
**Operating system:widowns** 
**Optifine/Other mods:sodium modmenu mini hud** 

**What's the issue:i cant see when im holding somthing it was the hack name tag ** 

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [ ✅] I know how to properly use check boxes 
- [ ❎] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [✅ ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by constantinDev** [comment]
[x] you dont know how to use check boxes

nametags are a bit wonky with rendering, if you turn it off it should work. Also try disabling the player head viewer inside the nametag options.

**Comment by Paralusion** [comment]
known bug with nametags
