### ISSUE TITLE
Mod loading issue / compatibility

### ISSUE THREAD

**Issue by Lxipwastaken** [THEREALWWEFAN231/Inertia#1097]
When trying to load with the mod / mods Origins and Origins Classes it will crash and show an error:

"
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1
"

I believe this is caused by optifine as other people have described incompatibility with this mod and optifine. 

Good day.

**Comment by feliscatusmeows** [comment]
Please list your other mods

**Comment by Lxipwastaken** [comment]
As of right now it is:
Cardinal Components (Api I think)
Fabric API
Immersive portals
Origins 
Origins Classes

(Trying to use Inertia with this)

I have done individual testing on where the issue might be. And from what I have seen is Origins I have the issues with. (Origins / Origins Classes)

**Comment by feliscatusmeows** [comment]
This is an incompatibility with a non-client side mod and likley will not be fixed.

**Comment by Lxipwastaken** [comment]
Ok, Thank you for your time.

**Comment by Paralusion** [comment]
incompatibility issue
