### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TheRegularDBJ** [THEREALWWEFAN231/Inertia#1099]
**Inertia Utility Mod version: 3.1.3** 
**Minecraft version: 1.16.5** 
**Operating system: Windows 10 64-bit** 
**Optifine/Other mods:** 

**What's the issue:** 
Click Gui panels won't open

(btw im new to inertia)

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [X] I know how to properly use check boxes 
- [X] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [X] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by THEREALWWEFAN231** [comment]
Bruh, right click, not left click.

**Comment by TheRegularDBJ** [comment]
oof
