### ISSUE TITLE
Hello! Could you add BookBot to Inertia Client?

### ISSUE THREAD

**Issue by kielet** [THEREALWWEFAN231/Inertia#1100]
**Minecraft Version(s)**

Could you add BookBot

We could write books faster

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by constantinDev** [comment]
https://github.com/AriliusClient/BookBot

**Comment by THEREALWWEFAN231** [comment]
.randombook
