### ISSUE TITLE
Couple of Suggestions.

### ISSUE THREAD

**Issue by Not-Anatrax** [THEREALWWEFAN231/Inertia#1102]
Make Boat Phase work when you mount mobs.

Make a suggestions tab in discord

Allow IRC Mods to have irc moderation commands ingame when the bot is down.

**Comment by Not-Anatrax** [comment]
Mobs being Pig's and Horses

**Comment by THEREALWWEFAN231** [comment]
You want your horses and pigs to die 😦

**Comment by feliscatusmeows** [comment]
blink phase :sunglasses:

**Comment by Paralusion** [comment]
suggestion tab in discord is never going to happen

**Comment by Paralusion** [comment]
use proper suggestion template
