### ISSUE TITLE
Bug Baritone is practically broken

### ISSUE THREAD

**Issue by DeadMilan** [THEREALWWEFAN231/Inertia#1105]
**1.16.4** 
**1.16.5** 
**windows 10** 
**no other mods** 

**baritone finds where to go but wont move there** 

** didnt crash**

**Final checklist:**

- [/ ] I know how to properly use check boxes 
- [ /] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [/] I have attempted to reproduce this bug using the latest available release of Inertia.

**Comment by constantinDev** [comment]
remove sodium

**Comment by DeadMilan** [comment]
> remove sodium

never installed it

**Comment by Paralusion** [comment]
send a screenshot of your mods folder

**Comment by DeadMilan** [comment]
> send a screenshot of your mods folder



> which mods did you install
![image](https://user-images.githubusercontent.com/79657790/109397368-7c90ee80-7936-11eb-9f45-c0b577932ecb.png)

**Comment by DeadMilan** [comment]
> which mods did you install



> send a screenshot of your mods folder

I do have other mods but they're not fabric or 1.16.4. I do have baritone specifically but its for 1.12.2

**Comment by constantinDev** [comment]
jesus that mods folder is dirty

**Comment by DeadMilan** [comment]
> jesus that mods folder is dirty

you wouldn't want to see my 1.12.2 one.

**Comment by feliscatusmeows** [comment]
Make sure that .b allowbreak is set to true.

**Comment by feliscatusmeows** [comment]
Also you need tools in your hotbar

**Comment by DeadMilan** [comment]
> **1.16.4**
> **1.16.5**
> **windows 10**
> **no other mods**
> 
> **baritone finds where to go but wont move there**
> 
> ** didnt crash**
> 
> **Final checklist:**
> 
> * [/ ] I know how to properly use check boxes
> * [ /] I have tried to reproduce this bug after removing all other mods except for Inertia.
> * [/] I have attempted to reproduce this bug using the latest available release of Inertia.

I think the problem was the anti-cheat on the server i was on. the anti-cheat is really strict even though its an anarchy server since player data can be corrupted by a lot of stuff. I think its the anti-cheat because it disconnects when i use baritone but when I'm not using it it does nothing so i think the anti cheat was messing with me.
