### ISSUE TITLE
bug client keeps crashing

### ISSUE THREAD

**Issue by ilanbirn** [THEREALWWEFAN231/Inertia#1106]
**Inertia Utility Mod version: 3.1** 
**Minecraft version: 1.16.5* 
**Operating system:windows** 
**Optifine/Other mods: fabric API, book and quil dupe mod** 

**What's the issue: it keeps crashing when I leave a multiplayer server then rejoins then it crashes** 

**Crash-report(if applicable)(Would be very useful also please format): an unexpected issue occurred and the game has crashed. we are sorry for the inconvenience. exit code 0**

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x] I have attempted to reproduce this bug using the latest available release of Inertia.

**Comment by constantinDev** [comment]
issue with 1.16.5, also have that issue. nothing i tried really helps except for turning off autoreconnect.

**Comment by feliscatusmeows** [comment]
Support is not given for other mods

**Comment by constantinDev** [comment]
> Support is not given for other mods

its not an issue with another mod, its a inertia issue.

**Comment by feliscatusmeows** [comment]
> Optifine/Other mods: fabric API, book and quil dupe mod

**Comment by ilanbirn** [comment]
> issue with 1.16.5, also has that issue. nothing I tried really helps except for turning off auto-reconnect.

@constantinDev so are you saying I need to turn off auto reconnect

**Comment by feliscatusmeows** [comment]
Yes that is what he is saying

**Comment by ilanbirn** [comment]
> Yes that is what he is saying

I attempted without mods aswell, not working
same problem

**Comment by feliscatusmeows** [comment]
Try reseting your config by going into .minecraft/inertia and deleting everything there

**Comment by THEREALWWEFAN231** [comment]
Try what @feliscatusmeows said, firstly without the crash log, I can't fix it, also if your using 3.1 it probably doesn't work on 1.16.5, you need to use 3.1.3, But I assume you just made a mistake and said 3.1 when it's 3.1.3.

**Comment by Paralusion** [comment]
Create a new issue and provide a crash log
