### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CriticalHex** [THEREALWWEFAN231/Inertia#1110]
**Version: 1.16.5**

**Suggestion: Block Picker for XRay**

**Why: Netherite doesn't seem to be XRayed by default, and there isn't a way to change that. Picking the blocks you'd like to see in XRay is a common feature and useful for finding bases, and certain blocks you might be looking for, as well as exclude some, like purpur blocks.**

**Comment by Silverwolf2332** [comment]
Already a thing

.xray gui
