### ISSUE TITLE
Give command and custom enchanments and attribute modifier

### ISSUE THREAD

**Issue by WahidIslamLinad** [THEREALWWEFAN231/Inertia#1112]
Please add give command to bypass give permission access on servers with creative mode..for example wurst has it and also aristois kinda..but i like this client so i dont want to switch to other client for this single reason..so hope devs will try to add this feature..thank you

**Comment by Paralusion** [comment]
You may be able to add this feature yourself using the Inertia API after the new Inertia version gets released.

**Comment by Paralusion** [comment]
use proper template when creating issue
