### ISSUE TITLE
Interacting with mod menu

### ISSUE THREAD

**Issue by WahidIslamLinad** [THEREALWWEFAN231/Inertia#1122]
**Minecraft version: 1.16.4** 
**Operating system:Win 10 x64** 
**Optifine/Other mods: Mod menu** 

**What's the issue:** 
Can't use inertia option if I have mod menu at the same time..the mod menu button overlays it...

**Comment by THEREALWWEFAN231** [comment]
We don't generally support other mods, but this is already changed in the next update(when ever that is)/current prebuilds.
