### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MozambiqueClientUser53** [THEREALWWEFAN231/Inertia#1123]
Version 3.1.3 
1.16.4
Windows
Meteor client is the other mod

If i use Meteor Client with Inertia Baritone does not work, like the weird red path things show up but Baritone just doesn't start moving. it is so weird

no crash

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x

https://user-images.githubusercontent.com/80639504/111076856-da0c6a00-84f6-11eb-9fe5-3f1f9204fd8c.mov

 ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Paralusion** [comment]
the fix is to not use multiple mods

**Comment by AutistEren** [comment]
open inertia.jar with winrar/7zip or whatever you have
delete the baritone folder,
delete baritone mixin files,
restart your game.

not sure if it will fix but but it should

**Comment by MozambiqueClientUser53** [comment]
> open inertia.jar with winrar/7zip or whatever you have
> delete the baritone folder,
> delete baritone mixin files,
> restart your game.
> 
> not sure if it will fix but but it should

It did not work. now game crashes when launched

**Comment by feliscatusmeows** [comment]
Re install inertia, then delete delete the "baritone" folder, delete mixins.baritone.json, delete mixins.baritone.refmap.json

**Comment by Paralusion** [comment]
Open your Minecraft Launcher, go to Installations (top left), select the profile you are using for Inertia (should be either Fabric or Forge) and press "MORE OPTIONS".
Now, go all the way to the end of your JVM Arguments and add `-Ddisablebaritone=true` in the text box. Press save and try to launch the game again. (it needs to be at the END of the JVM arguments)

**Comment by MozambiqueClientUser53** [comment]
thanks you everyone i got it work!! now i can use baritone
