### ISSUE TITLE
Add tracers to ESP

### ISSUE THREAD

**Issue by GalaxyShadow777** [THEREALWWEFAN231/Inertia#1126]
**Minecraft Version(s)** 1.16.4/1.16.5

**What is the suggestion** adding tracer mechanics to ESP (not blockESP)

**Why would this feature be useful** in mineshaft exploring we can use a combo of ESP (with the proposed tracer mechanincs), BlockESP (on spawners [optional]) and ocasionally freecam to gather all resources in under 30 mins (less if spawners are not seek).

**Final checklist:** tracer mechanics in regular ESP

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by Paralusion** [comment]
wait.. this is just the module called tracers..
