### ISSUE TITLE
Bug | Inertia Crashing upon startup with Origins mod

### ISSUE THREAD

**Issue by rainbow-glitch** [THEREALWWEFAN231/Inertia#1127]
**Inertia Utility Mod version:** 
 Newest at the time of reporting(3.1.3)
**Minecraft version:** 
 1.16.5
**Operating system:** 
 Win10 Pro
**Optifine/Other mods:** 
![image](https://user-images.githubusercontent.com/63537670/111474117-fe9d5780-872b-11eb-9c99-c37248a62326.png)

**What's the issue:** 
Attempting to start inertia with the origins mod crashes it
(I also did as said in this issue because I have tweakeroo #1072 _it also would not work without tweakeroo_ should i do this with every mod in the list?)
Anything I could try to resolve this?

**Crash-report(if applicable)(Would be very useful also please format):**
https://paste.ee/p/4jQiP

**Final checklist:**
- [x] I know how to properly use check boxes 
- [ ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x] I have attempted to reproduce this bug using the latest available release of Inertia.

**Comment by FeyXieXzf** [comment]
If Inertia cannot start with it, then it's just not compatible.

**Comment by FeyXieXzf** [comment]
Don't report these kinds of things as bugs!

**Comment by Paralusion** [comment]
issue contains a lot of other mods
