### ISSUE TITLE
elytra chestplate swap

### ISSUE THREAD

**Issue by dadudeme** [THEREALWWEFAN231/Inertia#1135]
1.9+

create a feature that on hotkey activation swaps between elytra and chest plate.

it makes swapping between rtavel and combat easier.

**Final checklist:**

-  [x] I know how to properly use check boxes 

- [x] This is not a suggestion for baritone or other mod

**Comment by TheHeiki** [comment]
now this is big brain time

**Comment by feliscatusmeows** [comment]
I did this by binding auto armor and elytra replace to the same key.

**Comment by Paralusion** [comment]
@feliscatusmeows method works fine for this
