### ISSUE TITLE
[close me] [Bug] If you hit entities while Blood Particles are enabled it plays the block break sound

### ISSUE THREAD

**Issue by GalaxyLinus** [THEREALWWEFAN231/Inertia#1136]
**Inertia Utility Mod version:**
newest
**Minecraft version:** 
1.16.4
**Operating system:** 
Windows
**Optifine/Other mods:** 
A lot, but they don't change anything, I tested it

**What's the issue:** 
If you hit entities while Blood Particles are enabled it plays the block break sound

**Crash-report(if applicable)(Would be very useful also please format):**
Doesn't Crash, just annoyes me

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Paralusion** [comment]
i'm pretty sure that's done on purpose..

**Comment by GalaxyLinus** [comment]
yes, just found out how to disable :/ sorry

**Comment by AutistEren** [comment]
you can close the issue yourself :(
