### ISSUE TITLE
Parkour

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#114]
**Quick Description**
A module to help with parkour jumps, with Blink integration.

**The Issue**
Let's face it - either the parkour is bad, or you're just bad at parkour. We should find a way that allows us to hit parkour jumps with almost full consistency.

**My Suggestion for Developers**
Simply jump at the edge of a block. A setting would be called "Blink" that would be enabled upon enabling parkour, where the client jumps at the edge of a block, and if the player lands then disable blink (or just send the packets one at a time, to make it look like a legit run). If the player falls one block below their orriginal jump height, however, cancel the blink packets and put the user back (block movement for split second so the user doesn't accidentally run off lol)

**Additional Context**
 Blink mode would be super OP and ensure that you would always make the jump (at least to anyone else's perspective)

**Comment by Paralusion** [comment]
added in latest prebuilds
