### ISSUE TITLE
1.16.5Suggestion Add anchor aura for pvp

### ISSUE THREAD

**Issue by qwerrtttttttty** [THEREALWWEFAN231/Inertia#1142]
**Minecraft Version(s)**

**What is the suggestion**

**Why would this feature be useful**

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] This is not a suggestion for baritone or other mod

**Comment by THEREALWWEFAN231** [comment]
I mean, damn, don't use the template 😳 , this is already planned/added to the 1.16 version, but not yet completed(I mean it works, but I have other plans) but it should be in the next update when ever that is 🤷‍♂️

**Comment by qwerrtttttttty** [comment]
can you make the auto totem faster pls


Pada tanggal Sab, 3 Apr 2021 pukul 13.28 THEREALWWEFAN231 <
***@***.***> menulis:

**Comment by feliscatusmeows** [comment]
The reason autototem fails is due entirety to ping.

**Comment by qwerrtttttttty** [comment]
is there a setting to make the crystal aura auto place and fast

Pada tanggal Sab, 3 Apr 2021 pukul 23.39 feliscatusmeows <
***@***.***> menulis:

**Comment by feliscatusmeows** [comment]
:pain: That will be in inertia 3.2.

**Comment by qwerrtttttttty** [comment]
when is the update?


Pada tanggal Min, 4 Apr 2021 pukul 09.58 feliscatusmeows <
***@***.***> menulis:

**Comment by feliscatusmeows** [comment]
The update will come in the next [0-8974356459267843265864825684625642] hours. Please be patient.

**Comment by Paralusion** [comment]
duplicate of #922 and already planned
