### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bamna-dot** [THEREALWWEFAN231/Inertia#1143]
1.16..5
being able to set binds to presets 

the command would go like .bind set preset _____

so you always dont have to go into click gui if you want to swap it easiy

- [x] I know how to properly use check boxes 
- [ ] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
Step 1. Click inertia options
Step 2. Open macros
Step 3. Make a macro do .value note_bot mode 5x5
Step 4. Bind that macro to a key
Step 5.????????
Step 6. Profit!!!!!!!$$$$💰💰💰💰💰

**Comment by feliscatusmeows** [comment]
Shoot I mean .preset load UwU

**Comment by THEREALWWEFAN231** [comment]
Do what @feliscatusmeows said, load a preset with a macro, .preset load presetname
