### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MRPatatesYK** [THEREALWWEFAN231/Inertia#1148]
**1.16.5**

**Disable İnertia**

**Because some times i want to play it legit but not with deleting the mod from the folder**

**Final checklist:**

- [x] I know how to properly use check boxes 
- [ ] This is not a suggestion for baritone or other mod

**Comment by GaiaB0t** [comment]
well... you can just turn everything off, including the hud, or you can use something like multimc, which is a launcher that uses multiple mini .minecraft profiles for different modsets

**Comment by MRPatatesYK** [comment]
But i want to disable it because some of the servers like hypixel can learn that u use hacked client sry for bad english

**Comment by MRPatatesYK** [comment]
Even that u turned everythink off

**Comment by Paralusion** [comment]
merged with #944
