### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kolders888** [THEREALWWEFAN231/Inertia#1149]
**Minecraft Version(s)** 1.16.5 

**What is the suggestion** Add TP-Aura.

**Why would this feature be useful** It would be useful for anarchy pvp,sometimes.

**Final checklist:** 

 

- [   ] I know how to properly use check boxes 

- [ ] This is not a suggestion for baritone or other mod

**Comment by Paralusion** [comment]
duplicate of like 10 other tp aura issues

**Comment by Paralusion** [comment]
duplicate of #637
