### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kolders888** [THEREALWWEFAN231/Inertia#1151]
**Minecraft Version(s)** ALL

**What is the suggestion** Disable Baritone commands./Make baritone not pick up commands without the dot.

**Why would this feature be useful** Well,I think it would be useful for the following reasons: 1.You would be able to say for an example the word 'stop' without baritone thinking it is a command. And instead Baritone should pick up only the commands that have an dot.

**Final checklist:**

- [ x ] I know how to properly use check boxes 
- [ x ] This is not a suggestion for baritone or other mod

**Comment by Kolders888** [comment]
And yes,I do know I gave only one reason.I couldn't think of more but the point is,you'll be able to say stuff that would normaly be picked up by baritone,thinking it's a command.

**Comment by GaiaB0t** [comment]
there is the command #chatcontrol false, but _I still dont know why wwefan hasnt set it to be default to false in prebuilds even_
maybe he has and I never noticed, but yea... "#chatcontrol false" until then

**Comment by Kolders888** [comment]
> #chatcontrol false

Thank you GaiaB0t

**Comment by feliscatusmeows** [comment]
Wwefan can you set the default to false tho? Or make an option to force it to false because it keeps coming up for i don't know why.
