### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by anonfoxer** [THEREALWWEFAN231/Inertia#1153]
**Minecraft Version(s)**
All supported versions of Inertia

**What is the suggestion**
An option to hide the "Inertia Options" button in the ESC menu.

**Why would this feature be useful**
Some servers that do jail checks (i.e. jail a player, ask for F3 menu n such), will use this as well as the texture packs screen to check for things like Fabric. While I dont think it is possible to hide Fabric as a texture pack item, Hiding the "Inertia Options" button would allow people to pass it off as just running Sodium when trying to bypass checks like this.

**Final checklist:**

- [ x ] I know how to properly use check boxes 
- [ x ] This is not a suggestion for baritone or other mod
- [ x ] Gluten free

**Comment by GaiaB0t** [comment]
not a ghost client
this will never happen

**Comment by anonfoxer** [comment]
> not a ghost client
> this will never happen

Yet there are options for semi legit functions in the client. Even if it isn't a ghost client outright, this could be a fairly useful feature.

**Comment by GaiaB0t** [comment]
it is for anarchy servers and ones that allow clients
if an anarchy server "jail checks" then dont play that server

**Comment by anonfoxer** [comment]
> it is for anarchy servers and ones that allow clients
> if an anarchy server "jail checks" then dont play that server

Fair enough, though this could've been explained in the first comment, and couldve been done so a bit more profressionally.

**Comment by Paralusion** [comment]
> > it is for anarchy servers and ones that allow clients
> > if an anarchy server "jail checks" then dont play that server
> 
> Fair enough, though this could've been explained in the first comment, and couldve been done so a bit more profressionally.

you're getting a reply from someone who helps out from the community.. and even if the creator commented on this, he isn't getting paid thousands of dollars to deliver this service to you.. don't expect any professional treatment from someone who does this as a hobby project..

**Comment by anonfoxer** [comment]
> > > it is for anarchy servers and ones that allow clients
> > > if an anarchy server "jail checks" then dont play that server
> > 
> > 
> > Fair enough, though this could've been explained in the first comment, and couldve been done so a bit more profressionally.
> 
> you're getting a reply from someone who helps out from the community.. and even if the creator commented on this, he isn't getting paid thousands of dollars to deliver this service to you.. don't expect any professional treatment from someone who does this as a hobby project..

Its not expecting it from someone whos doing it as a hobby product because I believe its a well funded and well backed service. I say that because I believe the footprint you leave on public github repositories, especially if you end up pursuing a career in software development, computer science, etc (fields where they will check a public github page if you have one, which you should if you're going into those fields), leaves a pretty big impact on employers, so a somewhat professional attitude goes well to the future.
