### ISSUE TITLE
Keeps crashing when using .dupe

### ISSUE THREAD

**Issue by CyberTechist** [THEREALWWEFAN231/Inertia#1154]
Kindav self explanatory from the title. I use .dupe hand, and minecraft crashes. I haven't even seen any documentation on it, and I've looked everywhere for an explanation. For details, I am playing on hardcore singleplayer.

**Comment by snoopchallenge** [comment]
.dupe uses the 11/11 dupe also known as the jump dupe which got patched in 1.11. It disconnects you from the server but shouldn't crash. I think this is still included in inertia because via version (by the way you can do .help [command] and I think it tells you about the command.)

**Comment by feliscatusmeows** [comment]
Also this was patched in 1.14.3.

**Comment by CyberTechist** [comment]
> .dupe uses the 11/11 dupe also known as the jump dupe which got patched in 1.11. It disconnects you from the server but shouldn't crash. I think this is still included in inertia because via version (by the way you can do .help [command] and I think it tells you about the command.)
> 
> Edit: I think it might be do with being in singleplayer, try to do the dupe on a multiplayer server and see if it affects anything

Lol ur the only one who actually helped me, everyone was saying 1.14(someone said this recently) but I've been playing on 1.12, thanks

**Comment by feliscatusmeows** [comment]
Why are you using inertia client in hardcore singleplayer?

**Comment by Paralusion** [comment]
.dupe was patched in 1.14.3, and does not work on most non-vanilla servers: i don't think this dupe works on singleplayer.
