### ISSUE TITLE
Rotate hack

### ISSUE THREAD

**Issue by Ral721chanel** [THEREALWWEFAN231/Inertia#1155]
Put the rotate hack to make it almost impossible for them to hit us.
A clear example is this video: https://youtu.be/vZ17OeNa784

**Comment by AutistEren** [comment]
so you want target strafe

**Comment by Ral721chanel** [comment]
Yes

dum., 11 apr. 2021, 11:22 AutistEren ***@***.***> a scris:

**Comment by snoopchallenge** [comment]
Wouldn't this get you killed immediately?

**Comment by Paralusion** [comment]
please suggest again using the proper template
