### ISSUE TITLE
dude if i use braitone it stuck and cannot move waht i do

### ISSUE THREAD

**Issue by harshjha112** [THEREALWWEFAN231/Inertia#1159]
**Inertia Utility Mod version:** 
**Minecraft version:** 
**Operating system:** 
**Optifine/Other mods:** 

**What's the issue:** 

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [ ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by snoopchallenge** [comment]
I also have this issue using Sodium/Lithium/Phosphor, resetting baritones settings still leads to it being still

**Comment by Paralusion** [comment]
not related to Inertia & please fill in the template next time
