### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by harshjha112** [THEREALWWEFAN231/Inertia#1160]
**Inertia Utility Mod version:** 
**Minecraft version:1.16.5
**Operating system:window
**Optifine/Other mods:** 

**What's the issue:i cannot move or the ai dosent mine the block i need . it stuck there wht do

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [ ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by feliscatusmeows** [comment]
This is for baritone, not inertia. Why are you reporting a baritone bug here?

**Comment by Paralusion** [comment]
not related to Inertia
