### ISSUE TITLE
Inertia overwrite title of Costum Title Window mod

### ISSUE THREAD

**Issue by comand100vip** [THEREALWWEFAN231/Inertia#1161]
**Inertia Utility Mod version: 3.1.3** 
**Minecraft version: 1.16.5** 
**Operating system: Windows 8.1** 
**Optifine/Other mods: Book dupe, Custom Window Title** 

**What's the issue: I add mod "Custom Windows Title to change title of minecraft window then playing, but inertia overwrite it with "Inertia Version 3.1.3""** 

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [X] I know how to properly use check boxes 
- [ ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by AutistEren** [comment]
inertia takes priority over other mods

**Comment by comand100vip** [comment]
> inertia takes priority over other mods

But can I change it?
What file in .jar contain title?

**Comment by AutistEren** [comment]
you cant edit the .jar since inertia is close source

**Comment by comand100vip** [comment]
> you cant edit the .jar since inertia is close source

I can open it with winrar and there is a lot of files, and there must be somewhere line with title

**Comment by AutistEren** [comment]
you can keep trying to find it but i dont think you will get anywhere 😔

**Comment by comand100vip** [comment]
> you can keep trying to find it but i dont think you will get anywhere

Ok. So I will find it.

**Comment by THEREALWWEFAN231** [comment]
Add -Ddisabletitle=true to your fabric 1.16.5 jvm arguments, though the minecraft launcher, to make inertia not change the title, not sure if the other mod will still work, but the title won't be Inertia x x x x x x also is this releated to #1162 ?
