### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by comand100vip** [THEREALWWEFAN231/Inertia#1162]
**Minecraft Version(s): All**

**Create posibbility to change title of window(I mean to change "Inertia Version 3.1.3")**

**Because to change it and on discord show it as "Minecraft 1.16.5", not Inertia Version 3.1.3, or "Broken Luncher" etc**

**Final checklist:**

- [X] I know how to properly use check boxes 
- [X] This is not a suggestion for baritone or other mod

**Comment by snoopchallenge** [comment]
You can turn off discord rpc but why not want everyone knowing you're using the best client

**Comment by THEREALWWEFAN231** [comment]
I'm confused by this report/suggestion, I assume what @snoopchallenge said does what you want, turning off the Discord RPC module will not show the Inertia Discord thing.

If this wasn't what you were looking for, feel free to leave a comment.
