### ISSUE TITLE
bug my game crash because I got banned on server please fix Crash-report The game crashed whilst rendering screen Error: java.lang.NullPointerException: Screen cannot be null

### ISSUE THREAD

**Issue by test4514** [THEREALWWEFAN231/Inertia#1163]
**Inertia Utility Mod version:** 
**Minecraft version:** 
**Operating system:** 
**Optifine/Other mods:** 

**What's the issue:** 

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [ ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Paralusion** [comment]
Please use the actual template, otherwise we won't know how to solve your issue..

**Comment by Paralusion** [comment]
use the actual template
