### ISSUE TITLE
Bug with jvm arguments

### ISSUE THREAD

**Issue by comand100vip** [THEREALWWEFAN231/Inertia#1167]
**Inertia Utility Mod version: 3.1.3** 
**Minecraft version: 1.16.5** 
**Operating system: Windows 8.1** 
**Optifine/Other mods: Custom Windows Title** 

**What's the issue: Inertia is still reseting jvm arguments and I can't give it 7Gb ram and -Ddisabletitle=true to not change the title.** 

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [X] I know how to properly use check boxes 
- [X] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [X] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by feliscatusmeows** [comment]
Which launcher are you using?

**Comment by THEREALWWEFAN231** [comment]
As @feliscatusmeows mentioned, it's probably your launcher, Inertia can't change your jvm arguments, nor would it stop you from giving 7GB of ram, maybe you aren't editing the correct installation, make sure you are editing the same exact fabric 1.16.5 profile that you click play to run Inertia with.

**Comment by comand100vip** [comment]
I am using Official Minecraft Luncher, and I am 100% sure I am editing fabric loader.
