### ISSUE TITLE
Baritone "Pausing since destination is at the edge of loaded chunks."

### ISSUE THREAD

**Issue by Buckeye12** [THEREALWWEFAN231/Inertia#1183]
**Inertia Utility Mod version: Inertia Client 3.1.3 - 1.16.5** 
**Minecraft version: fabric-loader-1.16.5** 
**Operating system: Latest Windows 10 Home** 
**Optifine/Other mods: None** 

**What's the issue: When I enter a command ex: ".b mine dirt" baritone stands still. The chat debug is, "[Baritone] Pausing since destination is at the edge of loaded chunks." This occurs with every block and distance combination I have used.** 

**Crash-report(if applicable)(Would be very useful also please format): N/A**

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Majora320** [comment]
This is a baritone issue, not an inertia issue. Go report it over [there](https://github.com/cabaletta/baritone) and close this.
