### ISSUE TITLE
Instant crash upon loading into a world

### ISSUE THREAD

**Issue by Majora320** [THEREALWWEFAN231/Inertia#1184]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.4
**Operating system:** Arch Linux
**Optifine/Other mods:** N/A

**What's the issue:** When attempting to create or play on a world, or connect to a server, the game will crash. I've tested this on 1.16.5 as well as 1.16.4 and the same thing happens, but I'll give you the log for 1.16.4 because I have an isolated environment set up there already (if you want one for 1.16.5, though, I can provide that).

**Crash report:** [Here](http://ix.io/3lnQ)

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by FreedomForeverMC** [comment]
Screen cannot be null?

**Comment by Majora320** [comment]
> Screen cannot be null?

I'm not sure what you mean by that?

**Comment by Paralusion** [comment]
Your crash report shows you're using Java Version: 15.0.2, N/A, Inertia does not support this Java version.
Install Java 8 or lower and the issue will be fixed.

**Comment by THEREALWWEFAN231** [comment]
Para is correct, I don't know why I didn't notice this when I first looked at this, Inertia crashes on java12(iirc) and above. You were using java 15, you have to install a lower version(I suggest java 8), and make the fabric profile(used to load inertia) use the java 8 version you installed(I don't know how to do it in multimc, but I'm sure your already know how).
