### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by godlikeone69** [THEREALWWEFAN231/Inertia#1190]
bug on haste 2 can't mine with diamond or netherite with efficiency V pickaxe??
anyway to fix this bug??

**Comment by Godeps2891** [comment]
what

**Comment by Paralusion** [comment]
Try on a singleplayer instance

**Comment by godlikeone69** [comment]
I did play single player

**Comment by Paralusion** [comment]
Was able to replicate issue on a Singleplayer world; behavior is to be expected with client-side potion effects. Works fine on unenchanted tools.
