### ISSUE TITLE
Help.IDK what is this but upon starting a singleplayer world with inertia the game crashes with exit code 255. Help needed.

### ISSUE THREAD

**Issue by GITTER126** [THEREALWWEFAN231/Inertia#1196]
Minecraft Version 1.16.5.
This issue is starting from the morning of 8-May-2021.
Starting a singleplayer world instantly crashes game when loaded with inertia.
When disabled the mod the game runs fine.
I will be attaching the logs as well as a link to the paste.ee website where i have the first instance of the log uploaded
I will also be attaching the logs with the Inertia mod disabled.
Thanking you in advance.
Logs without Inertia Mod: https://paste.ee/p/4KlTH
Logs with Inertia Mod: https://paste.ee/p/XJhLE

**Comment by Godeps2891** [comment]
downgrade to java 8

**Comment by AutistEren** [comment]
download java 8
delete java 9+

**Comment by GITTER126** [comment]
so anything higher than java 8 wont work?

**Comment by THEREALWWEFAN231** [comment]
> so anything higher than java 8 wont work?

Anything higher then java 12 wont work, irrc.
