### ISSUE TITLE
Suggestion: Worldseed Reader

### ISSUE THREAD

**Issue by LunaticLizzie** [THEREALWWEFAN231/Inertia#1208]
Minecraft Version 1.16.5

My suggestion is to add a feature that tells the user of the client the world generation seed of the server they're currently on.

It would be useful on servers with modified chest loot that have /seed disabled.

**Comment by feliscatusmeows** [comment]
That's not how it works, the world seed isn't sent to the client. You're gonna need to use https://github.com/KaptainWutax/SeedCracker

**Comment by Paralusion** [comment]
not possible, if possible in any other way (except for the way @feliscatusmeows told you), make a new issue and explain your method
