### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Human0001** [THEREALWWEFAN231/Inertia#1209]
**Inertia Utility Mod version:**  current
**Minecraft version:**   1.12.2
**Operating system:**  windows
**Optifine/Other mods:**  none
**Launcher:** fabric

**What's the bug:**  Crashes when placing a crafting table while using scaffold and was previously not placing crafting tables and attempts to keep placing and/or walking

**Crash-report(if applicable)(located in .minecraft/latest.log):** 

**Final checklist:**
- [x] I know how to properly use checkboxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attempted to reproduce this bug using the latest available release of Inertia.

**Comment by GaiaB0t** [comment]
how are you on 1.12 but fabric?

**Comment by Cypphi** [comment]
How, just how. And scaffolding with crafting tables works fine for me....

**Comment by Paralusion** [comment]
Make a new issue and provide a crash log
