### ISSUE TITLE
Xray not working

### ISSUE THREAD

**Issue by DentedGamer** [THEREALWWEFAN231/Inertia#1213]
**Inertia Utility Mod version:3.1.3
**Minecraft version:1.16.5
**Operating system:*windows
**Optifine/Other mods: none

X-ray not working/incompatabel with fabric api 

I have played with inertia for a month now and  THE ONLY thing i'm kind of dissapointed in is that xray doesn't work so please make sure this gets compatible with fabric api because reloading the chunks doesn't work for me (i know i need to add/remove blocks i want to xray)

**Final checklist:**
- [x] I know how to properly use check boxes. no
- [ ] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. yes
- [ ] I have attemped to reproduce this bug using the latest available release of Inertia. yes

**Comment by AutistEren** [comment]
either download sodium or remove fabric api
