### ISSUE TITLE
forge

### ISSUE THREAD

**Issue by hackerplayz124** [THEREALWWEFAN231/Inertia#1215]
**Minecraft Version(s)**
all
**What is the suggestion**
add forge mods 
**Why would this feature be useful**
because people trust forge more 
**Final checklist:**

- [ ] put forge mod for all veersion

**Comment by feliscatusmeows** [comment]
How do people trust forge more? Is forge "safer" or something? Fun fact, you can get ratted on forge too, most ratted clients you have heard of, including phobos, were forge mods. If you download suspicious mods on either platform, you're going to get screwed weather it's forge of fabric.

**Comment by Godeps2891** [comment]
mfw replacing the template with your suggestions
