### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Magiclime** [THEREALWWEFAN231/Inertia#1216]
**Minecraft Version(s)**
All.
**What is the suggestion**
Multiple, Here is a list;

1. A spinbot, Should be easy to implement just by using a radial function to send packets to change your angle and change the angle back whenever a click is seen just by getting the user angle.
2. A slight change on how AutoEat functions, Instead of just eating and keeping the selected slot there, Cache the current position in the hotbar and when it is done eating switch back to that position, Should be relatively easy to implement aswell.

**Why would this feature be useful**
1. Not essentially useful, Just is fun.
2. Just a QoL improvement.
3. 
**Final checklist:**

- [x] I know how to properly use check boxes 

- [x] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
> spinbot

did you mean aimbot (already added) or derp(included in prebuilds, will be avilable :soon::tm:)
> autoeat hotbar goes back

Yes, we should add that

**Comment by Magiclime** [comment]
Ah yeh Derp is the one, Looks good!
