### ISSUE TITLE
laucncher

### ISSUE THREAD

**Issue by hackerplayz124** [THEREALWWEFAN231/Inertia#1217]
**Minecraft Version(s)**
all
**What is the suggestion**
you should give x=choices for different launchers
like forge a lot of people use forge even other downloader other people use  
**Why would this feature be useful**
people who don't trust that downloader wont download it so if you do this  you might get more downloads for this
**Final checklist:**

- [ ] i  added forge to different version
- [ ] i added different clients for different versions

**Comment by feliscatusmeows** [comment]
You probably meant modloaders instead of launchers, anyways forge is not a good option for inertia 1.13+ due to them dropping support for coremods and a bunch of other reasons. Also fabricmc is safe, this is like saying windows is safer than Mac os because windows is more popular.

**Comment by hackerplayz124** [comment]
ok but if i get virus it is cause of interia

**Comment by feliscatusmeows** [comment]
Where is there a virus?

**Comment by hackerplayz124** [comment]
can you send link for fabric

**Comment by feliscatusmeows** [comment]
Fabric loader can be downloaded at http://fabricmc.net/use

**Comment by hackerplayz124** [comment]
thx

**Comment by hackerplayz124** [comment]
i am on windows tho wich is safer jar or windows

**Comment by feliscatusmeows** [comment]
Either works
