### ISSUE TITLE
hunt and automine

### ISSUE THREAD

**Issue by hackerplayz124** [THEREALWWEFAN231/Inertia#1219]
**Minecraft Version(s)**
all
**What is the suggestion**
you should have auto mine because it would mine what you want when you are afk and hunt for  it would follow and kill player  when you are afk 
**Why why you should this feature be useful**

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
Automine: type ".b mine diamond_ore" into chat
Hunt: type ".b follow players" in chat then turn on killaura
You can stop either one of these with ".b stop"

**Comment by hackerplayz124** [comment]
thanks you are very helpful
