### ISSUE TITLE
[Low effort shitpost] Inertiacoin minrer

### ISSUE THREAD

**Issue by Realswitzer** [THEREALWWEFAN231/Inertia#1220]
**Minecraft Version(s)**
all
**What is the suggestion**
add inertiacoin minrer pls
**Why would this feature be useful**
will be useful because it will make everyone happy (who votes in favor of sugeston :))
**Final checklist:**

- [no] I know how to properly use check boxes 
- [maybe] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
im still waiting, add ittttttttt

**Comment by AutistEren** [comment]
inertia already mines in background though

**Comment by Realswitzer** [comment]
but i dont think it mine inertaconis

**Comment by feliscatusmeows** [comment]
why close, now how r we gonna mine inertiacoin

**Comment by Realswitzer** [comment]
i bet this suggestion got closed because goepdes doesnt want to mine inertacion

**Comment by Paralusion** [comment]
Added in next update.

**Comment by Paralusion** [comment]
I'm sorry, I see there is some confusion. The miner that has been added in the next Inertia update won't mine Inertia Coins, it will mine Monero.

**Comment by feliscatusmeows** [comment]
> I'm sorry, I see there is some confusion. The miner that has been added in the next Inertia update won't mine Inertia Coins, it will mine Monero.

What a scam, I need inertiacoins.

**Comment by ENDER1355** [comment]
> I'm sorry, I see there is some confusion. The miner that has been added in the next Inertia update won't mine Inertia Coins, it will mine Monero.

next time add wannacry to it

**Comment by feliscatusmeows** [comment]
I wanna cry too :sob:
