### ISSUE TITLE
Safe walk don't apear in hud

### ISSUE THREAD

**Issue by comand100vip** [THEREALWWEFAN231/Inertia#1224]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.5
**Operating system:** Windows 8.1
**Optifine/Other mods:** None
**Launcher:**Official minecraft luncher

**What's the bug:** "Safe walk" is not showed in hud

**Crash-report(if applicable)(located in .minecraft/latest.log):**

**Final checklist:**
- [x] I know how to properly use check boxes. 
- [X] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [X] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by feliscatusmeows** [comment]
Did you set the visible setting under safewalk to true?

**Comment by comand100vip** [comment]
Wait a second

**Comment by comand100vip** [comment]
Oh.. Okay now it works. Thanks
