### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Water73** [THEREALWWEFAN231/Inertia#1227]
Inertia Utility Mod version: 3.1.3
Minecraft version: 1.16.5
Operating system: Windows 10 20H2
Optifine/Other mods: Sodium
Launcher:

**What's the bug:** 
Click GUI not working
**Crash-report(if applicable)(located in .minecraft/latest.log):**

**Final checklist:**
- [x] I know how to properly use check boxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by feliscatusmeows** [comment]
Step 1. Push the right shift key on your keyboard
Step 2. Right click to open the menus
Step 3. ???????
Step 4. Profit!

**Comment by Water73** [comment]
> 
> 
> Step 1. Push the right shift key on your keyboard
> Step 2. Right click to open the menus
> Ste
