### ISSUE TITLE
Everytiem i put this mod on my forge 1.12.2 mods folder it crashes

### ISSUE THREAD

**Issue by Dori-afk** [THEREALWWEFAN231/Inertia#1236]
**Inertia Utility Mod version:** 3,1,3
**Minecraft version:** 1.12.2 forge
**Operating system:** 
**Optifine/Other mods:** the other mods worked fien but ass soon as i isntaled inerita it crashes with error code 0
**Launcher:**Minecraft normal luacnher

**What's the bug:** 
Every time i try to luacnh inertia mod with al my other mods the eroor code 0 comes up, ass soon as i remove the client it works again.
**Crash-report(if applicable)(located in .minecraft/latest.log):**
exit code 0
**Final checklist:**
- [x] I know how to properly use check boxes. 
- [X ] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [ X] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by feliscatusmeows** [comment]
>[x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium.

Please read the checkbox you checked

**Comment by Paralusion** [comment]
:/
