### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Psychogenic88** [THEREALWWEFAN231/Inertia#1237]
**Minecraft Version(s)**
1.16.5

**What is the suggestion**
Add option to turn off the "You are using fabric api or fabric indigo" warning under xrap. For ex, the module could simply be called "Warning" or "Toggle Warning"

![image](https://user-images.githubusercontent.com/83254716/123535899-cfb05d80-d6ec-11eb-9f31-00faca0bfc8b.png)

**Why would this feature be useful**
Less annoying when using other mods that require the api.

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by Godeps2891** [comment]
-Ddisablefabricindigomessage=true jvm argument

**Comment by Psychogenic88** [comment]
Well I'll be damned.
