### ISSUE TITLE
Bug: missing hit boxes module

### ISSUE THREAD

**Issue by Supergamer5465** [THEREALWWEFAN231/Inertia#1239]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.12.2
**Operating system:** Windows 10 64-bit
**Optifine/Other mods:** Optifine, Schematica, Journeymap (they are probably not related to the issue)
**Launcher:**

**What's the bug:** This is a small but that I noticed while building on 2b2t. I was trying to remove the hit boxes module's keybind with the command .bind remove when I noticed that I could remove the keybind with .bind remove hit_boxes, but the preview which shows all of the modules didn't show up after I typed .bind remove

**Crash-report(if applicable)(located in .minecraft/latest.log):**

**Final checklist:**
- [x] I know how to properly use check boxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia. 

![image](https://user-images.githubusercontent.com/64598162/123572326-a695d880-d791-11eb-9715-66364cfa33ed.png)

![image](https://user-images.githubusercontent.com/64598162/123572344-af86aa00-d791-11eb-90ff-b0928a51de49.png)

Below there is no preview
![image](https://user-images.githubusercontent.com/64598162/123572363-b7464e80-d791-11eb-9b2d-83a6f5822d7b.png)

**Comment by feliscatusmeows** [comment]
command still works, but is missing in tab completion

**Comment by THEREALWWEFAN231** [comment]
bind remove command only suggests modules that currently have a bind, meaning it's not showing hit_boxes because it doesn't have a keybind at the current moment.
