### ISSUE TITLE
AntiHunger: "Efficient" Mode

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#124]
**What is the suggestion**
Seperate mode for AntiHunger labeled "Efficient" (compared to Normal mode), whereas movement packets will stop being sent if the player is standing still.
**Why it will be useful**
No movement packets = waaayyy less hunger being spent. Especially for hard(core) servers where hunger drains from just standing still.

The one issue that could come from this is dropping items, which will drop to where you were looking when you first topped, since looking shouldn't send movement packets too often as to waste hunger even further.

**Comment by Paralusion** [comment]
a revamp of the antihunger function has been added
