### ISSUE TITLE
Please Update viaversion

### ISSUE THREAD

**Issue by Haocen2004** [THEREALWWEFAN231/Inertia#1243]
**Minecraft Version(s)**
all
**What is the suggestion**
update the viaversion
**Why would this feature be useful**
use this client for 1.17.1 server
**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by Godeps2891** [comment]
implemented in prebuilds some time ago

**Comment by feliscatusmeows** [comment]
To 1.17.1?
