### ISSUE TITLE
Bug: Nether does not render properly

### ISSUE THREAD

**Issue by Errorcrafter** [THEREALWWEFAN231/Inertia#1244]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.12.2
**Operating system:** win10
**Optifine/Other mods:** Optifine + Latest Ares release
**Launcher:** Vanilla launcher

**What's the bug:** Entering the nether causes a whole bunch of visual glitches as shown in the screenshot. None of these are present in the overworld, and they go away when i press F1.

![image](https://user-images.githubusercontent.com/69189354/125451481-efc3d365-4b02-4dbe-8177-fc16d343a164.png)

**Final checklist:**
- [x] I know how to properly use check boxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attempted to reproduce this bug using the latest available release of Inertia.

**Comment by 0x150** [comment]
optifine moment
