### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by llefnof** [THEREALWWEFAN231/Inertia#1245]
Inertia Utility Mod version: 3.1.3
Minecraft version: 1.16.5
Operating system: win10
Optifine/Other mods: No Optifine + Baritone
Launcher: Vanilla Launcher

What's the bug: X-Ray Show Visual Ore

https://cdn.discordapp.com/attachments/858963454936350720/864709595762917396/stop_faking_me_interia.png

**Comment by llefnof** [comment]
yes too much ore and fake ore

**Comment by feliscatusmeows** [comment]
Antixray, ask @0x150 for his antiantixray solution
