### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by CrystalAura** [THEREALWWEFAN231/Inertia#1246]
When i join a server and move around for like 10 seconds, my minecraft closes and crashes
Bug: The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.j
Exit Code: -1

**Comment by AutistEren** [comment]
remove "-noverify" or "Xverify:none" from your jvm arguments
