### ISSUE TITLE
Incompatibility 

### ISSUE THREAD

**Issue by Azexxx** [THEREALWWEFAN231/Inertia#1253]
**Inertia Utility Mod version:** 3.3
**Minecraft version:** 1.16.5
**Operating system:** Windows 10
**Optifine/Other mods:** Baritone,Fabric API,Hydroden,Lithium,Mod Menu,Smooth Bot,Sodium
**Launcher:**Minecraft Launcher

**What's the bug:** 
When I use sodium along side inertia and join servers it pops up with saving world and the game just crashes
**Crash-report(if applicable)(located in .minecraft/latest.log):**
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 23/07/21 17:31
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_757.method_3188(class_757.java:705)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_3188(class_757.java:705)

-- Affected level --
Details:
	All players: 5 total; [class_745['pespfat'/0, l='ClientLevel', x=-41.50, y=51.00, z=-15.50], class_745['demon_13263'/2307, l='ClientLevel', x=-33.56, y=50.06, z=-1.56], class_745['a'/10, l='ClientLevel', x=-45.50, y=50.00, z=-11.50], class_745['aa'/6, l='ClientLevel', x=-21.50, y=50.00, z=-11.50], class_745['autist_'/14, l='ClientLevel', x=-25.50, y=51.00, z=-15.50]]
	Chunk stats: SodiumChunkCache: 81
	Level dimension: minecraft:overworld
	Level spawn location: World: (-34,50,-2), Chunk: (at 14,3,14 in -3,-1; contains blocks -48,0,-16 to -33,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 94702014 game time, 4000 day time
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1136920176 bytes (1084 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		baritone: Baritone 1.6.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.3
		fabric: Fabric API 0.37.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+6aebe11a7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f3e8589e7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+5f6b94517d
		fabricloader: Fabric Loader 0.11.6
		fpsdisplay: FPS-Display 1.4.1+1.16.4
		hydrogen: Hydrogen 0.2
		inertia: Inertia Client 1.16.5
		java: Java HotSpot(TM) 64-Bit Server VM 8
		lithium: Lithium 0.6.6
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.0.1
		modmenu: Mod Menu 1.16.10
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.1.0
	Launched Version: fabric-loader-0.11.6-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) R4 Graphics GL version 4.5.14009 Compatibility Profile Context 21.19.144.257, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (United Kingdom)
	CPU: 4x AMD A6-7310 APU with AMD Radeon R4 Graphics 
**Final checklist:**
- [x] I know how to properly use check boxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by feliscatusmeows** [comment]
remove smoothboot, use https://www.curseforge.com/minecraft/mc-mods/lazydfu instead

**Comment by Azexxx** [comment]
> remove smoothboot, use https://www.curseforge.com/minecraft/mc-mods/lazydfu instead
tried but still crashes

**Comment by feliscatusmeows** [comment]
remove hydrogen, it is cursed and should not be used with other mods

**Comment by Azexxx** [comment]
> remove hydrogen, it is cursed and should not be used with other mods
nope still crashes when joining servers.i dont think its any of the other mods.i think its just an issue between inertia and sodium as when i remove sodium it works completely fine but i need it

**Comment by feliscatusmeows** [comment]
wait a second

>- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium.

why did you check that box?

**Comment by Azexxx** [comment]
> wait a second
> 
> > * [x]  I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium.
> 
> why did you check that box?

i did try to check after removing other mods but the thing is i need sodium to play inertia as in my fps dies when i dont have it

**Comment by feliscatusmeows** [comment]
try using only inertia and sodium, then slowly add in other mods

**Comment by Azexxx** [comment]
> try using only inertia and sodium, then slowly add in other mods

when i launch inertia and sodium the game doesnt even open lmao so defo something to do with sodium and inertia

**Comment by AutistEren** [comment]
> > try using only inertia and sodium, then slowly add in other mods
> 
> when i launch inertia and sodium the game doesnt even open lmao so defo something to do with sodium and inertia

you cant open game without baritone in mods folder if you use custom baritone

**Comment by Azexxx** [comment]
> > > try using only inertia and sodium, then slowly add in other mods
> > 
> > 
> > when i launch inertia and sodium the game doesnt even open lmao so defo something to do with sodium and inertia
> 
> you cant open game without baritone in mods folder if you use custom baritone

oh forgot i needed custom baritone in folder thanks autisteren

**Comment by Azexxx** [comment]
same result;join a server and crashes

**Comment by Paralusion** [comment]
Remove all mods and create a new issue, we can't help with this
