### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Raz221** [THEREALWWEFAN231/Inertia#1255]
**Minecraft Version(s)**
1.12.2 Forge
**What is the suggestion**
Everytime that lightning strike you can see the coords where the lightning struck
**Why would this feature be useful**
base hunting
**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] This is not a suggestion for baritone or other mod

**Comment by Paralusion** [comment]
sure, this was possible 5 years ago.. not now

**Comment by feliscatusmeows** [comment]
patched on many servers, ncp patches this afaik
