### ISSUE TITLE
forge support 

### ISSUE THREAD

**Issue by crumb9001** [THEREALWWEFAN231/Inertia#1264]
**Minecraft Version(s)**
1.16.5,1.15.2,1.14.4
**What is the suggestion**
add inertia to forge in the newer versions
**Why would this feature be useful**
you could join forge servers that are hosted by your friends/you could join forge servers with inertia
**Final checklist:**
forge support so i dont have to use impact
- [no] I know how to properly use check boxes 
- [yes] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
Pretty sure impact doesn't support forge past 1.12 either, just use fabric or forgehax

**Comment by crumb9001** [comment]
> Pretty sure impact doesn't support forge past 1.12 either, just use fabric or forgehax

impact does support forge, also what the fuck is forgehax

**Comment by feliscatusmeows** [comment]
I remember impact only supporting forge 1.12, wierd. Also forgehax is a forge hacked client

**Comment by crumb9001** [comment]
yeah well impact supports forge for 1.16.5 also

**Comment by Godeps2891** [comment]
![image](https://user-images.githubusercontent.com/54289108/128764576-657b56f0-0ced-49b5-bc9a-47f0844aadda.png)
ah yes

**Comment by crumb9001** [comment]
> ![image](https://user-images.githubusercontent.com/54289108/128764576-657b56f0-0ced-49b5-bc9a-47f0844aadda.png)
> ah yes

cool, i have 1.16.5 forge tho

**Comment by ENDER1355** [comment]
> Pretty sure impact doesn't support forge past 1.12 either, just use fabric or forgehax

Forge is dying on past 1.12.2, now everyone sticked into Fabric instead of MCP or forge

**Comment by crumb9001** [comment]
> > Pretty sure impact doesn't support forge past 1.12 either, just use fabric or forgehax
> 
> Forge is dying on past 1.12.2, now everyone sticked into Fabric instead of MCP or Forge.

forge isnt dying, for mods atleast

**Comment by ENDER1355** [comment]
> > > Pretty sure impact doesn't support forge past 1.12 either, just use fabric or forgehax
> > 
> > 
> > Forge is dying on past 1.12.2, now everyone sticked into Fabric instead of MCP or Forge.
> 
> forge isnt dying, for mods atleast

that's what i meant actually

**Comment by feliscatusmeows** [comment]
Forge pretty dead since 1.13, they basically killed forge utility mods with a new policy in 1.13. Also it's bloated and slow af.

**Comment by ENDER1355** [comment]
> Forge pretty dead since 1.13, they basically killed forge utility mods with a new policy in 1.13. Also it's bloated and slow af.

Many Minecraft Clients on 1.13+ are on Fabric.

**Comment by feliscatusmeows** [comment]
You mean 1.14+, fabric just isn't used in 1.13 at all.

**Comment by ENDER1355** [comment]
> You mean 1.14+, fabric just isn't used in 1.13 at all.

oh yeah

**Comment by crumb9001** [comment]
feline cat
also wow they added 1.12.2 cool

**Comment by GaiaB0t** [comment]
yea...?

**Comment by crumb9001** [comment]
remember thta time it wasnt there
