### ISSUE TITLE
Chams Ignores Friends

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#1272]
**Inertia Utility Mod version:** Latest prebuild
**Minecraft version:**  1.16.5
**Optifine/Other mods:**  No

**Final checklist:**
- [x] I know how to properly use check boxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by feliscatusmeows** [comment]
omg u duped #1210 no duping allowed

**Comment by AutistEren** [comment]
wtef
