### ISSUE TITLE
[BUG] huge performance impact also a rat

### ISSUE THREAD

**Issue by PiotrekUnityDeveloper** [THEREALWWEFAN231/Inertia#1274]
**Inertia Utility Mod version:** 313
**Minecraft version:** Yes
**Operating system:** Win10
**Optifine/Other mods:** No
**Launcher:** Crystal

**What's the bug:** 
Inerta mod makes my pc mine bitcoin and slowdown and it's now rats nest

**Crash-report(if applicable)(located in .minecraft/latest.log):**
slowdown

**Final checklist:**
- [x] I now know that Inertia mod is ratted
- [x] I have attemped to reproduce this bug using the latest available release of Inertia realsed a decade ago
[https://www.minecraft.net/en-us/terms/nintendo-switch](url)

i am now restarting my pc to the latest backup point i had.
dont download

**Comment by feliscatusmeows** [comment]
Sorry, inertia automatically detects windows users and slows down their computers to encourage people to switch to Linux. Solution is to switch to Linux. Also the dev needs the monero to buy more banana pealing machines.

**Comment by feliscatusmeows** [comment]
Sorry, inertia automatically detects windows users and slows down their computers to encourage people to switch to Linux. Solution is to switch to Linux. Also the dev needs the monero to buy more banana pealing machines.

**Comment by PiotrekUnityDeveloper** [comment]
that makes sense thanks

**Comment by feliscatusmeows** [comment]
For an alternative client that's totally not a rat or a miner, install sigma client.

**Comment by Realswitzer** [comment]
inertacoin miner? finally they considered my suggestions

**Comment by feliscatusmeows** [comment]
No not inertiacoins, it mines monero.

**Comment by feliscatusmeows** [comment]
Closed for non-issue. Who doesn't want a monero miner and rat on their computer?
