### ISSUE TITLE
Thealtening's free gen is even worse, alts can't be renewed and expire after 15 mins, at that point just buy nfas

### ISSUE THREAD

**Issue by Torono909** [THEREALWWEFAN231/Inertia#1278]
Thealtening's free gen is even worse, alts can't be renewed and expire after 15 mins, at that point just buy nfas

_Originally posted by @feliscatusmeows in https://github.com/THEREALWWEFAN231/Inertia/issues/1234#issuecomment-869926655_

1. nativesine60@gmail.com:pegliese2002

**Comment by feliscatusmeows** [comment]
Wjat
