### ISSUE TITLE
NoRender doesn't work with lights

### ISSUE THREAD

**Issue by Discusser** [THEREALWWEFAN231/Inertia#13]
**WWE version:** 
2.7 -> 2.7.2
**Minecraft version:** 
1.12.2
**Operating system:** 
Win10 Home
**Optifine/Other mods:** 
```
clientcommand
EMC
EtikaHack
LunatriusCore
Optifine
Schematica
WWE
WorldEdit
```
**Whats the issue:** 
When making FPS laggers (machines that use a lot of light to crash your mc), you would want to turn on no render so that you don't crash yourself, but even with norender on it doesnt work and you crash
**Crash-report(Would be very useful also please format):**

**Comment by Paralusion** [comment]
If you're talking about skylight, there's nothing you can do about them. Test it with any other client, anti-skylight lag won't work.

**Comment by Paralusion** [comment]
this can be closed as this is not a issue that can be resolved at the moment
