### ISSUE TITLE
Minecraft crashed after joining a server

### ISSUE THREAD

**Issue by ll11l1lIllIl1lll** [THEREALWWEFAN231/Inertia#1308]
**Inertia Utility Mod version:** Inertia Client 3.1.3 - 1.12.2
**Minecraft version:** Minecraft 1.12.2
**Operating system:** Windows 10 1909
**Optifine/Other mods:** forge 14.23.5.2768
**Launcher:** HMCL (Hello Minecraft! Launcher)

**What's the bug:** Minecraft crashed after joining a server

**Crash-report(if applicable)(located in .minecraft/latest.log):**
[latest.log](https://github.com/THEREALWWEFAN231/Inertia/files/8037247/latest.log)

**Final checklist:**
- [x] I know how to properly use check boxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by 0x3C50** [comment]
Seems like baritone trying to access a field which is private or protected in Vec3i. You can try disabling baritone in the launch parameters by adding `-Ddisablebaritone=true`

**Comment by THEREALWWEFAN231** [comment]
> Seems like baritone trying to access a field which is private or protected in Vec3i. You can try disabling baritone in the launch parameters by adding `-Ddisablebaritone=true`

Also removing -noverify works as well, actually fixes the issue
