### ISSUE TITLE
Color Signs: Debug Mode

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#131]
**What is the suggestion**
"Debug" option for Colored Signs, where it'll write a sign with all color codes, in their appropriate colors.
**Why it will be useful**
This could be used for testing to see if colors work in the server, as well as reminding the player what colors there are and the codes.

**Comment by Paralusion** [comment]
useless, you can just test it manually, all servers use the same color codes + its patched in vanilla servers

**Comment by Paralusion** [comment]
still useless 2 years later!
