### ISSUE TITLE
Black Screen Bug

### ISSUE THREAD

**Issue by SirGokalp** [THEREALWWEFAN231/Inertia#1313]
**Inertia Utility Mod version:** 
3.1.3
**Minecraft version:** 
1.12.2
**Operating system:** 
Windows 10
**Optifine/Other mods:** 
none
**Launcher:**
tlauncher
**What's the bug:** 
black screen
**Crash-report(if applicable)(located in .minecraft/latest.log):**
none
**Final checklist:**
- [x] I know how to properly use check boxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Realswitzer** [comment]
1. dont use tlauncher - use normal launcher or multimc (or a fork)
2. use new version and viaversion back

> Its happening with me too

doesnt help with anything, especially since this is a known bug
![image](https://user-images.githubusercontent.com/39711351/160196027-2196f948-fd75-4ea8-acf9-ddc5870ec0a5.png)

**Comment by THEREALWWEFAN231** [comment]
It's a  problem with inertia and your gpu drivers, nothing really you can do about it, just have to wait till 3.2.
