### ISSUE TITLE
Make position of HUD elements as customizable as ClickGUI

### ISSUE THREAD

**Issue by DanielFA88** [THEREALWWEFAN231/Inertia#1319]
All Minecraft versions

I suggest to make position of HUD elements as customizable as ClickGUI. That is possible on Pyro (in fact is the only thing I liked from that shitty paid client) and Inertia would feel almost perfect with this feature...

This would be useful because you could arrange the HUD as you like! In some servers there are fixed HUD elements that overlap with Inertia's fixed HUD elements and it's a total mess...

**Final checklist:**

- [x ] I know how to properly use check boxes 
- [x ] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
Implemented in prebuilds

**Comment by DanielFA88** [comment]
Nice to hear that! 👍
