### ISSUE TITLE
Key Repeat always enabled

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#133]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.3
**Operating system:** W10
**Optifine/Other mods:** None

**Whats the issue:** 
KeyRepeat always seems to be enabled. Even when disabled, I can hold Q in my inventory to spam-drop items.

**Comment by Paralusion** [comment]
this was added by Minecraft itself
