### ISSUE TITLE
Off Hand not working

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#137]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.3
**Operating system:** W10
**Optifine/Other mods:** None

**Whats the issue:** 
Doesn't seem to work in 1.14.3. Or it just doesn't do anything. Tested by asking a friend if I was doing *anything*.

**Comment by Paralusion** [comment]
works fine in latest version
