### ISSUE TITLE
XCarry: Mouse Item

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#140]
**Minecraft Version**

**What is the suggestion**
Use the mouse as an extra slot to carry a fifth item.
**Why it will be useful**
Keeps you from dropping items, as well as holding a 5th item.

**Comment by feliscatusmeows** [comment]
wait is this possible?

**Comment by Godeps2891** [comment]
i tested on the latest prebuild, it is possible but glitchy
