### ISSUE TITLE
Phase Hack

### ISSUE THREAD

**Issue by Discusser** [THEREALWWEFAN231/Inertia#15]
**Minecraft Version**
every
**What is the suggestion**
Basically BoatPhase, but without the sand and the boat.
**Why it will be useful**
Allows you to go through blocks when in godmode, basically allowing truly free travel.
When combined with godmode, it acts as freecam but you can break blocks n stuff

**Comment by IAmWolfie** [comment]
Yes pls

**Comment by Paralusion** [comment]
Great suggestions, but this wont and can't work in godmode due to several reasons. Listing the obvious one: the entity would get stuck.

**Comment by GaiaB0t** [comment]
not possible to do
