### ISSUE TITLE
Bow Aimbot & Trajectories doesn't account for water/lava

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#150]
**Whats the issue:** 
Bow Aimbot & Trajectories doesn't account for water or lava, making them both miss

**Comment by scarifyFX** [comment]
i feel like this would be hard to implement

**Comment by SylveonBottle** [comment]
> i feel like this would be hard to implement

It's already been done with old clients like Huzuni and such. It's really simple math, actually. Just adjust the angle when inside water/lava
Also, wow, this client still exists?

**Comment by Paralusion** [comment]
merged with #548
