### ISSUE TITLE
"Inventory See"

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#152]
he suggestion**
Add a recorded history of all items held in the user's hand, including enchant. Put it under player nametags, and in Combat Info.
**Why it will be useful**
You can see what sword they have, items in their hotbar, how many items in a stack, etc. This was in Flare and it was pretty legit

**Comment by Paralusion** [comment]
seems like an insane feature, would love this

**Comment by Paralusion** [comment]
better documented in #1070
