### ISSUE TITLE
Auto Eat: Interrupt

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#155]
**Minecraft Version**

**What is the suggestion**
Remove "Eating" option from Crystal Aura, add to Auto Eat in the form of "Interrupt". When disabled, auto eat will wait until other movement modules are done (i.e. when killaura is done attacking, when blink is disabled, etc) - when enabled, it'll just eat regardless of everything else.
**Why it will be useful**
Cleans clutter, makes it usable on other modules.

**Comment by Paralusion** [comment]
eh no, i dont think you understand what the functionality does, crystal aura automatically places the crystals. the eating option makes it so you can eat and place at the same time
