### ISSUE TITLE
Chat Bot (Clean Clutter)

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#160]
**What is the suggestion**
Put Announcer, Insulter, JoinLeaveMsgs, Spammer, Fancy Chat+, Infinite Chat Lenght, etc as a sub-option of ChatBot. Add a Toggle to enable/disable the original chatbot functionality. 

Rename "Mode :" to "Detect :" to clear confusion

**Why it will be useful**
This would literally clean up so much clutter in the GUI and make things easier to find

**Comment by Paralusion** [comment]
yes

**Comment by Paralusion** [comment]
done in latest update
