### ISSUE TITLE
Elytra Replace: "Auto"

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#171]
**Minecraft Version**

**What is the suggestion**
Add option to only replace your armour with your elytra if you're falling >4 blocks. When you land, replace with your older armour.
**Why it will be useful**
I wanna use my diamond/iron armor, but still be cool enough to automatically equip elytra when falling. WWE could do this!

**Comment by Paralusion** [comment]
would not work due to desync on servers
