### ISSUE TITLE
Freecam: "Interaction"

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#174]
**Minecraft Version**

**What is the suggestion**
Make it so that you can interact with chests/buttons/levels/boats/etc through walls if right-clicked. 
**Why it will be useful**
Useful for going into boats, opening chests, etc through walls

**Comment by Paralusion** [comment]
Already possible.

**Comment by feliscatusmeows** [comment]
but reach checks still apply, along with other checks like line of sight from anticheat
