### ISSUE TITLE
SafeWalk: Allow movement downwards when purposely walking off edge

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#182]
**Minecraft Version**

**What is the suggestion**
Safe Walk: Add option to disable when walking off the edge of a block on the side that you're looking towards (so you don't fall off blocks when going backwards, but can still walk down hills)

Basically if the user is purposely looking south, let them walk forward off the block south-wise
**Why it will be useful**
Lets you walk down mountains.

**Comment by Paralusion** [comment]
Useless, safewalk is not made for that.
