### ISSUE TITLE
Sprint: "KeepSprint"

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#186]
**Minecraft Version**

**What is the suggestion**
Add "KeepSprint" option. When disabled, stop sprinting immediately after hitting an entity (vanilla feature), then re-sprint. 
**Why it will be useful**
This lets it bypass anticheat that can detect sprinting during attacking, like Hypixel

**Comment by Paralusion** [comment]
No anticheats can detect sprinting while attacking, so basically, useless.

**Comment by SylveonBottle** [comment]
Hypixel, badlion, etc can detect keepsprint.
Check Vape Forums for discussions of them figuring out that KeepSprint was the reason why they were being detected

**Comment by Paralusion** [comment]
they can not, sorry mate

**Comment by SylveonBottle** [comment]
> they can not, sorry mate

Okay damn I guess I'm wrong then 🤷 if you say so
