### ISSUE TITLE
GUI panel rewrite

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#194]
**Minecraft Version**

**What is the suggestion**
Rename GUI to "Hud"
Move Color List (rename to Rainbow), Hud, F3 Spoofer, and Custom Font to the new "Hud"
Move all previous "Hud" sub-motiles to the new Hud
**Why it will be useful**
Cleans up a bunch of clutter. So far the "Gui" section is literally only for the clickgui colors, but there's so much else that can be used.
I don't understand why I have to actively search for Custom Font when it should be something that technically changes the gui, therefore should be under gui.

**Comment by Paralusion** [comment]
"Rename GUI to Hud" Why? They're both separate things? No need to rename them.
I
