### ISSUE TITLE
Custom Font to effect rest of client

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#195]
**What is the suggestion**
Doesn't effect chat. Would be cool if it effected chat. Maybe even other places in the client, like item names, potion effect in inventory, etc
**Why it will be useful**
Honestly just pretty. Give me some Roboto in chat pls

**Comment by Paralusion** [comment]
Not good for a WWE feature. Not only would it bring up the loading screen (depending on the quality of the font) for much much much longer, a stand-alone mod would be way better for this. Use a mod such as "Smooth Font" instead.

**Comment by Paralusion** [comment]
use mod Smooth Font instead
