### ISSUE TITLE
Suggestion an Option for like a 100x better anti Hunger 

### ISSUE THREAD

**Issue by Nokkkk** [THEREALWWEFAN231/Inertia#256]
**Minecraft Version**
all
**What is the suggestion**
Anti hunger that basicly never goes down (still does just like once a night or somethin
**Why it will be useful**
for flying and using speed in survival cuz u just run out of food and die pretty much

**Comment by SylveonBottle** [comment]
While we're at it can we also have godmode? Like antihunger but for health that never goes down (do does just like once a night or something)

**Comment by Paralusion** [comment]
> While we're at it can we also have godmode? Like antihunger but for health that never goes down (do does just like once a night or something)

That'd be amazing. If it were possible. Explain to me, how would this be possible? Is there some secret packet I don't know about?

**Comment by SylveonBottle** [comment]
> > While we're at it can we also have godmode? Like antihunger but for health that never goes down (do does just like once a night or something)
> 
> That'd be amazing. If it were possible. Explain to me, how would this be possible? Is there some secret packet I don't know about?

Don't know I figured I'd i just suggested something and it would get added, like OP

(PS add forceop too)

(pss I really hope you understand I was joking to make fun of op's equally impossible suggestions)

**Comment by Paralusion** [comment]
> > > While we're at it can we also have godmode? Like antihunger but for health that never goes down (do does just like once a night or something)
> > 
> > 
> > That'd be amazing. If it were possible. Explain to me, how would this be possible? Is there some secret packet I don't know about?
> 
> Don't know I figured I'd i just suggested something and it would get added, like OP
> 
> (PS add forceop too)
> 
> (pss I really hope you understand I was joking to make fun of op's equally impossible suggestions)

WWE's antihunger is really inefficient and could be made way better, so..

**Comment by Paralusion** [comment]
added and works in latest release
