### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Nhjb1** [THEREALWWEFAN231/Inertia#26]
1.14.2

More variants for speed hacks such as bhop, vanilla, float, lowhop, and etc (use impact as an example)

Having different types of speedhacks would make it easier to bypass anti-cheat systems.

**Comment by feliscatusmeows** [comment]
![image](https://user-images.githubusercontent.com/29553771/115123708-1eb27780-9f73-11eb-8e12-40422e61cae2.png)
![image](https://user-images.githubusercontent.com/29553771/115123720-2a05a300-9f73-11eb-946b-76144f1c3f42.png)
:sunglasses:

**Comment by AutistEren** [comment]
no lowhop 😔
