### ISSUE TITLE
Suggestion Breezily scaffold

### ISSUE THREAD

**Issue by Semichaotic** [THEREALWWEFAN231/Inertia#275]
**Minecraft Version**
1.12.2 (preffered) But could be all

**What is the suggestion**
Having a scaffold that looks like "breezily bridging" 
**Why it will be useful**
It looks to server anti cheats and staff legit <3

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
This mod is only to be used on servers that allow it.

**Comment by AutistEren** [comment]
youre not supposed to use inertia on servers youre not allowed to

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
I think this issue was made when it was called ufc client or something lol.

**Comment by GaiaB0t** [comment]
WWE client

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
Pretty sure it's ufc client.

**Comment by GaiaB0t** [comment]
no, it was wwe client, hence wweclient.com

**Comment by GaiaB0t** [comment]
before the rename

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
![image](https://user-images.githubusercontent.com/29553771/96612138-42da1800-12b2-11eb-973c-86243acbed28.png)

**Comment by GaiaB0t** [comment]
it's a joke thing lol like "removed herobrine"

**Comment by GaiaB0t** [comment]
if you're in the discord look in #announcements

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
nope it's ufc client

**Comment by GaiaB0t** [comment]
bruh

**Comment by Paralusion** [comment]
not gonna happen
