### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by codermen1337** [THEREALWWEFAN231/Inertia#292]
**Minecraft Version**
1.14.3
**What is the suggestion**
Ghost Mode and being able to change the WWE command prefix to something custom
**Why it will be useful**
Pretty obvious why it would be.

**Comment by THEREALWWEFAN231** [comment]
.preset newprefix
.prefix #

**Comment by codermen1337** [comment]
Didn't know that, thanks, but please add a ghost mode, it would be cool!

**Comment by Paralusion** [comment]
does not specify what a "ghost mode" is
