### ISSUE TITLE
[Suggestion] Better Trajectories/Projectiles

### ISSUE THREAD

**Issue by Vonr** [THEREALWWEFAN231/Inertia#299]
**Minecraft Version**
yes

**What is the suggestion**
Make the box at the end of the trajectory translucent, a simple X, or a 2D translucent circle. Also, maybe change the colour when the trajectory is projected to hit an entity

**Why it will be useful**
Visuals are important in marksmanship.

**Comment by Paralusion** [comment]
merged with #548
