### ISSUE TITLE
Commitly Builds 🌙

### ISSUE THREAD

**Issue by ghost** [THEREALWWEFAN231/Inertia#31]
**Minecraft Version**
ALL

**What is the suggestion**
Make a Gradle task which automatically compiles and obfuscates the client every commit, and uploads the build to a private repository which only donators have access to.

**Why it will be useful**
Motivates people to donate to WWE, also lets people experience bleeding edge features!

**Comment by IAmWolfie** [comment]
yes this sounds amazing

**Comment by feliscatusmeows** [comment]
Added before I even heard of this client lol. Can now buy prebuilds for 20 dollars.
