### ISSUE TITLE
Suggestion Anti Afk

### ISSUE THREAD

**Issue by GenerousJack** [THEREALWWEFAN231/Inertia#311]
**Minecraft Version**
1.12.2
**What is the suggestion**
Add anti afk that works like the anti afk on future client
**Why it will be useful**
The client doesnt even have an anti afk feature plus it would be extremly useful on 2b2t because the anti afk plugin is very demanding of you

**Comment by THEREALWWEFAN231** [comment]
I dont know how it is on future, how is it on future?

**Comment by GenerousJack** [comment]
so from what i got out of a guy that has future (both of us are using it for 2b2t) it needs to move around,jump and interact with any type of blocks e.g. chests (and get out of the chest),maybe press levers or buttons so 2b2t doesnt kick you

**Comment by rushercrack** [comment]
https://i.imgur.com/sice0Jq.png
these are all the options
