### ISSUE TITLE
Let us add entities to Search

### ISSUE THREAD

**Issue by codingsocks** [THEREALWWEFAN231/Inertia#32]
**Minecraft Version**
All

**What is the suggestion**
Let us add entities to Search

**Why it will be useful**
Sometimes I'm running around trying to find cows and chickens and letting me add them to the Search feature to have a tracer drawn to them would make it a lot easier to find them.

**Comment by 2b2tQueueProject** [comment]
Close this issue, entity search is called ESP.

**Comment by IAmWolfie** [comment]
> Close this issue, entity search is called ESP.

Yeah, but that doesn't draw a tracer to individual entities. I want to pick out a specific entity like a Cow or a Chicken.

**Comment by Paralusion** [comment]
A more appropriate thing that could be added are more options to the Tracer/ESP module.

**Comment by IAmWolfie** [comment]
> A more appropriate thing that could be added are more options to the Tracer/ESP module.

Yes, but I think there should be the ability to select mobs in specific, but having that many entities as options in the menu would clutter it quite up.

**Comment by Paralusion** [comment]
merged with #27
