### ISSUE TITLE
[Suggestion] Chat filter

### ISSUE THREAD

**Issue by Vonr** [THEREALWWEFAN231/Inertia#35]
**Minecraft Version**
Yes

**What is the suggestion**
Make a Chat Filter that clientsidedly deletes chat messages that contain strings of a line in a settings file.

Example:
**File:**
`connect to`
**Message:**
`If you want to play minigames, _connect to_ 2.2.2.2:25565!`
That message will be deleted

**Why it will be useful**
Can be used to filter out spam messages

**Comment by Paralusion** [comment]
Something that can also get added with this to prevent spam, if a message gets said two times, it'd put the message like this and remove the previous ones: "Spam message (x2)"

**Comment by Paralusion** [comment]
ChatFilter has been added
