### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 200ms** [THEREALWWEFAN231/Inertia#354]
**Minecraft Version**
Version =>1.22.2

**What is the suggestion**
Autoplace 
Also in the inventory or the pause menu (because of reconnects)
Can be combined with Fastplace

**Why it will be useful**
At many farms like fish farms or mob farms you have to hold the right mouse button all the time. This would make it much easier.

**Comment by THEREALWWEFAN231** [comment]
This doesn't make sense whats your suggestion?

**Comment by feliscatusmeows** [comment]
Probably an input holder
