### ISSUE TITLE
Cant use Baritone with freecam

### ISSUE THREAD

**Issue by 200ms** [THEREALWWEFAN231/Inertia#355]
**WWE version:** 
2.7.2
**Minecraft version:** 
1.12.2
**Operating system:** 
Windows 10
**Optifine/Other mods:** 
Optifine
BoundingBoxOutlineReloaded
In-Game Account Switcher
Light Level Overlay Reoaded
Schematica
Xaero's Minimap
**Whats the issue:** 
Cant use the baritone features with the freecam.
It's always just joking around and the Freecam player gets moved, not the right one.

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
This is more of an enhancement, im not sure if it will be added. 🤷‍♀

**Comment by scarifyFX** [comment]
thats a bug from baritone but it could become an enhancement, pls close this.

**Comment by Paralusion** [comment]
"fixed" in prebuilds
