### ISSUE TITLE
建议添加.tp指令和相应功能

### ISSUE THREAD

**Issue by minecraft-pig** [THEREALWWEFAN231/Inertia#357]
**Minecraft Version**

**What is the suggestion**

**Why it will be useful**

**Comment by BleachDrinker420** [comment]
ah yes, ching chong bing bong indeed

**Comment by vungsung** [comment]
lol Bleach
Pls allow me to reply in Chinese, since OP looks not going to deal with any English except t and p.

@minecraft-pig 请参考`.help`的说明，使用`.clip v 格数`进行上下传送，`.clip h 格数`进行前後传送。

**Comment by Paralusion** [comment]
thank you for your great suggestion, but after two years of constant discussing, we've decided to decline this suggestion
