### ISSUE TITLE
Suggestion bindable chat/commands

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/Inertia#380]
**Minecraft Version**
all
**What is the suggestion**
.bind A .value ESP chest on
**Why it will be useful**
Allows me to use player esp & have chest ESP toggleable

**Comment by THEREALWWEFAN231** [comment]
as said yesterday already have this planed but it will be more like this,
(.bind A) (.value ESP chest on)
Ill close this once its added....

**Comment by Paralusion** [comment]
yea, just added it to Github, so you wouldnt forget
