### ISSUE TITLE
Weapon toggle for auto tool

### ISSUE THREAD

**Issue by Zernaie** [THEREALWWEFAN231/Inertia#385]
**Minecraft Version**
all
**What is the suggestion**
add a toggle for auto tool 
**Why it will be useful**
if your using auto tool and you are using your pickaxe axe and shovel with it then its fine but if you 
try to killaura it will switch to your axe instead of sword which is annoying and I dont feel like
toggling off auto tool every time I try to killaura or hit a mob

**Comment by THEREALWWEFAN231** [comment]
Well a axe is stronger then a sword...

**Comment by Zernaie** [comment]
ye but it takes longer to charge and its just annoying having it switch to axe

**Comment by Paralusion** [comment]
axe is stronger than a sword!
