### ISSUE TITLE
Smart totem 

### ISSUE THREAD

**Issue by Zernaie** [THEREALWWEFAN231/Inertia#389]
**Minecraft Version**
all
**What is the suggestion**
have a mode for totems where it only switches when your about to die
**Why it will be useful**
mainly pvp, alot of clients have it and I feel at a disadvantage in crystal pvp when the enemies are chugging gaps while I hit them then switching to totem as soon as they are about to die.

**Comment by Paralusion** [comment]
its called autototem..

**Comment by THEREALWWEFAN231** [comment]
I guess although its bad for auto crystal but i guess for sword pbp

**Comment by Paralusion** [comment]
duplicate of.. some issue
