### ISSUE TITLE
outline ESP drastically reduces FPS

### ISSUE THREAD

**Issue by LastExceed** [THEREALWWEFAN231/Inertia#402]
WWE 3.0.2
Minecraft 1.12.2
Windows 10

with outline ESP enabled and lots of entities around my FPS can drop below 20, while with other settings (2D, box, box outline, or no ESP at all) i can get up to 100 fps (150 when using optifine and vanilla-fixes ect)

**Comment by Paralusion** [comment]
Outline ESP is a Minecraft function, like, when you hit someone with a particular arrow, he gets the outline. It's Minecrafts fault for not optimising that code properly. If WWE wants to 'fix' it, he'd need to go out of his way and recreate a whole new outline ESP. If you really want him to do that, donate to him to show support.

**Comment by LastExceed** [comment]
the outline ESP in impact client isnt nearly as bad though, does that mean they actually reimplemented it?

**Comment by Paralusion** [comment]
probably

**Comment by Paralusion** [comment]
gave reasoning above
