### ISSUE TITLE
1.15 bugs/issues

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [THEREALWWEFAN231/Inertia#403]
F3 spoofer
Chat Mentation
Rainbow enchant
Nametags(font render) & item lighting
IRC

**Comment by fuckmymom771** [comment]
Also outlined ESP looks wrong.

**Comment by THEREALWWEFAN231** [comment]
Send screen shot

**Comment by fuckmymom771** [comment]
![2019-12-10_20 09 43](https://user-images.githubusercontent.com/58495022/70565049-33b21600-1b89-11ea-8742-73fb9c61c601.png)
![2019-12-10_20 11 52](https://user-images.githubusercontent.com/58495022/70565118-5d6b3d00-1b89-11ea-8e3e-7c0e5e58edec.png)

**Comment by THEREALWWEFAN231** [comment]
What modules did you have on, that did not happen for me

**Comment by fuckmymom771** [comment]
No modules, no mods. Problem remains for clean install.

Switching from Windows 7 to Ubuntu "solved" the problem. Must be OS-related. A little bit weird because 1.14 version works just fine on Windows.

**Comment by THEREALWWEFAN231** [comment]
Does minecrafts "glow arrow" "esp" work?

**Comment by fuckmymom771** [comment]
Yeah
![2019-12-11_02 02 04](https://user-images.githubusercontent.com/58495022/70584830-3ed16a00-1bba-11ea-9da6-c62069b40590.png)

**Comment by Godeps2891** [comment]
👍
