### ISSUE TITLE
Bug: AutoEat conflicts with Baritone

### ISSUE THREAD

**Issue by 6thPurge** [THEREALWWEFAN231/Inertia#406]
**WWE version:** 
3.0.2
**Minecraft version:** 
1.12.2
**Whats the issue:** 
When Baritone is mining and AutoEat is enabled, it will conflict itself. As soon as AutoEat wants to eat the Player gets stuck continuessly switching between the mining tool and food.

I would really like to see an AutoEat option, to force it waiting for other modules to finish, or pause the modules to eat.

**Comment by Paralusion** [comment]
suggest this to baritone instead
