### ISSUE TITLE
something like a schematic printer

### ISSUE THREAD

**Issue by FredTheFriendlyFox** [THEREALWWEFAN231/Inertia#407]
**Minecraft Version**
1.15*
**What is the suggestion**
SO I WAS THINKING MAYBE MAKE something like schematica yano print, save and load schematics.  
**Why it will be useful**
having something that can save your work from one world and put on to a server to show off your builds would be awsome.makes it so it wont take another 3 hours recreating the same build maybe you make something in single creative world then you wanna build it in a survival woorld on a server or realm

**Comment by Paralusion** [comment]
just install schemetica? ...

**Comment by FredTheFriendlyFox** [comment]
> just install schemetica? ...

i wish its was possible in 1.15. it hasnt been a thing since 1.12, people said the person will update now minecraft is on 1.15 because it is more stable but i dont think it will but who knows
+its just a suggestion in case they think hmm thats actually an idea

**Comment by Paralusion** [comment]
use baritone
