### ISSUE TITLE
Suggestion - FOV for Aim Assist

### ISSUE THREAD

**Issue by BoxFullOfInk** [THEREALWWEFAN231/Inertia#420]
**Minecraft Version**
1.15.x
**What is the suggestion**
Add an fov slider to the Aim Assist when it's on Legit mode so it doesn't turn towards players that are directly behind the player/out of a certain fov.
**Why it will be useful**
It'll make legit mode look more legit.

**Comment by aesafdasfda** [comment]
stop being poor and get Vape or drip if you want good legit crap

**Comment by THEREALWWEFAN231** [comment]
> VAPE FOR 1.15 DRIP FOR 1.15 bruh we got some competition

**Comment by Paralusion** [comment]
duplicate of #53
