### ISSUE TITLE
Screen died - BUG

### ISSUE THREAD

**Issue by pErus88** [THEREALWWEFAN231/Inertia#426]
**WWE version: 3.0.2** 
**Minecraft version: 1.12.2** 
**Optifine/Other mods: Optifine, Malibib and Schematica** 

**Whats the issue: I went thru a nether portal and when I was in the portal my screen started going crazy.** 
![image](https://user-images.githubusercontent.com/53449219/71583409-036def80-2b17-11ea-9fd2-ae544ee126fe.png)

**Comment by pErus88** [comment]
Far as I can remember I had: **NoRender(only fire)**, FastBreak, **BlockESP(ESP  only);shulkers and nether portals)**, Sprint, AutoRespawn, Criticals, **AntiWeather**, Name Tags, **HUD(with basic things)**,

**Comment by THEREALWWEFAN231** [comment]
The only render modules that are glitchy in wwe are Way Points and sometimes outline modes of esp, so if you dont have thoses on i assume its Schematica

**Comment by pErus88** [comment]
Oh I think that I had ESP with chests on or smthing, but maybe schematica too

**Comment by Paralusion** [comment]
probably fixed now
