### ISSUE TITLE
Chest ESp still shows after chest has been broken Bug

### ISSUE THREAD

**Issue by ShabanPlayz** [THEREALWWEFAN231/Inertia#43]
WWE Version: 2.7.2
Minecraft Version: 1.13.2
Issue: Chest ESP still shows the ESP after a Chest has been broken.

**Comment by THEREALWWEFAN231** [comment]
I have seen that before, only in the 1.13 version, I'm not sure why it happens, I haven't really been able to replicate it either.

**Comment by Vonr** [comment]
check every esp location every tick to fix... and make game lag

**Comment by THEREALWWEFAN231** [comment]
> check every esp location every tick to fix... and make game lag

Thats actually whats happening right now, it checks every tick

**Comment by Paralusion** [comment]
was not able to replicate in newest version
