### ISSUE TITLE
Esp Bug

### ISSUE THREAD

**Issue by seattlediamonds** [THEREALWWEFAN231/Inertia#435]
**WWE version:** 3.0.4
**Minecraft version:** 1.15.1
**Operating system:** Imac
**Optifine/Other mods:** litematica

**Whats the issue:** When i enable esp it takes up 3/4 of my screen and i cant see anything so i have to toggle it off in chat then restart Minecraft.

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Try removing litematica, someone else said they had this and had no mods so yeah... ill look into it some time if thats the case. He also said he had to make in windowed then back to full screen instead of restarting

**Comment by Paralusion** [comment]
probably fixed now
