### ISSUE TITLE
NAMETAG Bug

### ISSUE THREAD

**Issue by gordontsui24** [THEREALWWEFAN231/Inertia#442]
**WWE version:** 3.0.4
**Minecraft version:** 1.15.2
**Operating system:** window 10
**Optifine/Other mods:** none

**Whats the issue:** 
![2020-01-27_20 59 36](https://user-images.githubusercontent.com/60349040/73176936-a599eb00-4148-11ea-9e03-b07aa7a492b1.png)

![2020-01-27_21 00 35](https://user-images.githubusercontent.com/60349040/73176957-b185ad00-4148-11ea-91fb-d78db3a08812.png)

**Crash-report(Would be very useful also please format):**
when i close to players ,i am getting glitch out :/ 
and this case only happens in switch on the NAMETAG function [NAME TAGS] ----> [ITEM] ---->[Enchantments]

**Comment by Paralusion** [comment]
probably fixed now
