### ISSUE TITLE
1.15.2 Block ESP doesn't work

### ISSUE THREAD

**Issue by FoxieKitten** [THEREALWWEFAN231/Inertia#443]
Pretty much that, when I added blocks the esp or tracer doesn't work.   I did block esp list command and it shows they are there.   Oh and is there a way to add portals back like we had?

**Comment by THEREALWWEFAN231** [comment]
Yes that's how you would add portals, erm it should work though, try hitting f3 and a maybe 5 times, I did notice in 1.15 its a bit stupid, if that doesn't work send a screenshot of the stuff you have on

**Comment by FoxieKitten** [comment]
ok will do,  I tired refreshing the chunks few times nothing I add shows up on the block esp

**Comment by FoxieKitten** [comment]
![2020-02-10_09 32 38](https://user-images.githubusercontent.com/22878968/74154141-72e00000-4be8-11ea-8c8d-f99cca393e33.png)
![Uploading 2020-02-10_09.33.15.png…]()

**Comment by Paralusion** [comment]
what other mods?

**Comment by FoxieKitten** [comment]
![2020-02-10_09 36 55](https://user-images.githubusercontent.com/22878968/74154377-eaae2a80-4be8-11ea-9043-ac86798aa182.png)

I am running Voxel Mini map and Roughly Enough Items

**Comment by THEREALWWEFAN231** [comment]
Ok, so my question is does normal esp work on stuff, like chests, I know I need to recode block esp, it acts stupid in 1.15.x and i don't like the way it is, I'm just thinking of a better way.

**Comment by FoxieKitten** [comment]
those Chest ESP does work

**Comment by Paralusion** [comment]
probably fixed? if not create new issue
