### ISSUE TITLE
Suggestion: VR integration

### ISSUE THREAD

**Issue by DJcrafter13** [THEREALWWEFAN231/Inertia#446]
**Minecraft Version**
1.12.2 and 1.14
**What is the suggestion**
Vr integration with WWE
**Why it will be useful**
Since ForgeWurst is the only hacked client with VR, I thought it would be cool if WWE had it too. The only thing that would be different from the regular version is that the hack menu would pop up as a button in your inventory to press and then it would close your inventory and open the menu. Things like fly would allow you to fly by using the VR controller thumbstick and such.

**Comment by DJcrafter13** [comment]
Also, I can test it if you need me to.

**Comment by Paralusion** [comment]
i honestly do not think this will happen..
