### ISSUE TITLE
Suggestion add noclip/phase

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/Inertia#459]
**Minecraft Version**
all
**What is the suggestion**
noclip/phase
**Why it will be useful**

**Comment by cookiedragon234** [comment]
> Why it will be useful

**Comment by idqn** [comment]
to noclip/phase thru blocks..

**Comment by BlackL0L** [comment]
I think you can use freecam without packet cancel to do that

**Comment by idqn** [comment]
no it doesnt it just like blink

**Comment by RubyJet** [comment]
I would like to see this implemented
