### ISSUE TITLE
better elytra+ and hunger

### ISSUE THREAD

**Issue by zkkety** [THEREALWWEFAN231/Inertia#460]
1.12.2

elytra+ option that doesn't get rubberbanded as much like the elyta+ of impact or future. If possible better hunger for flight and elytra+ as hunger depletes extremely fast when using it

constantly getting rubberbanded when i use elytra+ and my hunger goes down fast.

**Comment by Paralusion** [comment]
you getting rubberbanded is either by the server not being able to keep up, or the anticheat doing so

**Comment by zkkety** [comment]
but the hunger depletion?

**Comment by Paralusion** [comment]
idk, it's not my decision what gets added into the client
