### ISSUE TITLE
Add keybinds to presets

### ISSUE THREAD

**Issue by 7orivorian** [THEREALWWEFAN231/Inertia#465]
**Minecraft Version**
Forge 1.12.2

**What is the suggestion**
I swap between presets a _frick_ ton & I've noticed that keybinds (plus some other info) doesn't save per preset.

**Why it will be useful**
Because it's a pain in the arse to change all my keybinds all the time XD

**Comment by TheRedHippo** [comment]
^ This would be really useful.  A way to utilise this would be being able to have presets for when you want to be super blatant, and when you only want a slight advantage. For example on your blatant preset you'd bind c to killaura, criticals, reach, etc. But on the slight advantage it'd only be triggerbot.

**Comment by THEREALWWEFAN231** [comment]
I'm going to close this, this is basically added in 3.1, macros were added in 3.1(which allows you to bind commands to keybinds) & a preset command was added which allows you to load a preset from a command, meaning with macros you can load presets with a keybind.
