### ISSUE TITLE
Lags

### ISSUE THREAD

**Issue by zyrafal** [THEREALWWEFAN231/Inertia#466]
**WWE version: 3.0.4** 
**Minecraft version: 1.15.2** 
**Operating system: Windows 10** 
**Optifine/Other mods: no** 

**Whats the issue: ** 
Game gets laggy after a long time of playing. a 1-2s lags every 10-15s

**Crash-report(Would be very useful also please format):**

**Comment by Paralusion** [comment]
ask the minecraft developers
