### ISSUE TITLE
Working Autosearch

### ISSUE THREAD

**Issue by bjcband** [THEREALWWEFAN231/Inertia#472]
Log locations where there are shulkers or chests (of a large amount) inside a file when the setting is on. Possibly, a setting to fly the player automatically, searching unchecked chunks in the area, saving the checked chunks to a file.

**Comment by THEREALWWEFAN231** [comment]
Already in prebuilds, you can buy it now for imidate access, it doesnt save the chunks, thats a good idea(ill keep this open for that), but theres a gui and everything, better than other "stash finders"

**Comment by Paralusion** [comment]
already in prebuilds
