### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Dogius** [THEREALWWEFAN231/Inertia#487]
**Minecraft Version**
Latest one
**What is the suggestion**
Add a spam button like in old wurst's versions for sending very long messages
And .give command for creative to get items with custom nbt tag instead of going to the world to get it and then put it on the tabs
**Why it will be useful**
It would be nice for creative users on public creative servers

**Comment by THEREALWWEFAN231** [comment]
I dont know what wursts spam button is like, but in Chat Bot, theres spammer option, you can edit the file to change the messages, and there an infinite chat length module which disables minecrafts chat scroll limit and chat box max length.
