### ISSUE TITLE
Suggestion have gui opened 

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/Inertia#491]
**Minecraft Version**
all
**What is the suggestion**
Have GUI opened on first start (after install)
**Why it will be useful**
Reduces confusion for people who aren't smart enough to try and right click..

**Comment by Paralusion** [comment]
with opened, I mean the menu's opened (like movement, player etc)

**Comment by THEREALWWEFAN231** [comment]
I was thinking of adding a tutorial type thing for it but not sure yet.

**Comment by Godeps2891** [comment]
tutorial type thing has been added
