### ISSUE TITLE
Creeper Safe -module

### ISSUE THREAD

**Issue by pErus88** [THEREALWWEFAN231/Inertia#492]
**Minecraft Version**
All
**What is the suggestion**
When creeper comes near your shield automatically blocks it OR when the creeper gets near you get noticed somehow, like a noise or you have a small transparent box and it gets less transparent and more red after a creeper comes near to you.
**Why it will be useful**
Its useful for hardcore minecraft servers or just vanilla servers and you don't want to die or want big holes in your buildings etc. You know creepers are very annoying.

**Comment by idqn** [comment]
if u ask me its a cool idea

**Comment by Paralusion** [comment]
duplicate of #116
