### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [THEREALWWEFAN231/Inertia#5]
**WWE version:** 2.6.1 beta
**Minecraft version:** 1.12.2 forge
**Operating system:** idk
**Optifine/Other mods:** quite a bit of mods

**Whats the issue:** Some crash in GuiInGameHook.renderTopMiddleObjects i need to fix, cant reproduce it though

**Crash-report(Would be very useful also please format):**
java.lang.NullPointerException: Unexpected error
	at wwe.Hear.NnXq(Unknown Source)//GuiInGameHook.renderTopMiddleObjects
	at wwe.Hear.aUGo(Unknown Source)

**Comment by RocketNinja15** [comment]
the first one uwu

**Comment by GaiaB0t** [comment]
bug for older version, I think fixed?
