### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Fuskiller** [THEREALWWEFAN231/Inertia#50]
**WWE version:** 2.6
**Minecraft version:** 1.12.2
**Operating system:** Windows 10
**Optifine/Other mods:** Optifine

**Whats the issue:** When I break crops like carrots and potatoes, the autotool mod changes my hand to either the axe or shovel in my hotbar.

**Crash-report(Would be very useful also please format):**

**Comment by Zernaie** [comment]
Not really a issue, it just switches to whatever minecraft thinks it uses, but it would be nice if Iknowimez made it so autotool didnt break foilage and others with swords and instead use hands
