### ISSUE TITLE
Suggestion: Baritone 1.15.2

### ISSUE THREAD

**Issue by Spekbillenn** [THEREALWWEFAN231/Inertia#501]
**Version:** 1.15.2
**Suggestion:** I would love to see Baritone in the 1.15.2 version of WWE
**Why:** Because baritone is the most advanced bot that can do a lot of useful things like automine.

**Comment by THEREALWWEFAN231** [comment]
This is already planned, its just wwe 1.15 released before baritone, so the next we update will have it.
