### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ggupleb** [THEREALWWEFAN231/Inertia#503]
**WWE version:**  3.0.3
**Minecraft version:** 1.15.2
**Operating system:** win 10
**Optifine/Other mods:** none

**Whats the issue:** path finder doesn't work properly new chunks don't show up

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Firstly, it works on some servers and not on other, secondly some people have told me it doesn't work in 1.13+, I have not tested that yet, when I do ill respond to this with my results.

**Comment by Godeps2891** [comment]
we have now concluded it does not work on 1.13+
