### ISSUE TITLE
Suggestion(some ideas i had)

### ISSUE THREAD

**Issue by a-a3458** [THEREALWWEFAN231/Inertia#504]
**Minecraft Version** 1.15.2

**What is the suggestion**
ping spoofer/UUID spoorfer,tp aura, murdery mystery revealer,crash block
**Why it will be useful**
have a ready to go excuse for speed. but the ping spoofer would need a fake lag optoin so it looks believeable and the UUID spoofer would be to bypass a ban. the tp aura just teleports you around your opoent so they cant hit you but you can hit them. the murdery mystery one could tell you who is the murder by havine the esp give them a red outline. crash block just gives you the crash anvil to crash a game.

**Comment by THEREALWWEFAN231** [comment]
Ping spoof, is already added, in 3.1(not released yet), UUID spoofer isn't possible, reach has a teleport option(its somewhat bad, will be improved sometime with a path finding algorithm so it works, once that happens there will also probably be a tp aura), a murder mystery isn't going to be added, just use nametags, idk about "crash anvil" I plan on eventually adding a just about 100% custom item generator for creative, in which you could create the "crash anvil". ill close this when that stuff is done.

**Comment by Paralusion** [comment]
pretty much all already suggested
