### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Unbatedivy79643** [THEREALWWEFAN231/Inertia#506]
**Minecraft Version** 1.15.2

**What is the suggestion** bassicly theres a bug when once in a while one of the touch gui things vanashs and it keeps on disaperaing until there is nothing so can you make so when u click esc when you press WWE options you can reset the layout not mods just layout

**Why it will be useful** You know why

**Comment by THEREALWWEFAN231** [comment]
Can you send a screen shot or a video.

**Comment by THEREALWWEFAN231** [comment]
Maybe try .guireset framename, so like .guireset Render
or to reset all .guireset all

**Comment by Unbatedivy79643** [comment]
WWE FAN thx u helped my issue

**Comment by Paralusion** [comment]
issue fixed
