### ISSUE TITLE
Suggestion [Wither Mute]

### ISSUE THREAD

**Issue by Hexiro** [THEREALWWEFAN231/Inertia#510]
**1.12.2**

**Mute withers  and/or hide bars for servers like 2b2t**

**1.12.2 is the version of anarchy servers and muting withers will be useful**

**Comment by THEREALWWEFAN231** [comment]
No render has a option for wither bars.

**Comment by Hexiro** [comment]
then just mute or maybe instead of just withers mute portals too

**Comment by Paralusion** [comment]
he means muting withers specifically
