### ISSUE TITLE
Suggestion add chat color in color manager

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/Inertia#517]
**Minecraft Version**
all
**What is the suggestion**
https://i.imgur.com/QyeyOxC.png
**Why it will be useful**
easier to see

**Comment by THEREALWWEFAN231** [comment]
Already had that in my todo list, but when its added, it's not going to be in the color manager, as you can only use the what 16 colors(I think), of course, I could make it more but I'm not going through that hassle.

**Comment by Paralusion** [comment]
added
