### ISSUE TITLE
Make Tracers customizeable

### ISSUE THREAD

**Issue by Zombaldag** [THEREALWWEFAN231/Inertia#519]
1.15.2

Make Tracers customizable, like with .tracer add (mob/animal/username) and  .tracer remove (mob/animal/username)

If you want to grind certain mobs and  they are not easily spottable (Example: Ghasts in nether, etc.) , or remove friends from being traced as you know where they are.

**Comment by scarifyFX** [comment]
love this idea, maybe even rainbow for players.

**Comment by Paralusion** [comment]
merged with #27
