### ISSUE TITLE
[Suggestion] DeathBurn

### ISSUE THREAD

**Issue by Vonr** [THEREALWWEFAN231/Inertia#52]
**Minecraft Version**
yes

**What is the suggestion**
A module that places a bucket of lava or ignites with a flint a steel the block under them either on death event or when they are at half a heart with no regen/hunger and there are enemies close to them
(players that have attacked them for the past minute)

**Why it will be useful**
Allows you to burn your items so that the enemy can not steal it.

**Comment by Paralusion** [comment]
I have no idea what you're trying to say.

**Comment by Vonr** [comment]
explained it to iknowimez already. just hope he remembers.

**Comment by Paralusion** [comment]
just hope he remembers: 2 years later :( probably not gonna happen.

**Comment by AutistEren** [comment]
i know, he says a module to burn yourself when you are low so your items burn when you die

**Comment by feliscatusmeows** [comment]
It's for automatic destruction of your items when you are about to die. So that nobody else gets any.
