### ISSUE TITLE
Max Tracers

### ISSUE THREAD

**Issue by Hexiro** [THEREALWWEFAN231/Inertia#528]
**1.12.2 but really any**

**What is the suggestion**
Under Blockesp and tracers have a "max tracers option" so that 30000 tracers don't all load in at once and there is a max amount.
**Why it will be useful**
In some regard this defeats the purpose but in certain situations this will be very useful. In my case, on 9b9t i have obsidian tracers on but when i join the queue world almost the entire thing is made out of obsidian so there are hundreds if not thousands of tracers and i have 1 fps.

**Comment by Paralusion** [comment]
but why have obsidian tracers on?

**Comment by Hexiro** [comment]
you could say that about literally any block it doesn't change anything and because you will find half broken nether portals

**Comment by Paralusion** [comment]
to me this seems like a lot of work, purely for **you** being too lazy to have it turned off when you don't need it

**Comment by THEREALWWEFAN231** [comment]
No, ill add it, it's not much of a problem.
