### ISSUE TITLE
death screen free cam

### ISSUE THREAD

**Issue by theflyingturtle1257** [THEREALWWEFAN231/Inertia#529]
**1.12.2**

since you can see everything happening around you in the death screen, make a way to move the camera around meanwhile

and the chunks will even load if you log out and rejoin, since you dont even show up on tracers while in death screen there may be some cool stuff to do with this like either spying or even a new god mode.

**Comment by zyrafal** [comment]
It can't show you what is happening around you, because it just loops a few seconds of your death on death screen. It may be client-side, but i don't think it is.

**Comment by Godeps2891** [comment]
#111 duplicate
