### ISSUE TITLE
Kill Aura doesn't work on Bats and the Enderdragon and Auto Clicker doesn't hurt but swings at the Ender Dragon Bug

### ISSUE THREAD

**Issue by CasualWolfGamer** [THEREALWWEFAN231/Inertia#534]
**Inertia Utility Mod version:** 
**Minecraft version:** 
**Operating system:** 
**Optifine/Other mods:** 

**What's the issue:** 

**Crash-report(Would be very useful also please format):**

**Comment by Paralusion** [comment]
would be fixed with #27
