### ISSUE TITLE
stash logger

### ISSUE THREAD

**Issue by watermelonnull** [THEREALWWEFAN231/Inertia#535]
**Minecraft Version(s)**
1.12.2
**What is the suggestion**
While using baritone afk, stash logger will take note of an increased amount of chests (usually changeable from 1 to 10+), shulkers, or other storages placed by players in a chunk. It then logs it in a txt file. The txt file could then be named the server, and the date that txt was created, a txt will only actually be created if anything is found. 
**Why would this feature be useful**
Allows for lazy people to afk at a new level of laziness. Using baritone to just walk and logging any stashes. 

ex. txt
--------------------------------------------------------------------------
6 chests (83019301, -381031803)
1 shulker (38013810, 0133013)

**Comment by watermelonnull** [comment]
txt name could look like


Constantiam (2/13/20)

**Comment by THEREALWWEFAN231** [comment]
3.1 already has block logger, and its the best in the game.

**Comment by watermelonnull** [comment]
fbkjebfksjfeksjffjanbefjkaf 
YAYAYAYAY WWEEWEWFAN UR THE BEST
