### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by watermelonnull** [THEREALWWEFAN231/Inertia#537]
**Inertia Utility Mod version:** 
3.0.4
**Minecraft version:** 
1.12.2
**Operating system:** 
mac os
**Optifine/Other mods:** 
none
**What's the issue:** 
when antikb is turned on auto fish does not work, the rod will not be able to reel out 
**Crash-report(Would be very useful also please format):**
no crash report

**Comment by THEREALWWEFAN231** [comment]
Try turning anti knockback on mode new

**Comment by watermelonnull** [comment]
thanks it got fixed
