### ISSUE TITLE
Auto-tool improvements

### ISSUE THREAD

**Issue by MESSIOS** [THEREALWWEFAN231/Inertia#538]
**Minecraft Version(s)**
1.12.2 but most certainly everything after 1.8.9

**What is the suggestion**
Make a switch for the Auto-tool module in which u can choose between the sword or the axe as the attack weapon

**Why would this feature be useful**
It would just add some more flexibility to this module.

**Comment by Paralusion** [comment]
already is a thing

**Comment by MESSIOS** [comment]
under which option?

**Comment by DaoMei520** [comment]
Unable to show download

**Comment by Paralusion** [comment]
Auto Tool: entities
