### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Karkexx** [THEREALWWEFAN231/Inertia#539]
1.15.1+ All if able.

Add item_frame to blockesp/xray

Many private vaults are made solely with item frames holding shulkers. Would help out a lot!

Thank you!

**Comment by THEREALWWEFAN231** [comment]
> ESP already has an option for item frames.

**Comment by Karkexx** [comment]
.blockesp add item_frame doesn't come up with anything..

**Comment by THEREALWWEFAN231** [comment]
I said its an option in ESP, not something you add in block esp, item frames are entities, not blocks.

**Comment by Karkexx** [comment]
Thank you
