### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#540]
All

User will create cheat profiles to switch between hacks faster. For an example. I will create a profile for pvp and vanilla. pvp will have kill aura, criticals and more and vanilla wont have any cheats and I will be able to switch between them to change multiple hacks at same time.

To save time.

I hope this was understandable cuz english isnt my main language

**Comment by Paralusion** [comment]
already exists, called presets

**Comment by THEREALWWEFAN231** [comment]
These aren't cheats. There's already presets, you can access them from the Click Gui.

**Comment by AutistEren** [comment]
> These aren't cheats. There's already presets, you can access them from the Click Gui.

oh my bad!
