### ISSUE TITLE
Invalid Character Causing Crash

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#543]
**Inertia Utility Mod version:** 3.0.4
**Minecraft version:** 1.15.2
**Operating system:** Windows 10, 64-bit
**Optifine/Other mods:** N/A

**What's the issue:** 
Doing .blockspoof remove * (Or any non [a-z0-9/._-] character) will cause the game to crash and reset everything in BlockSpoof. This issue seems to be fixed for other modules like .xray and .blockesp, however instead of crashing it just gives out an error message instead of saying it's not a valid block.

The game crashed whilst keypressed event handler
Error: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:*

**Crash-report(Would be very useful also please format):**
[crash-2020-07-04_16.21.43-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/4872203/crash-2020-07-04_16.21.43-client.txt)

**Comment by THEREALWWEFAN231** [comment]
"Fixed" for 3.1, won't be in the changelog though, as its almost irrelevant.
