### ISSUE TITLE
Main Menu Rework / Remove "Rage Quit" Button

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#544]
**Minecraft Version(s)** 1.15.2

**What is the suggestion** Remove the "rage quit" button on the main menu.

**Why would this feature be useful**
It's completely and utterly useless and does nothing except add extra clutter. If you're raging, who is going to **disconnect** from the server, **click** on the arrow to scroll along the main menu, and then finally click rage quit? All you need to do is alt+f4, or hit X if you aren't in fullscreen. The main menu definitely needs to be compacted and have a rework, as right now it's not the most aesthetically pleasing thing. I assume that this is already coming due to the rebranding of the utility mod, so I **BEG** please do a good job. The very first thing I did when installing the client was change the background image.

**Comment by THEREALWWEFAN231** [comment]
It's not going to get removed, its just there because on the main menu screen there's a quite button, but in 3.1 there is a new main menu added(because of the new name) that more resembles the default Minecraft main menu. I think/hope more people will like it.
