### ISSUE TITLE
download version

### ISSUE THREAD

**Issue by AndyAndy02** [THEREALWWEFAN231/Inertia#550]
do i have to wait to version 3.1 to download Inertia Client???

**Comment by Paralusion** [comment]
Yes, inertia has not yet been released. We don't suggest looking for an older version, as it may contain malware which will harm your computer.

**Comment by AndyAndy02** [comment]
How long do i have to wait btw...?

**Comment by Paralusion** [comment]
No set release date.

**Comment by AndyAndy02** [comment]
?

**Comment by AndyAndy02** [comment]
how
