### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bellCranelok** [THEREALWWEFAN231/Inertia#551]
WWE3.0.4
1.12.2
Windows 10
No

Hello, how can I make notebot work if it can’t connect to wweclient.com? Is it possible?

**Comment by THEREALWWEFAN231** [comment]
We do not support anything with wweclient.com, But you can manually download the songs here https://inertiaclient.com/notebotsongs/songs.zip you will have to figure out where to put all the nbs files.
