### ISSUE TITLE
.condense

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#554]
**Minecraft Version(s)** any

**What is the suggestion** A command .condense (or possibly module that does it automatically) that converts things in your inventory to block form. For example, 
wheat > hay blocks
diamonds > diamond blocks
gold nuggets > gold ingots/gold blocks
coal > coal blocks

**Why would this feature be useful** Adds more inventory space as a quality of life thing. This would only affect reversible crafts, so it wouldn't convert glowstone dust to glowstone as you can't reverse it back into dust by crafting it. But you can turn diamond blocks back into diamonds, and vice versa.

**Comment by yutaneki** [comment]
So you're going to convert diamonds to diamond blocks without a crafting table?
I don't see the point.

**Comment by TheRedHippo** [comment]
> So you're going to convert diamonds to diamond blocks without a crafting table?
> I don't see the point.

you're right, im retarded. forgot that you can't convert it in your inventory
