### ISSUE TITLE
Suggestion:Anti-Xray Bypass

### ISSUE THREAD

**Issue by VoidCyborg** [THEREALWWEFAN231/Inertia#555]
**Minecraft Version(s)**
1.12.2 - 1.16.1
**What is the suggestion**
Add anti-xray bypass, when u use xray and freecam u can hit fake ore and its disappear. I think its possible to write script what do the same by few seconds. And all fake ores will disappear in near area.
**Why would this feature be useful**
It will help all players who play on servers with anti-xray plugin.

**Comment by THEREALWWEFAN231** [comment]
I know this is secretly already added in the 1.12 version, it's not enabled though, as it works pretty bad, so until I fix it, it won't be added publically.

**Comment by scarifyFX** [comment]
nice

**Comment by Paralusion** [comment]
duplicate of  #42
