### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RocketNinja15** [THEREALWWEFAN231/Inertia#557]
**Minecraft Version(s)**
1.12.2+
**What is the suggestion**
Auto-reconnect bypassed by auto-log. When you take a certain amount of damage, it will log you out of the game, and not log you back in to be killed.
**Why would this feature be useful**
Currently, I might be AFK and someone would try to kill me, the game would about log, but then log back in after four seconds, therefore eliminating auto-log's purpose.

**Comment by THEREALWWEFAN231** [comment]
Added(I think, I didn't actually test it, but it should work).
