### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Missing-entity** [THEREALWWEFAN231/Inertia#558]
**Minecraft Version(s)**
1.12.2-1.16.1
**What is the suggestion**
tight multi-shot.
**Why would this feature be useful**
if possible makes the three arrows from multi shot be closer together. so all three arrows could hit a farther target.

also add an aim-bot setting that doesn't lock client side view. so from player point of view arrows will fly off sideways to entity closest to cross-hair.

**Comment by Paralusion** [comment]
this would not be possible
