### ISSUE TITLE
nametag Bug

### ISSUE THREAD

**Issue by HoppaC4** [THEREALWWEFAN231/Inertia#56]
**WWE version:2.7.2** 
**Minecraft version:1.14.2** 
**Operating system:win10** 
**Optifine/Other mods:no** 

**Whats the issue:nametags not showing and it fucks with the water and other stuff http://prntscr.com/o89kdu
http://prntscr.com/o89kks** 

**Crash-report(Would be very useful also please format):**

**Comment by Paralusion** [comment]
Known issue.

**Comment by d3monfiend** [comment]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.3
**Operating system:** Windows 7 Professional
**Optifine/Other mods:** No.

**Whats the issue:** Name tag 2d glitches out.

**Crash-report(Would be very useful also please format):** When using name tag and have potion buff or debuff, the 2d player tag will glitch out, water surface also glitches out and player model will face inwards

**Comment by THEREALWWEFAN231** [comment]
> **WWE version:** 2.7.2
> **Minecraft version:** 1.14.3
> **Operating system:** Windows 7 Professional
> **Optifine/Other mods:** No.
> 
> **Whats the issue:** Name tag 2d glitches out.
> 
> **Crash-report(Would be very useful also please format):** When using name tag and have potion buff or debuff, the 2d player tag will glitch out, water surface also glitches out and player model will face inwards

We know about this and all of them, esp, and name tags are getting recoded(although some might look the same)

**Comment by d3monfiend** [comment]
I just put here just in case someone need to know what is cause the 2d glitch.

**Comment by snowmii** [comment]
may i know what cause the glitch
my mod make texture glitches out too :/

**Comment by THEREALWWEFAN231** [comment]
Wait it still does that...

**Comment by snowmii** [comment]
so how can i fix it

**Comment by THEREALWWEFAN231** [comment]
Wait till i fix it, idk if it will be in 3.0.2 we will see, it would help if you could supply a list of the modules you have enabled and the settings for name tags, maybe a screen shot?

**Comment by snowmii** [comment]
wait i fixed it 
i just add  GlStateManager.popMatrix(); in the end of the code

**Comment by THEREALWWEFAN231** [comment]
... what does "i just add GlStateManager.popMatrix(); in the end of the code mean"

**Comment by snowmii** [comment]
`   private void drawNametag(Entity entityIn) {
        GlStateManager.pushMatrix();

        Vec3d interp = EntityUtil.getInterpolatedRenderPos(entityIn, mc.getRenderPartialTicks());
        float yAdd = entityIn.height + 0.5F - (entityIn.isSneaking() ? 0.25F : 0.0F);
        double x = interp.x;
        double y = interp.y + yAdd;
        double z = interp.z;

        float viewerYaw = mc.getRenderManager().playerViewY;
        float viewerPitch = mc.getRenderManager().playerViewX;
        boolean isThirdPersonFrontal = mc.getRenderManager().options.thirdPersonView == 2;
        GlStateManager.translate(x, y, z);
        GlStateManager.rotate(-viewerYaw, 0.0F, 1.0F, 0.0F);
        GlStateManager.rotate((float) (isThirdPersonFrontal ? -1 : 1) * viewerPitch, 1.0F, 0.0F, 0.0F);

        float f = mc.player.getDistance(entityIn);
        float m = (f / 8f) * (float) (Math.pow(1.2589254f, this.scale.getValue()));
        GlStateManager.scale(m, m, m);

        FontRenderer fontRendererIn = mc.fontRenderer;
        GlStateManager.scale(-0.025F, -0.025F, 0.025F);

        String str = entityIn.getName() + (health.getValue() ? " " + Command.SECTIONSIGN() + "a" + Math.round(((EntityLivingBase) entityIn).getHealth() + (entityIn instanceof EntityPlayer ? ((EntityPlayer) entityIn).getAbsorptionAmount() : 0)) : "");
        int i = fontRendererIn.getStringWidth(str) / 2;
        GlStateManager.enableBlend();
        GlStateManager.tryBlendFuncSeparate(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA, GlStateManager.SourceFactor.ONE, GlStateManager.DestFactor.ZERO);
        GlStateManager.enableTexture2D();
        Tessellator tessellator = Tessellator.getInstance();

        BufferBuilder bufferbuilder = tessellator.getBuffer();

        glTranslatef(0, -20, 0);
        bufferbuilder.begin(GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
        bufferbuilder.pos(-i - 1, 8, 0.0D).color(0.0F, 0.0F, 0.0F, 0.5F).endVertex();
        bufferbuilder.pos(-i - 1, 19, 0.0D).color(0.0F, 0.0F, 0.0F, 0.5F).endVertex();
        bufferbuilder.pos(i + 1, 19, 0.0D).color(0.0F, 0.0F, 0.0F, 0.5F).endVertex();
        bufferbuilder.pos(i + 1, 8, 0.0D).color(0.0F, 0.0F, 0.0F, 0.5F).endVertex();
        tessellator.draw();

        bufferbuilder.begin(GL_LINE_LOOP, DefaultVertexFormats.POSITION_COLOR);
        bufferbuilder.pos(-i - 1, 8, 0.0D).color(.1f, .1f, .1f, .1f).endVertex();
        bufferbuilder.pos(-i - 1, 19, 0.0D).color(.1f, .1f, .1f, .1f).endVertex();
        bufferbuilder.pos(i + 1, 19, 0.0D).color(.1f, .1f, .1f, .1f).endVertex();
        bufferbuilder.pos(i + 1, 8, 0.0D).color(.1f, .1f, .1f, .1f).endVertex();
        tessellator.draw();

        GlStateManager.enableTexture2D();

        GlStateManager.glNormal3f(0.0F, 1.0F, 0.0F);
	if(!entityIn.isSneaking()) fontRendererIn.drawString(str, -i, 10, entityIn instanceof EntityPlayer ? Friends.isFriend(entityIn.getName()) ? 0x00bfff : 0xffffff : 0xffffff);
        else fontRendererIn.drawString(str, -i, 10, 0xffaa00);
	if (entityIn instanceof EntityPlayer && armor.getValue()) renderArmor((EntityPlayer)entityIn, 0, -(fontRendererIn.FONT_HEIGHT + 1) - 20);
        GlStateManager.glNormal3f(0.0F, 0.0F, 0.0F);
        glTranslatef(0, 20, 0);

        GlStateManager.scale(-40, -40, 40);	    
	**GlStateManager.popMatrix();**
    }`

**Comment by THEREALWWEFAN231** [comment]
Thats not wwe....?..

**Comment by snowmii** [comment]
yes that's not

**Comment by snowmii** [comment]
but i think the problem could be same

**Comment by snowmii** [comment]
https://cdn.discordapp.com/attachments/629862249409937408/650895492594794516/2019-12-02_11.05.23.png

**Comment by Paralusion** [comment]
should have been fixed
