### ISSUE TITLE
Found a bug:I can't download inertiaclient

### ISSUE THREAD

**Issue by zz87** [THEREALWWEFAN231/Inertia#560]
I can't download inertiaclient，please look this the photo!
![Screenshot_20200727_170604_com android browser](https://user-images.githubusercontent.com/68846848/88524103-8c221080-cfbe-11ea-84b8-ec8a21234cc6.jpg)

**Comment by zz87** [comment]
Oh no，bug is:I can't download inertiaclient，please look the photo!

**Comment by zz87** [comment]
Please upload inertia on github.

**Comment by zz87** [comment]
On Releases.

**Comment by zz87** [comment]
I am chinese people，so the photo has a chinese.

**Comment by DoctorIDD** [comment]
My problem is the same as you,my PC browser cannot download the inertia client.

**Comment by zz87** [comment]
Ok



---Original---

**Comment by scarifyFX** [comment]
Downloads have been disabled till 3.1 releases

**Comment by TheGrandMaster26** [comment]
> Downloads have been disabled till 3.1 releases

and when will it release

**Comment by THEREALWWEFAN231** [comment]
You can not download until 3.1, 3.1 is not released yet.

**Comment by JohnShiozo** [comment]
LMAO

**Comment by valetzx** [comment]
爬，下载 关闭 直到 3.1 更新

**Comment by scarifyFX** [comment]
We Done knep

tis 28 juli 2020 kl. 11:33 skrev Man Victor <notifications@github.com>:
