### ISSUE TITLE
Better Barrier Vision

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#563]
**Minecraft Version(s)** Any

**What is the suggestion** Ability to see barrier blocks as full blocks

**Why would this feature be useful** Because the current one shows the barrier texture

**Comment by THEREALWWEFAN231** [comment]
Barrier are not even blocks, they are literary just "particles", I was honestly suppose to remove it when 3.1 releases, but I'm not going to, in 3.1 you are able to add barriers to Block ESP, so id suggest using that when 3.1 releases.
