### ISSUE TITLE
Buggy Scrolling in the Colour Manager

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#566]
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 1.16.1
**Operating system:** Windows 10
**Optifine/Other mods:** N/A

**What's the issue:** When in the colour manager, scrolling through the settings can be incredibly buggy in how many of the settings don't show up and are cropped out, even though they should still be visible. This is very clear if you go under "ESP", open every setting, and start scrolling.

**Comment by THEREALWWEFAN231** [comment]
https://cdn.discordapp.com/attachments/737778716465168455/738991642203258980/Screenshot_84.png

**Comment by THEREALWWEFAN231** [comment]
Fixed in 3.1.1.
