### ISSUE TITLE
Bug Inventory

### ISSUE THREAD

**Issue by alientony** [THEREALWWEFAN231/Inertia#57]
**WWE version:2.7.2** 
**Minecraft version:1.14.3** 
**Operating system:Windows 10** 
**Optifine/Other mods:informedload-1.1.1, LightOverlay-1.1.0.6, ModMenu-1.5.3-84, mousewheelie-1.1.5+1.14** 

**Whats the issue: Inventory bugs out now showing items. ** 
![image](https://user-images.githubusercontent.com/11477330/60389372-bdf83900-9a85-11e9-8870-77393bec4d87.png)

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
What modules do you have enabled?

**Comment by alientony** [comment]
Treasure Map Coords Infinite Chat Length Strong Hold Finder Inventory Cleaner Full Bright Teleport Finder Off Hand Crash Player ESP Death Coords Trident Boost Anti Book Ban Trajectories Color Signs Name Tags Time Stamp Way Points Color List Item ESP Tracers No Turn Search No Fall Portal Peek Hud MCF

Cords is spelt wrong within the modules.txt section.

**Comment by Godeps2891** [comment]
closed; outdated bug/crash report
