### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by VoidCyborg** [THEREALWWEFAN231/Inertia#571]
**Inertia Utility Mod version: 3.1**
**Minecraft version:1.16.1** 
**Operating system: Windows 10** 
**Optifine/Other mods: Sodium and VoxelMap** 

**What's the issue: Crashing when using Freecam** 

**Crash-report(Would be very useful also please format): TXT**
[crash-2020-08-01_08.49.43-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5009899/crash-2020-08-01_08.49.43-client.txt)
[crash-2020-08-01_08.42.31-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5009900/crash-2020-08-01_08.42.31-client.txt)
[crash-2020-08-01_08.46.33-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5009901/crash-2020-08-01_08.46.33-client.txt)

**Comment by THEREALWWEFAN231** [comment]
This is fixed in 3.1.1.
