### ISSUE TITLE
ESP not displaying blast furnaces/smokers

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#572]
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 1.16.1
**Operating system:** Windows 10
**Optifine/Other mods:** N/A

**What's the issue:** ESP does not display blast furnaces or smokers, even if the furnaces setting is on.
![Screenshot_86](https://user-images.githubusercontent.com/67818307/89095587-eeda3880-d412-11ea-80bb-d08b1579a00f.png)

**Comment by THEREALWWEFAN231** [comment]
Fixed in 3.1.1, I noticed the smithing table did not show as well and it appears its not a Tile Entity, so you'd have to use Block ESP for that, just saying.
