### ISSUE TITLE
Sideways scaffold

### ISSUE THREAD

**Issue by Cypphi** [THEREALWWEFAN231/Inertia#579]
**Inertia Utility Mod version:** Probably all versions with scaffold
**Minecraft version:** All
**Operating system:** Doesn't matter
**Optifine/Other mods:** Doesn't mattet either

**What's the issue:** When using scaffold walk sideways the player will get stuck in the corner of a block and then the client won't place anymore blocks which is quite annoying.

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Try using scaffold mode(I think its called all not normal). Tell me if that works.

**Comment by Cypphi** [comment]
Aight, I'll try that out

**Comment by THEREALWWEFAN231** [comment]
If this isn't solved, feel free to reopen, but I'm pretty sure all mode it what your looking for.
