### ISSUE TITLE
.commands keybinds Suggestion

### ISSUE THREAD

**Issue by alientony** [THEREALWWEFAN231/Inertia#58]
114.3

Command keybinds. Examples: .bind ; .dupe dropall, or .bind [ .clip v 5 and .bind ] .clip v -5

This would be useful in the sense of fast action although these are less used being able to bind them would allow for quick teleport up and down floors or not having to open chat every time when I log back into a server I can dupe again at the press of a button.

**Comment by Paralusion** [comment]
Instead of this, a macro system with keybinds could be implemented.

**Comment by alientony** [comment]
That would probably be more suitable but at that point just adding a new module to the GUI allowing for you to bind commands to keys would be better seeing as how in the GUI you can already control the keybinds for "hacks"
