### ISSUE TITLE
Custom Font Crash

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#580]
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 1.16.1
**Operating system:** Windows 10
**Optifine/Other mods:** Sodium, but others without it have also reported this.

**What's the issue:** Joining a world while you have a custom font selected will instantly crash your game. Enabling the custom font once you've already loaded in is perfectly fine though.
_note_: The crash only seems to happen 50% of the time? It's very odd.
**Crash-report(Would be very useful also please format):**
[hs_err_pid14424.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5010257/hs_err_pid14424.txt)

**Comment by THEREALWWEFAN231** [comment]
I don't quite understand this "Joining a world while you have a custom font selected will instantly crash your game. Enabling the custom font once you've already loaded in is perfectly fine though.
note: The crash only seems to happen 50% of the time?". What i got was, you selected a custom font with .customfont, closed the game, then when starting it about 50% of the time joining a world crashes?

**Comment by TheRedHippo** [comment]
nvm it doesnt look like a chance thing
Video:
https://imgur.com/a/MkAkh1N
Crash:
[message (3).txt](https://github.com/THEREALWWEFAN231/Inertia/files/5011888/message.3.txt)

**Comment by VillagerNo4** [comment]
This is a bit late but a way to crudely fix this is going to the Inertia folder in your .minecraft file and finding the Modules.json

From there you edit it (I used Notepad ++). Find the Font and set the value to value:false instead of value:true

Crude but in case anyone cant open their world or even open the click gui in the menu, this is a way

**Comment by Paralusion** [comment]
known and we know how to fix it: trouble? create issue
