### ISSUE TITLE
BPS stuck at 0.

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#581]
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 1.16.1
**Operating system:** Windows 10
**Optifine/Other mods:** Sodium (but has been reported by many people without mods)

**What's the issue:** BPS counter does not switch off of 0 no matter how fast you're going.

**Comment by THEREALWWEFAN231** [comment]
Fixed in 3.1.1
