### ISSUE TITLE
Chatfilter gui dupe all line of chatfilter when opening the gui

### ISSUE THREAD

**Issue by Alsdrouf** [THEREALWWEFAN231/Inertia#585]
Inertia Utility Mod version: 3.1
Minecraft version: 1.15.2
Operating system: Windows 
Optifine/Other mods: Optifine + Optifabric 

What's the issue: .chatfilter gui dupe all line of chatfilter when opening the gui
![image](https://user-images.githubusercontent.com/40452949/89102581-19c08e80-d40b-11ea-9859-c15aeabbdc36.png)
![image](https://user-images.githubusercontent.com/40452949/89102585-28a74100-d40b-11ea-9b7b-b472d46ab07d.png)
![image](https://user-images.githubusercontent.com/40452949/89102599-4b395a00-d40b-11ea-80eb-163832b31d3c.png)

Note that the Chat Filter.json don't get changed
I think you add the Chat Filter.json content to a list every time we open it without reseting the list

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Fixed in 3.1.1.
