### ISSUE TITLE
thealtening not working

### ISSUE THREAD

**Issue by darktubeNL** [THEREALWWEFAN231/Inertia#586]
using the altening alts and api gives you an error

**Comment by THEREALWWEFAN231** [comment]
Just adding these
https://cdn.discordapp.com/attachments/737778716465168455/739162196919189614/unknown.png
https://cdn.discordapp.com/attachments/737778716465168455/739162108469575741/unknown.png

**Comment by THEREALWWEFAN231** [comment]
God damnnnn, that was much harder to fix then it should have been, fixed in 3.1.1
