### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Qdessix** [THEREALWWEFAN231/Inertia#589]
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 16.1
**Operating system:** win 7 <3
**Optifine/Other mods:**  Sodium

**What's the issue:** Just randomly crashed while flying on a server 
[crash-2020-08-01_18.33.53-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5010940/crash-2020-08-01_18.33.53-client.txt)

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
This is Block ESP, for now turn it off, ill look into a fix.

**Comment by THEREALWWEFAN231** [comment]
This wasn't 100% inertia, the server is sending an "invalid" packet, and Block ESP was reading it, causing the crash, but i made it check if the packet is invalid, so its fixed in 3.1.1.
