### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TheRealistik** [THEREALWWEFAN231/Inertia#590]
**Inertia Utility Mod version: 3.1
**Minecraft version: 1.12.2
**Operating system: Linux Mint
**Optifine/Other mods: Applied Energistics, Aroma1997Core (dependency for Aroma1997's Dimensional World), Aroma1997's Dimensional World, Baubles, Bibliocraft, Biomes O Plenty, Blood Magic, Buildcraft, Chisels and Bits, Dimensional Doors, Electroblob's Wizardry, Guide API (dependency for Blood Magic), Ido, Inventory Pets, Just Enough Items, Journey Map, Lucky Blocks, Mantle (dependency for Tinker's Construct), Minecraft Comes Alive, Minecolonies, More Overlays, Mystcraft, Open Blocks, Open Mods Lib (dependency for Open Blocks), Ore Excavation, Tinker's Construct, Tomb Many Graves, Traverler's Backpack, Twilight Forest

**What's the issue: I am able to boot Minecraft with my current 1.12.2 mods but when I add the Inertia jar to the mods folder and try booting Minecraft, the game crashes with "Error: java.lang.NullPointerException: Initializing game".

**Crash-report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  uldT (Inertia Client 3.1 - 1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 8/1/20 9:30 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.item.ItemMap.handler$BVjx$zzp000(ItemMap.java:568)
	at net.minecraft.item.ItemMap.func_77624_a(ItemMap.java:477)
	at jds.bibliocraft.items.ItemAtlas.func_77624_a(ItemAtlas.java:1121)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemMap.handler$BVjx$zzp000(ItemMap.java:568)
	at net.minecraft.item.ItemMap.func_77624_a(ItemMap.java:477)
	at jds.bibliocraft.items.ItemAtlas.func_77624_a(ItemAtlas.java:1121)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.4.0-26-generic
	Java Version: 1.8.0_252, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 335513880 bytes (319 MB) / 1778384896 bytes (1696 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                 | Source                                             | Signature                                |
	|:----- |:------------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LCH   | mcp                 | 9.42                    | minecraft.jar                                      | None                                     |
	| LCH   | FML                 | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | openmodscore        | 0.12.2                  | minecraft.jar                                      | None                                     |
	| LCH   | appliedenergistics2 | rv6-stable-7            | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | aroma1997core       | 2.0.0.2                 | Aroma1997Core-1.12.2-2.0.0.2.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCH   | aroma1997sdimension | 2.0.0.2                 | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar    | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCH   | baubles             | 1.5.2                   | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | bibliocraft         | 2.4.5                   | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCH   | biomesoplenty       | 7.0.1.2444              | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
	| LCH   | guideapi            | 1.12-2.1.8-63           | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| LCH   | bloodmagic          | 1.12.2-2.4.3-105        | BloodMagic-1.12.2-2.4.3-105.jar                    | None                                     |
	| LCH   | buildcraftlib       | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCH   | buildcraftcore      | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCH   | buildcraftbuilders  | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCH   | buildcrafttransport | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCH   | buildcraftsilicon   | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCH   | buildcraftcompat    | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCH   | buildcraftenergy    | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCH   | buildcraftfactory   | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCH   | buildcraftrobotics  | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCH   | chiselsandbits      | 14.33                   | chiselsandbits-14.33.jar                           | None                                     |
	| LCH   | dimdoors            | 1.12.2-3.1.2+UNOFFICIAL | DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar       | None                                     |
	| LCH   | ebwizardry          | 4.2.11                  | ElectroblobsWizardry-4.2.11-MC1.12.2.jar           | None                                     |
	| LCH   | ido                 | 1.0.6                   | ido-1.12.2-1.1.0.jar                               | None                                     |
	| LCH   | inertia             | 3.1                     | Inertia Client 3.1 - 1.12.2.jar                    | None                                     |
	| LCH   | inventorypets       | 2.0.6                   | inventorypets-1.12-2.0.6.jar                       | None                                     |
	| LCH   | jei                 | 4.15.0.296              | jei_1.12.2-4.15.0.296.jar                          | None                                     |
	| LCH   | journeymap          | 1.12.2-5.7.1            | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCH   | lucky               | 7.6.0                   | Lucky-Block-Mod-1.12.2.jar                         | None                                     |
	| LCH   | mantle              | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCH   | mca                 | 6.1.0                   | MCA-1.12.2-6.1.0-universal (1).jar                 | None                                     |
	| LCH   | moreoverlays        | 1.15.1                  | moreoverlays-1.15.1-mc1.12.2.jar                   | None                                     |
	| LCH   | mystcraft           | 0.13.7.06               | mystcraft-1.12.2-0.13.7.06.jar                     | None                                     |
	| LCH   | openmods            | 0.12.2                  | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | openblocks          | 1.8.1                   | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | oreexcavation       | 1.4.143                 | OreExcavation-1.4.143.jar                          | None                                     |
	| LCH   | squeedometer        | 1.0.4                   | Squeedometer-mc1.12.x-1.0.4.jar                    | None                                     |
	| LCH   | twilightforest      | 3.10.1013               | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
	| LCH   | tconstruct          | 1.12.2-2.13.0.183       | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LCH   | tombmanygraves      | 1.12-4.2.0              | TombManyGraves-1.12-4.2.0.jar                      | None                                     |
	| LCH   | travelersbackpack   | 1.0.32                  | TravelersBackpack-1.12.2-1.0.32.jar                | None                                     |
	| LCH   | structurize         | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar            | None                                     |
	| LCH   | minecolonies        | 1.12.2-0.11.804-RELEASE | minecolonies-1.12.2-0.11.804-RELEASE-universal.jar | None                                     |

	Loaded coremods (and transformers): 
uldT (Inertia Client 3.1 - 1.12.2.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.6 (Compatibility Profile) Mesa 20.0.4' Renderer: 'Mesa Intel(R) HD Graphics 620 (KBL GT2)'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Mesa Intel(R) HD Graphics 620 (KBL GT2) GL version 4.6 (Compatibility Profile) Mesa 20.0.4, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by THEREALWWEFAN231** [comment]
What mod pack is this, I really didn't want to fix this(I think its an easy fix, its just weird), but I guess a lot of people use that mod pack, but I'm pretty sure when i fix it, there's another crash, I don't want to fix it, then you have to submit another crash because the mod pack crashed for another reason.

**Comment by TheRealistik** [comment]
It's a custom modpack I made: http://www.mediafire.com/file/omge2yv21m3z8v8/mods.zip/file. It's fine if you don't really want to fix it, Inertia's still a great client.

**Comment by THEREALWWEFAN231** [comment]
Well I fixed that specific crash, but it crashed again, due to another reason, but this time with less/no relevant information, therefor i am not going to fix the second crash with it.
