### ISSUE TITLE
Black Screen when going into F5

### ISSUE THREAD

**Issue by oofmas** [THEREALWWEFAN231/Inertia#598]
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 1.16.1
**Operating system:** Windows 10
**Optifine/Other mods:** None

**What's the issue:** Black screen in F5, stops happening when Nametags is on. Attached is my enabled modules.
![2020-08-01_21 16 08](https://user-images.githubusercontent.com/69096876/89113911-5bb5f880-d43c-11ea-8643-4bb4b51d893f.png)
![2020-08-01_21 16 22](https://user-images.githubusercontent.com/69096876/89113919-63759d00-d43c-11ea-8a1f-931c370491b9.png)

**Crash-report(Would be very useful also please format):** N/A

**Comment by THEREALWWEFAN231** [comment]
It was Name Tags head option, fixed in 3.1.1
