### ISSUE TITLE
Chat Bot Gui resetting

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#600]
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 1.16.1
**Operating system:** Windows 10
**Optifine/Other mods:** Sodium

**What's the issue:** Any text added via the Chat Bot GUI will automatically be removed the next time you open up the GUI.

**Comment by THEREALWWEFAN231** [comment]
Also when loading chat bot it should ignore empty elements, like if the announcer element is empty

**Comment by THEREALWWEFAN231** [comment]
That wasn't very cash money of me, fixed in 3.1.1.
