### ISSUE TITLE
damage while using speed

### ISSUE THREAD

**Issue by Jumpscare314** [THEREALWWEFAN231/Inertia#604]
version: Inertia 3.1
Minecraft version: 1.12.2
Operating system: windows 10
Optifine/Other mods: none

What's the issue: speed on packet mode makes u take void damage killing you in seconds and speed on ncp mode sometimes makes you take random fall damage (may take some time to recreate)

Crash-report(Would be very useful also please format): -

**Comment by THEREALWWEFAN231** [comment]
This is not going to be "fixed", Speed mode Packet, and packet fly may both cause damage to the player on some servers, basically same with speed mode NCP.
