### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ppmaster69** [THEREALWWEFAN231/Inertia#605]
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 1.16.1
**Operating system:** windows 10
**Optifine/Other mods:** baritone litematica malilab optifine

**What's the issue:** everytime i try to start up minecraft it gives me a error unacceptable code point ' ' (0x0) special characters are not allowed
in "'reader'", position 0
[crash-2020-08-02_14.18.54-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5012207/crash-2020-08-02_14.18.54-client.txt)

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Weird, this isn't quite a Inertia bug/issue, but try going to your .minecraft folder, Inertia, 1.16.1, and delete the ViaVersion folder, and see if that works.
