### ISSUE TITLE
Chat Suffix

### ISSUE THREAD

**Issue by Oecher1** [THEREALWWEFAN231/Inertia#606]
**Minecraft Version(s)**
?
**What is the suggestion**
Just to add chat suffix as its simple to do and i don't see a reason why not to add it
**Why would this feature be useful**
Just to add chat suffix as its simple to do and i don't see a reason why not to add it

**Comment by THEREALWWEFAN231** [comment]
I assume your talking about the period for commands, its already a feature .prefix, if your talking about something else, feel free to describe what your talking about more.

**Comment by Oecher1** [comment]
> I assume your talking about the period for commands, its already a feature .prefix, if your talking about something else, feel free to describe what your talking about more.

chat suffix like on 1.12.2 anarchy servers with messages like | Kami to the right of your messages

**Comment by Oecher1** [comment]
> I assume your talking about the period for commands, its already a feature .prefix, if your talking about something else, feel free to describe what your talking about more.

http://i.imgur.com/vrL1qf3.png next to the right of my message

**Comment by THEREALWWEFAN231** [comment]
Ohh hel* no lmao, thats way to toxic lmao, I'm not swooping down to kami skid level.

**Comment by Oecher1** [comment]
> Ohh hel* no lmao, thats way to toxic lmao, I'm not swooping down to kami skid level.

kami was just a example but ok

**Comment by THEREALWWEFAN231** [comment]
I mean every kami skid has that.
