### ISSUE TITLE
Altening non function

### ISSUE THREAD

**Issue by Maximillus** [THEREALWWEFAN231/Inertia#607]
**Inertia Utility Mod version:** inerta 3.1
**Minecraft version:** 1.16.1
**Operating system:** linux
**Optifine/Other mods:** sodium

**What's the issue:** When i try log with altening, using api key generating alt or free token i get message "An error has occured report this if you know it should work"

**Crash-report(Would be very useful also please format):**"An error has occured report this if you know it should work"

**Comment by Paralusion** [comment]
That message displays if you're entering a wrong (API) token. For TheAltening, API token's look like this: api-xxxx-xxxx-xxxx. Account login tokens, that you can use on the free mode, look like this: wfebf-puo89@alt.com or 6a737-h25f1@alt.com.

**Comment by aisair** [comment]
this may relate to #586

**Comment by THEREALWWEFAN231** [comment]
God damnnnn, that was much harder to fix then it should have been, fixed in 3.1.1
