### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TheLittenLord** [THEREALWWEFAN231/Inertia#608]
**Inertia Utility Mod version:** 
3.1
**Minecraft version:** 
1.15.2
**Operating system:** 
Ubuntu 18.04 LTS
**Optifine/Other mods:** 
Optifine, optifabric, fabric api, xaeros minimap
**What's the issue:** 
My cape won't show up >:I
**Crash-report(Would be very useful also please format):**
n/a

**Comment by Paralusion** [comment]
How does this issue relate to Inertia at all?

**Comment by TheLittenLord** [comment]
it relates to inertia because it's the inertia cape that isnt showing up

**Comment by Paralusion** [comment]
not everyone gets a cape, only donators do

**Comment by TheLittenLord** [comment]
![Workspace 1_152](https://user-images.githubusercontent.com/67177072/89126610-c8141480-d49b-11ea-9ef8-88bc2f6e71a2.png)
say what now?

**Comment by TheLittenLord** [comment]
My donor rank wont show up in IRC, and my cape doesn't show up in-game :(

**Comment by THEREALWWEFAN231** [comment]
I think the cape issue is fixed in 3.1.1.
