### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TheLittenLord** [THEREALWWEFAN231/Inertia#609]
**Inertia Utility Mod version:** 
3.1
**Minecraft version:** 
1.15.2
**Operating system:** 
Ubuntu 18.04 LTS
**Optifine/Other mods:** 
Lithium, Phosphor, Xaero's Minimap, Fabric API
**What's the issue:** 
Pressing f5 to go into 3rd person crashes me
**Crash-report(Would be very useful also please format):**
[latest.log](https://github.com/THEREALWWEFAN231/Inertia/files/5012382/latest.log)

**Comment by aisair** [comment]
Any rendering of the Inertia capes might crash your game (the crash log reads "Non [a-z0-9/._-] character in path of location: minecraft:InertiacapePurpleCape.png"). A temporary fix is to unequip the cape until this is fixed.

**Comment by THEREALWWEFAN231** [comment]
Yes this only happens in 1.13+, it will/has been fixed in 3.1.1.
