### ISSUE TITLE
Airjump

### ISSUE THREAD

**Issue by Cypphi** [THEREALWWEFAN231/Inertia#612]
**Minecraft Version(s)** all

**What is the suggestion** add airjump as an easy way to bypass vanilla fly detect and it's just really nice to have

**Why would this feature be useful** AirJump can be used to bypass vanilla anti fly, it's also a good way to move around in some cases.

**Comment by GaiaAlexf** [comment]
I like using this in other clients to do things like jump up small jumps, or in tight spaces, I was really surprised that this isn't already in the client. I hope it gets added soon!

**Comment by Cypphi** [comment]
> 
> 
> I like using this in other clients to do things like jump up small jumps, or in tight spaces, I was really surprised that this isn't already in the client. I hope it gets added soon!

So I'm not the only one :), I would love to see that in the client. It shouldn't be that hard to add since it's just removing the anti jump when in air thingy. (I dont know shit)

**Comment by Paralusion** [comment]
duplicate #88
