### ISSUE TITLE
Better Selection Module

### ISSUE THREAD

**Issue by PogPig** [THEREALWWEFAN231/Inertia#614]
**Minecraft Version(s)**
1.16.1
**What is the suggestion**
Another mode called "Vanilla" or something, which has just the vanilla selection outline so you can have just the colour changed not the selection outline aswell.
**Why would this feature be useful**
Not sure really, I just would like it added, but it might be useful for a few other people too.

**Comment by THEREALWWEFAN231** [comment]
This is already a feature, I my self forgot, turn off option fill.

**Comment by TheRedHippo** [comment]
I think by vanilla they mean that the lines won't be rendered through other blocks.
