### ISSUE TITLE
BetterHotBar not showing enchants

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#616]
**Inertia Utility Mod version:**  3.1
**Minecraft version:** 1.16.1
**Operating system:** Windows 10
**Optifine/Other mods:** Sodium

**What's the issue:** Items do not appear enchanted if they're in the first slot of BetterHotbar.

**Comment by THEREALWWEFAN231** [comment]
Fixed in 3.1.1.
