### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TsukiKagami** [THEREALWWEFAN231/Inertia#619]
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 1.16.1
**Operating system:** Windows10
**Optifine/Other mods:** No
**What's the issue:** if you place a sign with the "Time Stamp" module and click on finish then the game crashes.

**Crash-report(Would be very useful also please format):**

**Comment by TheRedHippo** [comment]
[crash-2020-08-03_19.26.37-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5015052/crash-2020-08-03_19.26.37-client.txt)

**Comment by TheRedHippo** [comment]
Experiencing the same with auto sign as well, might be because I edited the JSON though.
[crash-2020-08-03_20.23.02-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5015418/crash-2020-08-03_20.23.02-client.txt)

**Comment by THEREALWWEFAN231** [comment]
This is already fixed in 3.1.1(when it releases), thanks for reporting though.
