### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WERooo** [THEREALWWEFAN231/Inertia#620]
**Inertia Utility Mod version:** 
3.1
**Minecraft version:** 
1.12.2 Forge
**Operating system:** 
Win 10
**Optifine/Other mods:** 
Opti HD F5 Ultra

**What's the issue:** 
When i tried turn off flight from ClickGUI in main menu (Inertia Options -> ClickGUI) minecraft crashes!

**Crash-report(Would be very useful also please format):**
[latest.log](https://github.com/THEREALWWEFAN231/Inertia/files/5017273/latest.log)

**Comment by THEREALWWEFAN231** [comment]
Fixed in 3.1.1.
