### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by WERooo** [THEREALWWEFAN231/Inertia#621]
Inertia Utility Mod version:
3.1
Minecraft version:
1.12.2 Forge
Operating system:
Win 10
Optifine/Other mods:
Opti HD F5 Ultra 

**What's the issue:** 
When i tried join to spigot 1.12.2 server (they have viavers) with selected 1.12.2 version in ViaVersions in multiplayer menu, me logout with error NullPointerException. Only when I choose version 1.13 can I log into the server. (im russian)
**Crash-report(Would be very useful also please format):**
[logs.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5017328/logs.txt)

**Comment by THEREALWWEFAN231** [comment]
This is a ViaVersion bug, and honestly makes no sense. Your using forge 1.12.2, using(inertia via version, 1.12.2, which means your not using via version), and your getting null pointer exceptions, doesn't make sense. either way i cant fix it. Its not an inertia issue.
