### ISSUE TITLE
Suggestion: Baritone Mod

### ISSUE THREAD

**Issue by TsukiKagami** [THEREALWWEFAN231/Inertia#622]
**Minecraft Version(s)**: 1.16.1

**What is the suggestion**: Baritone Mod

**Why would this feature be useful**: to find a fast and automated way to get away from the spawn of an anarchy server

**Comment by THEREALWWEFAN231** [comment]
This will be added when baritone officially releases for 1.16.1

**Comment by Paralusion** [comment]
added
