### ISSUE TITLE
Strange issue where blocks render on top of actual blocks

### ISSUE THREAD

**Issue by Errorcrafter** [THEREALWWEFAN231/Inertia#627]
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 1.16.1
**Operating system:** Windows 10
**Optifine/Other mods:** Sodium, Lithium

**What's the issue:** When I joined a server using the client issues would arise where block models would render everywhere, instead of on the block's hitbox. This doesn't crash the game or anything, it's just annoying and makes the game unplayable. Some screenshots: 
![image](https://user-images.githubusercontent.com/69189354/89266089-0f4f0080-d668-11ea-8e90-d70449b07bd4.png)
![image](https://user-images.githubusercontent.com/69189354/89266146-2130a380-d668-11ea-95dc-cefadc8362c0.png)
![image](https://user-images.githubusercontent.com/69189354/89267696-268eed80-d66a-11ea-8b4f-14ade8a15b84.png)
![image](https://user-images.githubusercontent.com/69189354/89266193-2e4d9280-d668-11ea-8bae-2789b3c603ea.png)
![image](https://user-images.githubusercontent.com/69189354/89267502-e6c80600-d669-11ea-9473-a75e2effcd22.png)
![image](https://user-images.githubusercontent.com/69189354/89266339-605ef480-d668-11ea-8ea5-fd0143db2e0a.png)
![image](https://user-images.githubusercontent.com/69189354/89269311-53440480-d66c-11ea-8528-ffab67b6a9a8.png)
![image](https://user-images.githubusercontent.com/69189354/89267368-b97b5800-d669-11ea-94bf-9aa609c94081.png)

I have no idea what's causing this. These screenshots were taken after uninstalling Lithium, and other users claimed having no problems with using Inertia with Sodium? Can you please help? Thanks!
**EDIT:** Turns out the issue randomly stopps occuring after some time, but reoccurs randomly as well.

**Crash-report(Would be very useful also please format):** N/A

**Comment by THEREALWWEFAN231** [comment]
I have no idea, It might be inertias' Xray fix for sodium, all i can really suggest, at least for now is trying just inertia and see if it still happens.

**Comment by Errorcrafter** [comment]
> 
> 
> I have no idea, It might be inertias' Xray fix for sodium, all i can really suggest, at least for now is trying just inertia and see if it still happens.

Alright then I will update the post if anything new crops up while using Inertia w/o Sodium.
