### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by WERooo** [THEREALWWEFAN231/Inertia#630]
**Inertia Utility Mod version:** 
3.1
**Minecraft version:** 
1.12.2 Forge
**Operating system:** 
Win 10
**Optifine/Other mods:** 
Opti HD F5 Ultra

**What's the issue:** 
When i interact with birch door minecraft crashes!

**Crash-report(Would be very useful also please format):**
[stacktrace.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5021849/stacktrace.txt)

**Comment by THEREALWWEFAN231** [comment]
This is baritone, please report to their github.
