### ISSUE TITLE
Bug: Inventory Walk Interfering With GUIs

### ISSUE THREAD

**Issue by Epikest** [THEREALWWEFAN231/Inertia#638]
**Inertia Utility Mod version:** All
**Minecraft version:** All
**Operating system:** All
**Optifine/Other mods:** No

**What's the issue:** Using WASD with left hand mode in Inventory Walk and searching anything that contains WASD will rotate the player even if you are typing. This also applies to the chat.

**Comment by THEREALWWEFAN231** [comment]
That's the way its suppose to be, turn off Chat mode, but for the search, there's just about nothing we can do about that. The idea behind left hand and right hand mode is this, right hand players play with WASD to move around, and the arrow keys will change your yaw and pitch. And for left hand mode its the other way around.
