### ISSUE TITLE
Suggestion: Air jump

### ISSUE THREAD

**Issue by UmmName** [THEREALWWEFAN231/Inertia#639]
**Minecraft Version(s)** 1.8-1.16

**What is the suggestion** Air Jumping

**Why would this feature be useful** Its kinda like fly but you dont have to keep toggling it, i like it better than fly sometimes

**Comment by GaiaAlexf** [comment]
> **Minecraft Version(s)** 1.8-1.16
> 
> **What is the suggestion** Air Jumping
> 
> **Why would this feature be useful** Its kinda like fly but you dont have to keep toggling it, i like it better than fly sometimes

There's already a suggestion post for this. look at #612 (wwefan please close this issue as it's a copy)
