### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zz87** [THEREALWWEFAN231/Inertia#644]
cant't start inertia forge 1.12.2
crash log url:https://drive.google.com/file/d/1DB0iilS0TrC1aIWaolBT2Yhl19kHxhec/view?usp=sharing

**Comment by THEREALWWEFAN231** [comment]
Please update to Inertia 3.1.1, and when doing that, go to your .minecraft folder, and delete the Inertia folder.

**Comment by zz87** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you!
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                a77579963
                            
                    
                        
                            
                                    a77579963@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 8/7/2020 10:36，THEREALWWEFAN231<notifications@github.com> wrote： 



Please update to Inertia 3.1.1, and when doing that, go to your .minecraft folder, and delete the Inertia folder.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
