### ISSUE TITLE
Crash java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by TenTeypek** [THEREALWWEFAN231/Inertia#645]
**Inertia Utility Mod version:** 3.1.1
**Minecraft version:** 1.16.1
**Operating system:** Windows 10
**Optifine/Other mods:** no

**What's the issue:** The game randomly crashed.

**Crash-report(Would be very useful also please format):** https://pastebin.com/yYs2Xrtf

**Comment by THEREALWWEFAN231** [comment]
Yhprryszi#4421 has the same issue, its related to Block ESP, he says it only happens when he connects to a 1.8.x version from 1.16.1(via version). Ill have to take a look sometime.

**Comment by dotNEON** [comment]
I have the same issue, using version 3.1.1 on a 1.12.2 server.

**Comment by THEREALWWEFAN231** [comment]
Ok this is fully fixed in 3.1.2, I though I fixed it in 3.1.1, but I guess not.
