### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Righted1** [THEREALWWEFAN231/Inertia#653]
Inertia Utility Mod version: 3.1.1
Minecraft version: 1.12.2
Operating system: Windows 10
Optifine/Other mods: AmbientSounds and JourneyMap

What's the issue: Game crashing when launching

Crash-report(Would be very useful also please format): didnt give any crash reports

**Comment by THEREALWWEFAN231** [comment]
Try removing the other mods.... I really cant do anything without a crash log.

**Comment by Righted1** [comment]
> Try removing the other mods.... I really cant do anything without a crash log.

ive tried it but it still crashes the game even if im not launching forge

**Comment by THEREALWWEFAN231** [comment]
So if it happens in vanilla minecraft/nothing todo with inertia, you need to google it and try finding a solution.
