### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by hippostars** [THEREALWWEFAN231/Inertia#659]
**Minecraft Version(s)**
All
**What is the suggestion**
Suffix Message Eg: "Hello | Inertia", Interia Is The Suffix
**Why would this feature be useful**
I wanna advertise the client I really like it.

**Comment by THEREALWWEFAN231** [comment]
#606 I appropriate that you want to advertise it, but i find that more toxic they advertising, and usually represents a kami skid client.
