### ISSUE TITLE
changing the IRC prefix

### ISSUE THREAD

**Issue by GaiaAlexf** [THEREALWWEFAN231/Inertia#662]
**Minecraft Version(s)**
all?
**What is the suggestion**
ability to change IRC prefix from @ 
**Why would this feature be useful**
other mods like fabritone for 1.16 are really useful but also use @ so it prevents the IRC from working, ik fabritone counts as other mods, but normal baritone isn't 1.16 yet...
(I really should have made this already, but was lazy)

**Comment by THEREALWWEFAN231** [comment]
I THINK someone else already created an issue on this, but I don't feel like finding it so we will keep this open.

**Comment by GaiaAlexf** [comment]
oh ok

**Comment by GaiaAlexf** [comment]
wait found it it's #640 I'll close this

**Comment by JohnShiozo** [comment]
ok
