### ISSUE TITLE
Blink while inventory is open and walk with inventory is enabled - Suggestion

### ISSUE THREAD

**Issue by GreatZardasht** [THEREALWWEFAN231/Inertia#668]
**Minecraft Version(s)**

Maybe all

**What is the suggestion**

Blink while inventory is open and walk with inventory is enabled

**Why would this feature be useful**

It might be possible to dupe like this

**Comment by Versimpeld** [comment]
I've tried something similar by catching and cancelling the sPacketCloseWindow, but it only creates ghost items; they dissappear when placed or inventory is re-opened.

**Comment by GreatZardasht** [comment]
There might be a way to make the ghost items real

**Comment by Paralusion** [comment]
this wont work for duping
