### ISSUE TITLE
1.12.2 Forge Hostiles aren't affected by ESP and kill aura

### ISSUE THREAD

**Issue by Godeps2891** [THEREALWWEFAN231/Inertia#672]
**Inertia Utility Mod version:** 3.1.2
**Minecraft version:** 1.12.2 
(Forge Version:  14.23.5.2854)
**Operating system:** Windows 10 2004
**Optifine/Other mods:**  None

**What's the issue:** ~~read the title lmao~~ Hostile mobs currently don't get targeted by kill aura and aren't displayed by ESP even if the modules are set to. ESP and Aura still function normally for everything else eg. attacking or adding ESP to passive mobs, players etc.

**Comment by THEREALWWEFAN231** [comment]
Hostile mobs show as passive*.

**Comment by THEREALWWEFAN231** [comment]
Allows happens in 1.16.2,
Kill Aura
if Players, Animals and mobs are selected, it will not target players.

**Comment by THEREALWWEFAN231** [comment]
I *think/hope* this is fixed in 3.1.3(next update).
