### ISSUE TITLE
Flight bypass

### ISSUE THREAD

**Issue by AnimeFreak0710** [THEREALWWEFAN231/Inertia#675]
**Minecraft Version(s)**
all (?)
**What is the suggestion**
add an auto toggle to the flight module which turns it off for x ms every x seconds(sliders for setting times). This will allow a bypass on minecraft's default "flying is not enabled on this server" kick
**Why would this feature be useful**
this will prevent getting kicked for flying automatically instead of having to manually toggle the module every couple of seconds

**Comment by Paralusion** [comment]
already suggested
