### ISSUE TITLE
Flight Bypass Setting

### ISSUE THREAD

**Issue by ThePickinator** [THEREALWWEFAN231/Inertia#679]
Minecraft version: All versions.

Suggestion: Anti kick fly setting.

Reason: Fly doesn't bypass "flying is disabled on this server". It often kicks me within about 5-10 seconds of using flight on any speed.

**Comment by MLGgamingpro** [comment]
I would like to see this added. I've seen a *few* anarchy server without an anti-cheat.

**Comment by Paralusion** [comment]
duplicate of  #505: thanks @MLGgamingpro
