### ISSUE TITLE
New killaura setting

### ISSUE THREAD

**Issue by DoucheGab** [THEREALWWEFAN231/Inertia#681]
**Minecraft Version(s)**
1.12.2 to 1.16.2
**What is the suggestion**
Adding an option to the killaura settings that allows killaura to work while blocking with a shield
**Why would this feature be useful**
You can attack while blocking which is op against players that depends on melee combat on non anarchy servers

**Comment by MLGgamingpro** [comment]
In other clients i have used (Wurst in this example) on **your** screen it shows that you are attacking while blocking, but to the **server** you unblock for a tiny amount of time, during which you attack. This would be a useful feature to add to the killaura module.

**Comment by Paralusion** [comment]
merged with #116
