### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by therealOri** [THEREALWWEFAN231/Inertia#682]
**Minecraft Version(s)**
1.16+

**What is the suggestion**
Add Ancient Debris and nether gold ore to xray.

**Why would this feature be useful**
Pretty obvious how this would be useful. xD
To find the new ores easier!

**Comment by Silverwolf2332** [comment]
This is already a thing. 

.xray gui then add Ancient Debris and nether gold ore

**Comment by THEREALWWEFAN231** [comment]
This is already done by default in the next update, but do what @Silverwolf2332 said, to add different blocks.
