### ISSUE TITLE
ever since i updated to latest inertia, the mobs are extremely broken.

### ISSUE THREAD

**Issue by jewbob** [THEREALWWEFAN231/Inertia#683]
inertia latest. forge 1.12.2
killaura on mode hostiles, dosent attack any hostiles, but when i turn it to passives, it attacks them. also when i turn on esp, every hostile mob is rendered green as a passive mob.
![Screenshot_34](https://user-images.githubusercontent.com/69072843/90617438-97a3d880-e206-11ea-8803-3bd8fce02957.png)

![Screenshot_35](https://user-images.githubusercontent.com/69072843/90617507-aa1e1200-e206-11ea-9f2b-6a037eb367c1.png)

![Screenshot_36](https://user-images.githubusercontent.com/69072843/90617528-af7b5c80-e206-11ea-825c-3773545706ab.png)
edit= when i set killaura to passives, they get hit

edit 2= downgraded to inertia 3.1 and killaura works fine with hostiles, so its just latest release.

**Comment by THEREALWWEFAN231** [comment]
I am aware, this is related to #672 but I wont close this as it has more information.

**Comment by Paralusion** [comment]
fixed
