### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ijustsawabug** [THEREALWWEFAN231/Inertia#689]
**Inertia Utility Mod version:** 1.12.2? idk the version of the hack
**Minecraft version:** 1.12.2
**Operating system:** windows
**Optifine/Other mods:** nope

**What's the issue:** when i launch the game the screen is completly black plz halp

**Crash-report(Would be very useful also please format):** no crash report

**Comment by THEREALWWEFAN231** [comment]
#686
