### ISSUE TITLE
[suggestion] Force Crawl

### ISSUE THREAD

**Issue by WaffleTraits** [THEREALWWEFAN231/Inertia#69]
**Minecraft Version**
1.14.x
**What is the suggestion**
Utility that allows player to forcefully go into the crawling state.
**Why it will be useful**
Could be used to crawl in 1x1 spaces easier without needing a trapdoor. Don't know if this is possible or not but it might be worth a try. Also issue #69 🦀🦀🦀

**Comment by THEREALWWEFAN231** [comment]
#951 
RIP 69.
