### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by datheia** [THEREALWWEFAN231/Inertia#695]
**Minecraft Version(s)**
1.12.2
**What is the suggestion**

Making .dupe being automated in a specified amount: 
Like `.dupe <slot> <how many times> <delay>`

**Why would this feature be useful**

So duping in some vanilla servers would be more easier; also would be more efficient. Duping it to the stacks may be a pain, also may cost alot of time. So we just could automate it, to just get tons of items duped.

**Comment by 0x150** [comment]
the fuck was the purpose of this

**Comment by 0x150** [comment]
you know we can see the edit history right
