### ISSUE TITLE
Bug : Elytra doesn't work with Anti Hunger

### ISSUE THREAD

**Issue by markeno6** [THEREALWWEFAN231/Inertia#696]
**Inertia Utility Mod version: 1.12.2 forge ** 
**Minecraft version: 1.12.2 ** 
**Operating system: Windows 64-bit ** 
**Optifine/Other mods: Only Inertia** 

**What's the issue: Elytra doesn't work with Anti Hunger** 

**Crash-report(Would be very useful also please format):**

**Comment by AutistEren** [comment]
i think its meant to do that. not a bug

**Comment by THEREALWWEFAN231** [comment]
^.
