### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by pipipear** [THEREALWWEFAN231/Inertia#699]
**Inertia Utility Mod version:** 3.1.1
**Minecraft version:** 1.16.1
**Operating system:** Kubuntu 20.04
**Optifine/Other mods:** optifine

**What's the issue:** Trying to enable IRC gives the following error `[IRC] Disconnected from the IRC. Reason "java.lang.IndexOutOfBoundsException: readerIndex(21) + length(1) exceeds writerIndex(21): PooledUnsafeDirectByteBuf(ridx: 21, widx: 21, cap: 21)"`

**Comment by THEREALWWEFAN231** [comment]
You are using 3.1.1, irc only allows 3.1.2 users.
