### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HyperAzur** [THEREALWWEFAN231/Inertia#70]
**Minecraft Version**
          1.14.3

**What is the suggestion** 
Remove wwe accents from client. Like wwe button from homescreen and login/name from multiplayer screen.
Ingame add a panic button to suspend all keybindings.
Add a turn off all modules.

**Why it will be useful** 
**Proving innocence.**

**Comment by Paralusion** [comment]
duplicate of #270
