### ISSUE TITLE
Fullbright not turning off.

### ISSUE THREAD

**Issue by SirEarlybird** [THEREALWWEFAN231/Inertia#702]
**Inertia Utility Mod version:** 3.1.2
**Minecraft version:** 1.16.1 (on a aternos server without any anticheat)
**Operating system:** Windows
**Optifine/Other mods:** None

**What's the issue:** 
The fullbright hack is broken, it does not turn off. Even after relogging/relaunching the game. Furthermore, I have gone onto another (non-aternos) server, and the bug persists. I have tried to clear effects (for the potion version of the hack), and have set my brightness to the lowest setting. I have yet to see whether this bug occurs in singleplayer. 
**Crash-report(Would be very useful also please format):** N/A

**Comment by THEREALWWEFAN231** [comment]
Inertia is not a hack nor does it contain hacks, its a utility mod, which contains modules, as it seems, you already noticed how to fix this, you go to options, video settings, turn brightness down then back up. This isn't *really* a bug, and wont be fixed

**Comment by SirEarlybird** [comment]
Ok, I see your point about the nature of this mod. Also thank you for helping me with this!
