### ISSUE TITLE
Please make Inertia open source

### ISSUE THREAD

**Issue by game-been** [THEREALWWEFAN231/Inertia#707]
**Minecraft Version(s)**
All
**What is the suggestion**
Please make Inertia open source
**Why would this feature be useful**
You give away Inertia for free. You accept suggestions and bug reports via github why don't you open source. Just releasing the source would give you utility mod way more credibility. We would know for a fact there is no back door.  Any one could request to commit to the project and allow additions to Inertia you never could not do your own. It would fix the biggest issue with mods, when they get abandoned. Releasing the source in its entirety deobfuscated would allow anybody for fork your mod. It would allow people to fix major issues without you needing to spend the 6 hours scratching your head staring at your code and a long incomplete stack trace.
My question is why you haven't already. If you like the money from donations just keep inertia updated and people will continue  to donate. If you don't comment your code it dose not matter anybody with enough skill in java can read through even the most messy of code. If your variable names are named with little relation to what they do, so what we can see where they go to. If your scared people will take what you build up all you have to do is make sure you do Inertia best and people will favor the original.  
I am a advocate of open source. If everybody open sourced there programs the state of software would be 10 years ahead. If you were making your own utility mod you would not have to reinvent the wheal every time you could simply look at 6 other utility mods and mix n match until you made the ULTIMATE mod. I have made many server plugins on my spigot account and each have been open source. They are not that popular BUT i made something that others can use to see how they could make something similar, it could help them learn and improve. If open sourced or just released the Obfuscation map as minecraft had done them self. It would allow for a new generation of mods. Mods controlled by the community and not just one creator.

**Comment by THEREALWWEFAN231** [comment]
Inertia will not be open source. ill read your paragraph later.

**Comment by THEREALWWEFAN231** [comment]
Firstly, i think inertia has a lot of credibility and arguing that wont get anywhere, we get plenty of downloads and new users everyday, more then most/all open source clients. Also we are not open source for a couple reasons, firstly ill be able to sell it some day, that wont happen if its open source. Also look at kami, its a literal shi* hole, skids/forks and skids/forks  and skids/forks, non stop, people selling these crappy skids as well. I'm not afraid of the source quality, its quite good in my opinion(i would actually say very good, but i wouldn't go too far), everything is formatted how i like it, names are relevant, sometimes too specific to the point they are 20+ letters long.

Also i am/was already working on a the "biggest issue for mods", i am already working on an API which allows users to create their own modules, commands, and some other stuff, and eventually more, its mainly planned for 3.2(of course you cant edit stuff like kill aura but you could make your own). This solves both my problems, i could still sell the source if i wanted to. And inertia doesn't get skidded.

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
> Also look at kami, its a literal shi* hole, skids/forks and skids/forks and skids/forks, non stop, people selling these crappy skids as well. 
Missed a chance to mention the fact that there's a kamiautoskidder that can be used to automatically skid kami. I aM vErY dIsApPoInTeD y0u f@il3d to menti0n this.

**Comment by rockyTKNsxdvibes** [comment]
guys just make the damn thing open source

**Comment by rockyTKNsxdvibes** [comment]
ppl will probably get the client more bc they will know it is safe

**Comment by feliscatusmeows** [comment]
He literally just said that people already know we are safe. You can verify this as the inertia client does not connect to its central servers if irc is turned off. You can also verify that irc is safe because it's cleartext.
