### ISSUE TITLE
Anti afk

### ISSUE THREAD

**Issue by grotefigi** [THEREALWWEFAN231/Inertia#709]
The auto fish is very good,one of the best i've ever used but the client doesn't have a anti afk function so i keep getting kicked because im afk,can you guys please add anti afk?

**Comment by grotefigi** [comment]
the Aristois has a good anti afk if you want an example

**Comment by MLGgamingpro** [comment]
if you want an anti-afk, *while* fishing, i doubt that will work, add an anti-afk would be a nice feature. Also tag your posts correctly.

**Comment by Paralusion** [comment]
#11
