### ISSUE TITLE
AirJump

### ISSUE THREAD

**Issue by Beanthief** [THEREALWWEFAN231/Inertia#710]
**Minecraft Version(s)**
1.16.2+
**What is the suggestion**
Add an airjump or doublejump feature.
**Why would this feature be useful**
It would make traversing vertical terrain easier in survival mode. I can also use it to debug my anticheat better.

**Comment by MLGgamingpro** [comment]
I think this would be a nice-to-have, i wouldn't see much point in it though, unless the server has no anti-cheat, also i don't think it should be for **only** 1.16.2+ i think its should be for 1.12.2+.

**Comment by GaiaAlexf** [comment]
both #691 and #612 already have this, #612 being the first

**Comment by Paralusion** [comment]
duplicate of  #88
