### ISSUE TITLE
Fast Bow

### ISSUE THREAD

**Issue by Cypphi** [THEREALWWEFAN231/Inertia#715]
**Minecraft Version(s)** 1.12.2 - 1.16.2

**What is the suggestion** Add fast bow

**Why would this feature be useful** You could add fast bow since it's a really useful hack, if you make bow release "Fast bow" you can make a setting to change it to packet, which is just a machine gun, or to fast release which is like normal bow useage.

**Comment by MLGgamingpro** [comment]
Inertia is not a "Hacked Client" nor does it contain "Hacks" it is a utility mod. Fast bow only works in 1.8, to my knowledge and since its patched there is no point, all* anti-cheats patch it and there are essentially no anarchy servers on 1.8, if you want a faster bow, use Timer.

**Comment by THEREALWWEFAN231** [comment]
^ 90% sure what @MLGgamingpro said is true, I'm pretty sure it was "patched" by mojang in 1.9+.
