### ISSUE TITLE
Freecam Fly

### ISSUE THREAD

**Issue by TellTheL** [THEREALWWEFAN231/Inertia#722]
Version: Any

Suggestion: When you use Freecam while flying, you float and don't get kicked

Why: Because I used Freecam on servers that don't allow flight and somehow ended up floating. Maybe you can use this to make a working fly hack

**Comment by TheRedHippo** [comment]
The way that freecam works is by preventing any movement packets being sent to the server, which is why you'll just float midair. I believe that **packet fly** utilises this as well. So your 'freecam fly' already exists.

**Comment by THEREALWWEFAN231** [comment]
Freecam does no send packets to the server, meaning on some anticheats they allow you to float till you send your next movement packet, so lets say you wanted to fly using this(you would send a movement packet and the anticheat would kick you or set you on the ground), and no packet fly is different.
