### ISSUE TITLE
Ignore chests near mob spawners portal ruins, and underwater structures

### ISSUE THREAD

**Issue by TellTheL** [THEREALWWEFAN231/Inertia#723]
Version: Any

Suggestion: An option under ESP that doesn't render naturally generated chests, and maybe even a option for distance from the structure, or maybe a different colour for chests by spawners, portal ruins, and underwater structures.

Why: When your looking for a base, you don't want to be distracted by structures. You want to find bases, so it would be nice to have an option like this.

**Comment by THEREALWWEFAN231** [comment]
I'm not going to add this, for one there is not exact way to detect if the chest was generated by a spammer or a ruin, so the client would have to guess if it's a monument. What someone could do then is create a fake monument and put 2 chests and fill it up. Of course they could do this in the first place all well. 

Also, "When your looking for a base, you don't want to be distracted by structures. You want to find bases, so it would be nice to have an option like this." If you're looking for a base I would use Block Logger, it's much better then this idea, basically it ignores small amount of blocks, in this case x(2) chests, Block Logger is just much better for base hunting.
