### ISSUE TITLE
NoPotion

### ISSUE THREAD

**Issue by Cypphi** [THEREALWWEFAN231/Inertia#724]
**Minecraft Version(s)** any

**What is the suggestion** Add NoPotion (a module to delete specific potions from showing up, or working on you, yes I know, you can't remove stuff like poision, but maybe make a way to bypass slowness?)

**Why would this feature be useful**
It would be nice to be able to walk at normal speed even when you have slowness on you. It could be nice in a lot of different ways too. If that's not a good idea maybe add an option to NoSlow to bypass slowness?

**Comment by GaiaAlexf** [comment]
blindness prevents you from sprinting and with no-overlay on it would be nice to sprint with blindness
(oh god I can't English today)

**Comment by Cypphi** [comment]
> 
> 
> blindness prevents you from sprinting and with no-overlay on it would be nice to sprint with blindness
> (oh god I can't English today)

Oh damn, I thought I couldn't walk because of slowness, on the server I play there are custom enchants and I thought the slowness effects prevented me from walking but as it turn out it's Inertia...

**Comment by GaiaAlexf** [comment]
it's not inertia it's just vanilla minecraft that stops you from sprinting with blindness

**Comment by Cypphi** [comment]
> 
> 
> it's not inertia it's just vanilla minecraft that stops you from sprinting with blindness

Oh what, that's strange because somehow I can't even walk normally, I'm just stuck at my place, so I would like to see something like slowness bypass anyways.

**Comment by GaiaAlexf** [comment]
if you're stuck in place that's probably the server

**Comment by Cypphi** [comment]
> 
> 
> if you're stuck in place that's probably the server

it's not, im the owner and I bypass anticheat or anything else

**Comment by GaiaAlexf** [comment]
does it do it in singleplayer?
idk then tho I'm sure it's not inertia

**Comment by Cypphi** [comment]
> 
> 
> does it do it in singleplayer?
> idk then tho I'm sure it's not inertia

Hmm, I'll test that later, im not home rn

**Comment by Paralusion** [comment]
merged with #1028

**Comment by Paralusion** [comment]
probably better to close this one and just add nofog instead: #404
