### ISSUE TITLE
Incompatible with Sodium (main menu rendering error)

### ISSUE THREAD

**Issue by Lemoliam** [THEREALWWEFAN231/Inertia#726]
**Inertia Utility Mod version:** 3.1.2
**Minecraft version:** 1.16.2
**Operating system:** Windows 10
**Optifine/Other mods:** Sodium

**What's the issue:** Incompatible with Sodium (mod which boosts your fps very well). After the loading screen it stucks on main menu and just after 2-3 seconds game crashes 

**Crash-report:** https://pastebin.com/N992rM0n

**Comment by Qdessix** [comment]
As far as official versions for Sodium go, there isn't one for 1.16.2. You are maybe using inertia 1.16.2 and Sodium 1.16.1. Sodium with 1.16.1 works great. And now i use the unofficial Sodium build for 1.16.2 with 3 or 4 other mods to boost fps and they all work flawlessly.

**Comment by Lemoliam** [comment]
I'm using Sodium 1.16.2 0.1.0 snapshot from its github. If it were 1.16.1, the game just wouldn't start, in my case it starts and crashes on main menu

**Comment by Qdessix** [comment]
Try this  https://mega.nz/file/apQyRCbR#CZyT-kQai_BnVEYBRWi32givAInZqv-0WQ7N1CJZ8n8

**Comment by Lemoliam** [comment]
It actually worked, thank you!
