### ISSUE TITLE
named mob exclusion option in kill aura

### ISSUE THREAD

**Issue by GaiaB0t** [THEREALWWEFAN231/Inertia#729]
**Minecraft Version(s)**
all
**What is the suggestion**
add an option to either target named mobs specifically or to avoid hitting named mobs
**Why would this feature be useful**
I keep killing my zombie powering my iron farm and I use nametags to keep it from despawning, also things like killer rabbits would be targeted as the anarchy server I play on has a lot of killer rabbits which do a lot of damage,
I would hope that when targeting named mobs it would ignore whether it's a hostile mob or "peaceful" mob

**Comment by Paralusion** [comment]
would be fixed with #27
