### ISSUE TITLE
Flight Glide Mode

### ISSUE THREAD

**Issue by Cypphi** [THEREALWWEFAN231/Inertia#735]
**Minecraft Version(s)** any

**What is the suggestion** Add glide mode to flight

**Why would this feature be useful** This allows us to fly using this mode, you could make it so you can change how fast you go down, this could be used to bypass some crappy anticheats on towny servers or just anywhere since static and vanilla don't work with almost every anticheat...

**Comment by THEREALWWEFAN231** [comment]
Added in the next major update, but I highly doubt it will help "bypass" any crappy anticheat, I was just going to add a Down Speed option to mode Static(its literally the same thing), but decided I would just add mode Glide with that option instead, for less confusion.

**Comment by Paralusion** [comment]
@THEREALWWEFAN231 you could also add a "Damage" mode, which inflicts some damage onto the player which surprisingly bypasses lots of anticheats.
