### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Lempity** [THEREALWWEFAN231/Inertia#740]
**Inertia Utility Mod version:** 
**Minecraft version:** 
**Operating system:** 
**Optifine/Other mods:** 

**What's the issue: I lost the "search option in the click GUI"** 

**Crash-report(Would be very useful also please format):**
![search not working](https://user-images.githubusercontent.com/71273838/93243931-89d26c00-f74e-11ea-989e-591c83d4e47d.png)

**Comment by GaiaAlexf** [comment]
all you need to do is do ".gui reset"
and then re order them to how you want

**Comment by THEREALWWEFAN231** [comment]
.guireset search
