### ISSUE TITLE
Better Step module

### ISSUE THREAD

**Issue by DustRRaven** [THEREALWWEFAN231/Inertia#745]
**Minecraft Version(s)**
1.16.3
**What is the suggestion**
Better Step module
**Why would this feature be useful**
Because the Step module only allows you to cross a block, it would be good to be able to modify the maximum amount of block that you can cross

**Comment by AutistEren** [comment]
You should be able to set it with .value but putting more will most likely lag you back

**Comment by MLGgamingpro** [comment]
Most vanilla server are fine w/ high step values, some servers (with a bad anti-cheat) allow 3block step sometimes. The "Delay" mode already bypasses NCP (and its flagless as far as I know). But I think being able to set it to extreme values would be useful (maybe 10/20 max).
