### ISSUE TITLE
Bug with Freecam + Autowalk/Baritone

### ISSUE THREAD

**Issue by MESSIOS** [THEREALWWEFAN231/Inertia#748]
**Inertia Utility Mod version: Inertia Client 3.1.3** 
**Minecraft version: 1.12.2** 
**Operating system:WN10** 
**Optifine/Other mods:** 

**What's the issue:** While walking with Baritone the freecam is unuseable because it moves around and just behaves unnormal

**Comment by AutistEren** [comment]
Already a known issue
Most likely wont be fixed

**Comment by Paralusion** [comment]
"fixed" in prebuilds
