### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ppmaster69** [THEREALWWEFAN231/Inertia#751]
**Minecraft Version(s)**
1.16.1 and above
**What is the suggestion**
avoids taking damege from swords by spam typing .clip v 1 
**Why would this feature be useful**
would be easiar to use in fights if it was automated

**Comment by MLGgamingpro** [comment]
This is essentially TP-Aura, which has already been suggested (#363 #703 #637 #504)

**Comment by Paralusion** [comment]
merged with #637
