### ISSUE TITLE
BOT CONSTRUCTOR AND BOT MINER

### ISSUE THREAD

**Issue by Ral721chanel** [THEREALWWEFAN231/Inertia#757]
That they put in a bot so that it can create automated constructions, that can make houses etc and that it can be configured. Also that they put a bot that mines minerals by itself, that the valley goes directly for the minerals, and that can dodge the lava and kill the mobs

**Comment by AutistEren** [comment]
already a thing
use baritone + kill aura + auto tools

**Comment by Ral721chanel** [comment]
I do not understand you

**Comment by AutistEren** [comment]
look up how to use baritone

**Comment by Paralusion** [comment]
this is baritone.
