### ISSUE TITLE
Killaura + shield no longer works

### ISSUE THREAD

**Issue by Ral721chanel** [THEREALWWEFAN231/Inertia#758]
In the previous version of the client you could use the killaura and the shield at the same time and it would be like a "god mode". But I tried it in this new version but it no longer works, and that was key to pvp that they can't hurt you and you do. I hope that in the next version they will put this again

**Comment by THEREALWWEFAN231** [comment]
Turn Kill Aura Eatting(yes its misspelt/:) to Ignore instead of stop or what ever its on. It will ignore your Shield/Eating when using Kill Aura.
