### ISSUE TITLE
FORCE OP

### ISSUE THREAD

**Issue by Ral721chanel** [THEREALWWEFAN231/Inertia#759]
Put a force op to hack non-premium passwords. In short, it would be a password brute force attack, in short, it is trying password by password until it is found. But that a text of words by default comes with the client, but that you can also put a personalized one. And that the attack is very fast, because if it is done very slowly it could take days, even weeks. In short, when testing passwords that test 5 per second or 10, to make it faster, and once found to stop the attack. This would be very cool for the client to have it for non-premium anarchic servers

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
This client is a utility client and is not a hacked client used for hacking. This client will not attempt to hack into someone's account for you.

**Comment by AutistEren** [comment]
^ that
**_IF_** this was a hacked client i still doubt it would be added

**Comment by Ral721chanel** [comment]
I know that it is not a client to hack, you do not lose anything by putting it, in my opinion people would like it a lot. Besides that there are very few clients that have force op, and most are paid.

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
It would be illegal to distribute hacking tools. wwefan does not want to get in trouble with mojang. If you really want to break minecraft tos just use wurst's forceop.

**Comment by Ral721chanel** [comment]
In the first place, if it worked for me, wurst would use it, but when I downloaded it and everything did not appear in the versions. And the second is not illegal force op, since they are third-party servers that do not belong to mojang, and you can do whatever you want. If it had been illegal because the grifers did not go to prison or had no legal problems? Besides that there are many brute force tools for example for facebook, instagram etc. And the creator had no legal problems

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
wwefan does not support cracked versions of minecraft anyways. also wwefan does not support hacking, this is a utility mod for normal anachary servers. Even if it's unlikley to get caught, wwefan does not want to risk it.
