### ISSUE TITLE
Word wrap instead of character wrap

### ISSUE THREAD

**Issue by ShayBox** [THEREALWWEFAN231/Inertia#766]
I've never seen words be split by wrapping, usually if a word is too long you move the entire word to the next line, it's very jarring when trying to read menus like the initial menu.

**Comment by MLGgamingpro** [comment]
Can you please post a screen shot on where you encountered this?

**Comment by THEREALWWEFAN231** [comment]
I know what he's talking about, and I agree with him.

**Comment by THEREALWWEFAN231** [comment]
Changed in the newest prebuild/next update.
