### ISSUE TITLE
Suggestion x-ray fabric api

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/Inertia#77]
**Minecraft Version**
all Fabric versions
**What is the suggestion**
Add a message in chat (client-sidely), saying if x-ray does not work, try to remove the Fabric API.jar in your mods folder
**Why it will be useful**
people will understand why x ray doesnt work

**Comment by THEREALWWEFAN231** [comment]
Yeah, i am trying to make it override fabric api(well not right now but have looked into it)

**Comment by matthewsf619** [comment]
How do I find Fabric API.jar. i went into the mods folder nothing is there

**Comment by Paralusion** [comment]
added and works in latest release
