### ISSUE TITLE
Hit animations + 1.7/1.8 animations

### ISSUE THREAD

**Issue by Cypphi** [THEREALWWEFAN231/Inertia#772]
**Minecraft Version(s)** All

**What is the suggestion** Add a module to modify what hitting looks like, maybe even a simple way to sort of modify how it looks. Maybe also add 1.7/1.8 animations like being able to "hit" blocks while eating. And a module to hide your shield when wielding a sword to make it look like you're sword blocking.

**Why would this feature be useful** those would be a couple of fun features to add. They're just some visuals for the nostalgic people...

**Comment by Paralusion** [comment]
merged with #784
