### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ConnorLosted** [THEREALWWEFAN231/Inertia#775]
Minecraft version: *1.16.3* 
Operating system: *windows 10* 
Optifine/Other mods: *fabric, sodium* 

What's the issue: *well im nont sure if this a bug but, the xray dont detect the acient debris (block with which I can make netherita) this block generate in the nether and the xray dont detect it, i try add the block but the client say mi this not a block?
and i am in the minecraft version 1.16.3*

**Comment by Godeps2891** [comment]
".xray gui" in chat, select a**n**cient debris from there

**Comment by THEREALWWEFAN231** [comment]
What @Godeps2891 said is the way to make xray show netherite or what ever its called.
