### ISSUE TITLE
It don`t works for me

### ISSUE THREAD

**Issue by AngelinoVinz** [THEREALWWEFAN231/Inertia#778]
**Inertia Utility Mod version: Inertia 3.1.3

**Minecraft version: 1.16.3

**Operating system: Windows 8

**Optifine/Other mods: Just Optifine

**What's the issue: Everything works ok, but Xray dont works, it works like FullBright, and dont`s show`s the ores

**Crash-report(Would be very useful also please format):There its no crash

Sorry for my english im from Argentina

**Comment by THEREALWWEFAN231** [comment]
OptiFine causes that, remove it when you want to use Xray, this might be fixed sometime, its just really a pain, we have fixed it twice then OptiFine decides to change their code again and make our fixes not work.

**Comment by THEREALWWEFAN231** [comment]
You could also use Block ESP instead, if you really want to use OptiFine.

**Comment by AngelinoVinz** [comment]
> You could also use Block ESP instead, if you really want to use OptiFine.

LoL i have a shit of pc, so

**Comment by Godeps2891** [comment]
even more reason to ditch optifine and use sodium then

**Comment by THEREALWWEFAN231** [comment]
But you didn't try it 🤔

**Comment by AngelinoVinz** [comment]
Thanks <3
<3<3<3<33<3<3<<3<3<3<33<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<<3<3<3
<3<3<3<33<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<<3<3<3<3<3<3<3<3<3<3
<3<3<3<33<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<<3<3<3<3<3<3<3<3<3<3
<3<3<3<33<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<<3<3<3<3<3<3<3<3<3<3
<3<3<3<33<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<<3<3<3<3<3<3<3<3<3<3
<3<3<3<33<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<<3<3<3<3<3<3<3<3<3<3

**Comment by GaiaB0t** [comment]
please don't spam...
but sodium breaks another large feature of inertia... baritone

**Comment by AngelinoVinz** [comment]
But wait, no other way to fix?

**Comment by GaiaB0t** [comment]
nope

**Comment by AngelinoVinz** [comment]
What its "sodium"?

**Comment by Godeps2891** [comment]
https://www.curseforge.com/minecraft/mc-mods/sodium

performance mod, 99% of the time outperforming optifine but no fancy vanity features, like GaiaB0t said it breaks baritone though

**Comment by AngelinoVinz** [comment]
Im new in inertia

**Comment by GaiaB0t** [comment]
it's a choice between x-ray and baritone, tho most would rather have xray

**Comment by AngelinoVinz** [comment]
I have to put Sodium in "mods" folder huh?

**Comment by GaiaB0t** [comment]
ye

**Comment by Godeps2891** [comment]
yes, it's a mod like any other, keep in mind it's not compatible with optifine so you'll have to remove that

**Comment by AngelinoVinz** [comment]
sodium its like optifine :D?

**Comment by AngelinoVinz** [comment]
ok, i will try it

**Comment by GaiaB0t** [comment]
both sodium and optifine are performance mods, but optifine has more features and is less focused on direct performance than sodium

**Comment by Godeps2891** [comment]
like said, sodium is only focused on performance, there are more mods to reimplement optifine features though https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by AngelinoVinz** [comment]
Wow


I thinked i know everything of mc mods but this, is new

**Comment by GaiaB0t** [comment]
you probably know hardly anything if you didn't know things like that

**Comment by GaiaB0t** [comment]
and unless you have memorized all modpacks to ever exist and such you certainly don't know everything

**Comment by AngelinoVinz** [comment]
im a noob then

**Comment by GaiaB0t** [comment]
btw it is impossible for any one person to know everything lol...

**Comment by AngelinoVinz** [comment]
Hey, you have Discord?

**Comment by AngelinoVinz** [comment]
I think you are very friendly ^^****

**Comment by Godeps2891** [comment]
https://discord.gg/nCPa4k

**Comment by AngelinoVinz** [comment]
thanks!
