### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by clickym** [THEREALWWEFAN231/Inertia#782]
**Minecraft Version(s)** 
1.8+
**What is the suggestion**
The ability to see slime chunks.
**Why would this feature be useful**
Don’t have the seed and too lazy to find one legitimately? Why not create a render feature that shows where they are?

**Comment by THEREALWWEFAN231** [comment]
Because you need the seed to find them, the server doesn't tell the client what chunks are slime chunks. Not possible.
