### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bobydon1** [THEREALWWEFAN231/Inertia#783]
**Minecraft Version(s)**
1.16.3
**What is the suggestion**
to get a dupe working for 1.6.3
**Why would this feature be useful**
because it would make it so much easier to dupe if it was added to the client on 1.16.3

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
That's not how this works, there is currently no known way to dupe in 1.16.3. 1.6.3 might be possible but we don't support 1.6.3.

**Comment by E404NNF** [comment]
1.6.3 has no working dupe iirc, might have to look around forums from that era about it
