### ISSUE TITLE
Typing Error on main website

### ISSUE THREAD

**Issue by ColdIcyy** [THEREALWWEFAN231/Inertia#787]
**Inertia Utility Mod version:** None
**Minecraft version:** None
**Operating system:** None
**Optifine/Other mods:** None

**What's the issue:** Website Miss-spelling

**Crash-report(Would be very useful also please format):** None.

Haven't tried it out yet, just found this while downloading.
![inertia](https://user-images.githubusercontent.com/72895828/96056218-f5921c80-0e53-11eb-92a8-192a2dee175d.png)

**Comment by THEREALWWEFAN231** [comment]
I mean its not miss-spelt, more miss-worded? I'm not sure if I'm going to "fix" that, its getting removed when the next update is released.

**Comment by TheRedHippo** [comment]
"dowload" is the mispelling, but I guess it could be reworded too.

**Comment by THEREALWWEFAN231** [comment]
Ohh lol, doesn't matter anymore, I "removed" that screen.

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
Go to sleep now pls.
