### ISSUE TITLE
X-ray not working with Optifabric & Optifine

### ISSUE THREAD

**Issue by TheRealistik** [THEREALWWEFAN231/Inertia#794]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.3
**Operating system:** Linux
**Optifine/Other mods:** Optifabric, Optifine

**What's the issue:** X-ray completely does not work with Optifabric and Optifine.

**Crash-report(Would be very useful also please format):**

**Comment by Silverwolf2332** [comment]
This is caused from optifine. this isn't a bug with inertia. and optifine wont fix it. if you want x-ray but and performance increase use sodium instead. and don't complain about inertia not working properly when using other mods
