### ISSUE TITLE
inertia not running in 32 bit windows Bug

### ISSUE THREAD

**Issue by wurstisgood** [THEREALWWEFAN231/Inertia#798]
**Inertia Utility Mod version:** 
**Minecraft version:** 
**Operating system:** 
**Optifine/Other mods:** 

**What's the issue:** 

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Well you would have to give more detail, I don't have any 32 bit system to test it on.

**Comment by wurstisgood** [comment]
> Well you would have to give more detail, I don't have any 32 bit system to test it on.

windows 7,32 bit,        when i run it ,it says "**inertia client 3.1.3(not responding)**" and then closes

**Comment by wurstisgood** [comment]
> Well you would have to give more detail, I don't have any 32 bit system to test it on.

but it works on my mac but that is not with me right now so i tried to use in this computer

**Comment by AutistEren** [comment]
I got a 32bit Windows 10 Laptop. I can run 1.16.3 and 1.12.2 fine.

**Comment by wurstisgood** [comment]
> I got a 32bit Windows 10 Laptop. I can run 1.16.3 and 1.12.2 fine.

then maybe it not works for windows 7

**Comment by wurstisgood** [comment]
> I got a 32bit Windows 10 Laptop. I can run 1.16.3 and 1.12.2 fine.

you run inertia 3.1.3 or older version?

**Comment by dexterfoxy** [comment]
@wurstisgood Provide logs and then we can talk.

**Comment by AutistEren** [comment]
> > I got a 32bit Windows 10 Laptop. I can run 1.16.3 and 1.12.2 fine.
> 
> you run inertia 3.1.3 or older version?

3.1.3

**Comment by wurstisgood** [comment]
> @wurstisgood Provide logs and then we can talk.

logs means?

**Comment by GaiaB0t** [comment]
crash logs I think

**Comment by GaiaB0t** [comment]
well, crash logs, or the .latest in .minecraft / logs

**Comment by wurstisgood** [comment]
[Uploading latest.log…]()

**Comment by wurstisgood** [comment]
i have uploaded logs 

> @wurstisgood Provide logs and then we can talk.



> well, crash logs, or the .latest in .minecraft / logs

**Comment by wurstisgood** [comment]
[latest.log](https://github.com/THEREALWWEFAN231/Inertia/files/5414112/latest.log)

**Comment by wurstisgood** [comment]
> Well you would have to give more detail, I don't have any 32 bit system to test it on.

i have uploaded logs please check it @THEREALWWEFAN231

**Comment by THEREALWWEFAN231** [comment]
I'm going to need more information on this, It's been 2 months 😳 Feel free to reopen this.
