### ISSUE TITLE
FastUse Hack

### ISSUE THREAD

**Issue by Discusser** [THEREALWWEFAN231/Inertia#8]
**Minecraft Version**
every version?
**What is the suggestion**
Allows you to use items quickly, e.g: spam xp, bow spam, etc..
**Why it will be useful**
XP Spam is useful when you're fighting with breakable armor, Bow Spam is useful when you're fighting in general and have a lot of harming arrows, FastUse also has other utilities but these are the main ones

**Comment by mememasterlord32345** [comment]
This can be done with fast place.

**Comment by THEREALWWEFAN231** [comment]
He wants bow spam though, i think ill add an option to fast place called bow spam, and place

**Comment by Zernaie** [comment]
Yeah @THEREALWWEFAN231 you should rename the cheat to fast interact and put fast place, fast bow, and fast use options.

**Comment by Paralusion** [comment]
yes, rename the module

**Comment by feliscatusmeows** [comment]
issue should be closed now, modules called fast bow release and fast place. also there is an autoclicker.

**Comment by THEREALWWEFAN231** [comment]
XP Spam, just use Fast Place, with only XP bottles, if you want that, and there is Fast Bow Release module.
