### ISSUE TITLE
Stash Finder

### ISSUE THREAD

**Issue by Zenot1cc** [THEREALWWEFAN231/Inertia#800]
**Minecraft Version(s)**

**What is the suggestion**

**Why would this feature be useful**
Similar to how Salhack did it, but simpler to understand, it creates waypoints in a circle around your current position, and flies to said waypoints in a circle, once all the Waypoints have been met, the waypoints are moved further away and it is repeated until stopped. Also, a stash Logger could be useful for stash hunting. Not many clients have these

Base hunting made easy, and among other things

**Comment by THEREALWWEFAN231** [comment]
Firstly Inertia already has a Stash Logger, its called Block Logger and we are not adding something that automatically files around.
