### ISSUE TITLE
sneak walk? Suggestion

### ISSUE THREAD

**Issue by wurstisgood** [THEREALWWEFAN231/Inertia#801]
**Minecraft Version(s)** as you wish

**What is the suggestion** Automatically sneaks at block edge

**Why would this feature be useful** To build bridges faster(like ninja bridge) without scaffoldwalk(due to anticheat)

**Comment by Godeps2891** [comment]
there's already the safewalk module which prevents you from going down blocks

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
If you want to use this to not look suspicious when bridging, forget about it, inertia is a mod for servers that allow it. We do not condone using this mod where it isn't allowed.

**Comment by THEREALWWEFAN231** [comment]
As @Godeps2891 said the Safe Walk module does what you want.
