### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rojoesqueimados** [THEREALWWEFAN231/Inertia#803]
**Minecraft 1.16.3**

**Mount Bypass**

**Duping and just travel as well**

**Comment by GaiaB0t** [comment]
I think there is something to bypass the lack of saddles? tho I doubt it'll be added for duping

**Comment by rojoesqueimados** [comment]
I don't think there is, i've search and found no module that does that

**Comment by GaiaB0t** [comment]
is "entity ride" (I had to look it up lol" not at least part of what you want?

**Comment by GaiaB0t** [comment]
it's under the movement tab in the click gui

**Comment by rojoesqueimados** [comment]
I dont have it whaaat
