### ISSUE TITLE
Maps Preview Isn't Working

### ISSUE THREAD

**Issue by flufl** [THEREALWWEFAN231/Inertia#810]
Inertia Utility Mod version: 3.1.3
Minecraft version: 1.16.3
Operating system: Win10
Optifine/Other mods: None

What's the issue: Doesn't preview maps when using peek, only shulkers.

**Comment by THEREALWWEFAN231** [comment]
Make sure Maps option is on, and If it still doesn't work, You have to manually take the map out and hold it in your hand(to get the server to send the client the map).
