### ISSUE TITLE
Sorting option for inventorys

### ISSUE THREAD

**Issue by Z3r0ut** [THEREALWWEFAN231/Inertia#819]
All versions

Please add a feature to sort inventorys (Player, chests) for example with middleclick
Cause i didnt find any Inventory sorter for fabric.

Of course for me it would work the otherway around too, make Inertia forge compatible, but i know thats not going to happen any time soon. xD

An Sorter feature is always usefull. I dont know why there isnt already a fabric mod for it.

**Comment by Godeps2891** [comment]
https://www.curseforge.com/minecraft/mc-mods/inventory-sorting
https://www.curseforge.com/minecraft/mc-mods/inventory-profiles
https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie

**Comment by Z3r0ut** [comment]
I found the first one, and it is Server side, so not usefull.
But i didnt find the other two. Thank you. So i close this thread then.
