### ISSUE TITLE
Anti kick and bypass

### ISSUE THREAD

**Issue by Ral721chanel** [THEREALWWEFAN231/Inertia#824]
Put a function on the fly so that when you use it, the minecraft server will not kick you.
Because in most of the servers in general and anarchic when using the fly for a long time they kick you. And the message "Fly is not avaible on this server" appears. But it is allowed.
And create a fly / speed bypass for the 2b2t and l2x9 servers.

**Comment by AutistEren** [comment]
vanilla fly kick has been suggested a lot so i think its already on wwefan's to do list
and if fly speed bypass for anarchy servers are not easy, they can even take months

**Comment by Ral721chanel** [comment]
Ok
