### ISSUE TITLE
long jump and air jump.

### ISSUE THREAD

**Issue by Missing-entity** [THEREALWWEFAN231/Inertia#825]
add a long jump and air jump. both fun and can bypass some anti che*ts.

**Comment by MLGgamingpro** [comment]
Please follow the format.
Longjump would be helpful and definitely should be in Inertia air-jump is a duplicate of #639 #612 and #88. I highly doubt air-jump this could bypass any anti-cheats though.

**Comment by Paralusion** [comment]
thanks @MLGgamingpro : duplicate of #88
