### ISSUE TITLE
Speed hacks

### ISSUE THREAD

**Issue by ghost** [THEREALWWEFAN231/Inertia#83]
Hello, WWE doesnt allow me to use any other hacked clients speed. I use impacts speed hack onground but sadly it doesn't work when im using wwe. Another suggestion would be to add the Onground Speed hack that future has because it is almost flawless

**Comment by Acedropthebase** [comment]
btw this is on forge 1.12.2

**Comment by Paralusion** [comment]
mixin issue, we are aware
