### ISSUE TITLE
Deprecate/remove inertia 1.13

### ISSUE THREAD

**Issue by I-can-have-a-long-username-if-I-want-to** [THEREALWWEFAN231/Inertia#832]
**Minecraft Version(s)**
1.13
**What is the suggestion**
Stop updating 1.13. 
**Why would this feature be useful**
1.13 is the most painful version to update and barely anybody uses it so pls deprecate it. It's bullied you for too long. Break Free.

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
Is 1.13 holding you at gunpoint and forcing you to do this?

**Comment by MLGgamingpro** [comment]
honestly 1.13 is just a flex

**Comment by E404NNF** [comment]
> honestly 1.13 is just a flex

If your pc runs 1.13/1.14 that's a flex.

**Comment by Doogie13** [comment]
surely 1.13/4 is useless anyways as there arent many mods for 1.13/4 that would run with inertia that arent on 1.16. viaversion would mean that the versions are literally useless

**Comment by E404NNF** [comment]
> surely 1.13/4 is useless anyways as there arent many mods for 1.13/4 that would run with inertia that arent on 1.16. viaversion would mean that the versions are literally useless

There should only be a 1.12.2 and 1.16.3(4?) versions only

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
1.13 doesn't support other mods. there should only be a 1.12 and a 1.16. mabye a 1.15 if wwefan feels like it but 1.13 is just painful.
