### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Bwise2game** [THEREALWWEFAN231/Inertia#834]
All

Thad you can use Freecam when walking or mining with Baritone.

Because then when you are traveling you can go in to free cam and find chests or dupe places.

**Comment by Z3r0ut** [comment]
Yeah would be nice. Cause when i use a utility client Free cam, it doesnt work anymore. (To say that, the #come feature that is especialy for freecams, doesnt work with freecam.. xD)

**Comment by feliscatusmeows** [comment]
wwefan please? also make killaura work properly in freecam too pleas.

**Comment by TheRedHippo** [comment]
close

**Comment by Paralusion** [comment]
in current prebuilds
