### ISSUE TITLE
Compatability issue with Sodium

### ISSUE THREAD

**Issue by DannyParker0001** [THEREALWWEFAN231/Inertia#835]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:**  1.16.3
**Operating system:** Windows
**Optifine/Other mods:** Sodium

**What's the issue:** 
Fabritone wont move with sodium, this was fixed [2 months ago](https://gitlab.com/CDAGaming/fabritone/-/issues/16)
Please update fabritone <3

**Comment by THEREALWWEFAN231** [comment]
We don't use Fabritone 😉 😳. We use baritone even on the Fabric versions.

**Comment by DannyParker0001** [comment]
😳 Then its a sodium/phosphor/lithium compatibility issue

**Comment by DannyParker0001** [comment]
Ah ok this is a duplicate of #802, [the fabritone patch](https://gitlab.com/CDAGaming/fabritone/-/issues/16#note_392151419) looked simple, I hope its not too much work for what you guys have.
