### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PeppoNetwork** [THEREALWWEFAN231/Inertia#837]
---
name: Bug report
about: Create a report to help us improve
title: Bug
labels: bug
assignees: ''
---

**Inertia Utility Mod version:** 
Latest 
**Minecraft version:** 
1.12.2
**Operating system:** 
Windows 8 Latest version, Type x64 BITS
**Optifine/Other mods:** 
Optifine,Gamesense Client 2.2.0
**What's the issue:** 
Whenever i load inertia my minecraft window is black
**Crash-report(Would be very useful also please format):** I don't got one

**Comment by PeppoNetwork** [comment]
May i get a older version of inertia? That would probally fix the issues

**Comment by AutistEren** [comment]
that happens a lot with 1.12 i think
wait for 3.2 update

**Comment by PeppoNetwork** [comment]
Alrigt

**Comment by Paralusion** [comment]
duplicate of #618
