### ISSUE TITLE
[suggestion] Client-Side Spectator Mode

### ISSUE THREAD

**Issue by WaffleTraits** [THEREALWWEFAN231/Inertia#84]
**Minecraft Version**
Any
**What is the suggestion**
Have a utility that makes the user's gamemode spectator (client side of course)
**Why it will be useful**
Could potentially be useful for something like freecamming or some other use.

**Comment by Paralusion** [comment]
an actual client-side spectator mode wouldn't do a lot, especially not with an entity cheat. 
to change your gamemode client-sidely for experimenting could be cool though, i'd suggest a .gamemode command
a Spectator mode option to Freecam could be added, but it'd be quite a few lines of code

**Comment by SylveonBottle** [comment]
Why add this because it's "something like freecam" when we already have freecam? What's the purpose of using this rather than freecam?

**Comment by Paralusion** [comment]
@SylveonBottle is right: use freecam instead.
