### ISSUE TITLE
Add portals to esp

### ISSUE THREAD

**Issue by I-can-have-a-long-username-if-I-want-to** [THEREALWWEFAN231/Inertia#840]
**Minecraft Version(s)**
all
**What is the suggestion**
add nether portals esp as a module under esp
**Why would this feature be useful**
we need to ~~skid~~ borrow features from other clients. Also blockesp portals just isn't the same.

**Comment by THEREALWWEFAN231** [comment]
This is not happening, Block ESP portals works 100% fine.
