### ISSUE TITLE
Suggestion: .taco

### ISSUE THREAD

**Issue by Godeps2891** [THEREALWWEFAN231/Inertia#845]
**Minecraft Version(s)** All

**What is the suggestion** Add .taco

**Why would this feature be useful** Haha i love this little guy 
![771079695844376596](https://user-images.githubusercontent.com/54289108/98080648-0abc0300-1e76-11eb-848c-68d4bd1b2731.gif)

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
do it now

**Comment by JohnShiozo** [comment]
> Approved

**Comment by E404NNF** [comment]
Also add nyan cat taco from LB please

**Comment by feliscatusmeows** [comment]
.taco

**Comment by AutistEren** [comment]
i love dancing kebab more

**Comment by feliscatusmeows** [comment]
Yay is there .taco

**Comment by Godeps2891** [comment]
![98080648-0abc0300-1e76-11eb-848c-68d4bd1b2731](https://user-images.githubusercontent.com/54289108/105622522-93fa2a80-5e12-11eb-9a1b-5ad4b973afb6.gif)
