### ISSUE TITLE
Make website open source so that the inconsistent grammar can be fixed 

### ISSUE THREAD

**Issue by I-can-have-a-long-username-if-I-want-to** [THEREALWWEFAN231/Inertia#847]
**Version(s)**
HTML5
**What is the suggestion**
Make the inertia client website licensed under an open source license so people can legally modify it and send the updated versions to you.
**Why would this feature be useful**
An invasion of Grammar Nazis is imminent. Please do this to prevent the invasion.

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
Example:
![image](https://user-images.githubusercontent.com/29553771/98208163-b6eeff80-1ef1-11eb-8fd8-8a886da042a7.png)
"Alot" is not an English word.

**Comment by THEREALWWEFAN231** [comment]
Bruh lol, that's not happening firstly the whole website is "basically php", secondly there is confidential information in the source files, also don't worry about the website 😉

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
Suggestion 2: make a new place to put all website suggestions.
