### ISSUE TITLE
Notebot discriminates against note blocks that are almost, but not quite out of reach. 

### ISSUE THREAD

**Issue by feliscatusmeows** [THEREALWWEFAN231/Inertia#848]
**Inertia Utility Mod version:** 
idk
**Minecraft version:** 
idk
**Operating system:** 
probbably hannah montana linux idfk
**Optifine/Other mods:** 
i doubt
**What's the issue:** 
![image](https://user-images.githubusercontent.com/29553771/98210214-0d117200-1ef5-11eb-94fa-896e89ba4b98.png)
i made this so u not forget
**Crash-report(Would be very useful also please format):**
911: 911 whats ur emengercey?
victim: help somebody crashed into me with their car and ran away
victim: now im bleeding on the shoulder of the highwa-
911: thats illegul they can't crash into u like that

**Comment by Godeps2891** [comment]
comparison video, even blocks that can be hit in survival without reach are not recognized by note bot

https://www.youtube.com/watch?v=aUuhtHBmm28

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
Adding a reach slider might help if on a server with terrible/vanilla anticheat.

**Comment by THEREALWWEFAN231** [comment]
Ok, so from my understanding @Godeps2891 just wanted Note Bot Per Song to detect 1 block higher, which is what I did in the next prebuild/3.2.

**Comment by feliscatusmeows** [comment]
yay
.taco
