### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by Xetter2000** [THEREALWWEFAN231/Inertia#851]
**Inertia Utility Mod version: 3.1.3** 
**Minecraft version: 1.12.2** 
**Operating system: Windows** 
**Optifine/Other mods: None** 

**What's the issue: I am using the Forge 1.12.2 version. Everything boots up alright but when Forge is done loading it just shows a black screen.  
![image](https://user-images.githubusercontent.com/64616678/98291819-98741d00-1f60-11eb-8b55-f03cad3ebf50.png)
** 

**Crash-report(Would be very useful also please format): there is no crash report. there is just a black screen that I can't do anything about.**

**Comment by GaiaB0t** [comment]
this is a known issue, only fix until 3.2 is using other versions

**Comment by Xetter2000** [comment]
Oh! okay
