### ISSUE TITLE
Auto crystal and aurabed

### ISSUE THREAD

**Issue by Ral721chanel** [THEREALWWEFAN231/Inertia#853]
Put a glass car so that you can automatically put crystals in a pvp. And put a bedaura igaul than the crystal aura because sometimes exploding beds in the nether or end in pvp is better

**Comment by AutistEren** [comment]
i dont know what glass car is but enable "toxic" for beds

**Comment by Ral721chanel** [comment]
> i dont know what glass car is but enable "toxic" for beds

Sorry, the translator translated it wrong, I mean the autocrystal. Put a function to be able to put crystals automatically in the pvp. Other clients have this function but inertia does not

**Comment by AutistEren** [comment]
its called crystal aura

**Comment by Ral721chanel** [comment]
> its called crystal aura

The crystalaura only hits automatically it does not put crystals automatically

**Comment by AutistEren** [comment]
have u enabled "place" in crystal aura settings

**Comment by Ral721chanel** [comment]
Yes

dum., 8 nov. 2020, 14:36 AutistEren <notifications@github.com> a scris:

**Comment by AutistEren** [comment]
have u set y difference to 0
