### ISSUE TITLE
What is the file format/type needed to import alts?

### ISSUE THREAD

**Issue by Kopamed** [THEREALWWEFAN231/Inertia#854]
Can anyone give me an example file and how its supposed to look?

**Comment by AutistEren** [comment]
no, they are encrypted by HID the only way is adding them 1 by 1 or using the altening api

**Comment by E404NNF** [comment]
> no, they are encrypted by HID the only way is adding them 1 by 1 or using the altening api

What if... He decrypted it and then added his alts and encrypt it again?

**Comment by THEREALWWEFAN231** [comment]
When you import alts its like
email:password
email:password

**Comment by feliscatusmeows** [comment]
holy heck that's insecure wtf
