### ISSUE TITLE
Backfilling when nothing is turned on

### ISSUE THREAD

**Issue by sukulent** [THEREALWWEFAN231/Inertia#863]
**Inertia Utility Mod version:** "Inertia Client 3.1.3 - 1.16.4.jar"
**Minecraft version:** 1.16.4
**Operating system:** Linux Debian Buster
**Optifine/Other mods:** Only fabric api, nothing else.

**What's the issue:** 

When mining some blocks like dirt or cobblestone, even when everything is turned off, the blocks are placed back. It looks like backfilling.

tested on fabric 0.9.3 , 0.10.5 and 0.10.6

**Comment by AutistEren** [comment]
im kinda confused, can u show us a video

**Comment by Godeps2891** [comment]
i assume it's like this https://www.youtube.com/watch?v=Y8su6ytD0iU

**Comment by AutistEren** [comment]
oh thats weird
what happens when you place it
if you cant what happens if you /clear @p dirt

**Comment by sukulent** [comment]
Here I have a video I just recorded.

https://youtu.be/EuHXFZ151g8

**Comment by AutistEren** [comment]
yea something is definitely wrong with urs
delete .minecraft/Inertia and if its still happens its not inertias problem

**Comment by sukulent** [comment]
I did deleted Inertia folder a few times and nothing helped. I might try to delete the .minecraft folder.

**Comment by sukulent** [comment]
Ok so I did fix this issue.

Before installing Inertia I have tried standalone baritone and his settings caused this behavior. I think this should be noted somewhere. Deleting all folders named "baritone" fixed it. (one in .minecraft and one in each world)

Thanks for help.

**Comment by sukulent** [comment]
Ok, it is still happening. When you have allowbackfill set to true, it backfills blocks even when baritone is not active. Obvious workaround is to turn of allowbackfill when not using baritone. It's a bug isn't it?

**Comment by THEREALWWEFAN231** [comment]
That would be a baritone bug not an Inertia bug. 🤷‍♂️
