### ISSUE TITLE
Baritone doesn't work on servers in Inertia Fabric 1.16.4

### ISSUE THREAD

**Issue by IronBoi62** [THEREALWWEFAN231/Inertia#865]
I have tried everything to see what the problem is. and nothing.

**Comment by THEREALWWEFAN231** [comment]
It does work I tested it before I released Inertia 1.16.4, .b goto 0 0 works. You are probably using sodium or some mod that doesn't work with baritone.

**Comment by AutistEren** [comment]
delete sodium and next time follow the format
