### ISSUE TITLE
Noclip

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/Inertia#870]
**Minecraft Version(s)**
All
**What is the suggestion**
Add NoClip
**Why would this feature be useful**
I know I've suggested this multiple times by now, but it's a good feature and should be easy enough to add.

**Comment by feliscatusmeows** [comment]
I'm afraid I will have to disagree, it is incredibly hard to make a working noclip because the minecraft server on vanilla does an incredible job preventing clipping into blocks.

**Comment by CZHO404** [comment]
I do agree and even if it does get added it's one of the easiest things to patch, I have never come across a still working one that hasn't existed for more than a month.

**Comment by Paralusion** [comment]
duplicate of #433
