### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CZHO404** [THEREALWWEFAN231/Inertia#874]
**Minecraft Version(s)**
Any
**What is the suggestion**
Bedbomb
**Why would this feature be useful**
This feature would make the PVP hacks in inertia way better and make it a way better utility mod for anarchy servers like 2b2t.

**Comment by GaiaB0t** [comment]
I'm pretty sure wwefan is already working on this, along with potentially an anchor bomb for 1.16+

**Comment by CZHO404** [comment]
That's good just didn't see a ticket for it, hope this gets added soon.

**Comment by GaiaB0t** [comment]
I _think_ it'll be in 3.2, but don't count on that

**Comment by THEREALWWEFAN231** [comment]
"Bed Bomb" is already a feature in Inertia, Toxic does what you want, places and uses bed near players in the nether, and @GaiaB0t is correctly, anchor will probably also be added to Toxic so one can use them to blow people up as well, because what's more fun then blowing people up in a block game.

**Comment by GaiaB0t** [comment]
oh sorry I had forgotten bed bomb was already a thing

**Comment by CZHO404** [comment]
Same on my part, I was just thinking of some of the Phobos features and didn't stop to think that it was in toxic cause I didn't see it in the pvp tab.
