### ISSUE TITLE
Bug: Shulker texture is cut off when using peek

### ISSUE THREAD

**Issue by Godeps2891** [THEREALWWEFAN231/Inertia#876]
**Inertia Utility Mod version:** Pre 11/07/20 02:35 PM 😎
**Minecraft version:** All (tested 1.12 and 1.16)
**Operating system:** Wind10
**Optifine/Other mods:** None

**What's the issue:** the bottom row of pixels isn't displayed when hovering over shulker boxes
![image](https://user-images.githubusercontent.com/54289108/99187605-e60a3a00-2757-11eb-95eb-bfa875408f69.png)
are you seeing my character? it's in pain from looking at this

**Comment by THEREALWWEFAN231** [comment]
It actually isn't cut off, 
![image](https://user-images.githubusercontent.com/21975901/99191210-133af600-2720-11eb-8687-4a680f9c83f0.png) I don't know how I feel above rendering the bottom part of the texture at the bottom.

**Comment by THEREALWWEFAN231** [comment]
😡 🖕 
You already know this is added in the next prebuild/3.2.
