### ISSUE TITLE
esp update suggestion

### ISSUE THREAD

**Issue by DeadAlice5094** [THEREALWWEFAN231/Inertia#879]
**Minecraft Version(s)**
1.16.4~1.16.3

 Item esp

Can't just display certain items?

**Comment by THEREALWWEFAN231** [comment]
*This is a really picky suggestion...*

**Comment by enderson0** [comment]
It is theoretically possible as there is an NBT tag pertaining to specific items. In vanilla 
@e[type=minecraft:item,nbt={id:"ITEM HERE"}]
is a selector for individual items and could theoretically be used for ESP.

**Comment by THEREALWWEFAN231** [comment]
I never said it was impossible, I just said it's quite picky.

**Comment by Paralusion** [comment]
duplicate of #349
