### ISSUE TITLE
Title screen

### ISSUE THREAD

**Issue by svxl** [THEREALWWEFAN231/Inertia#881]
**Inertia Utility Mod version:** 1.12.2 forge
**Minecraft version:**  1.12.2
**Operating system:**  windows
**Optifine/Other mods:** salhack, optifine

**What's the issue:** whenever i launch it, the title screen is just black. and i cant click on anything

**Crash-report(Would be very useful also please format):** doesnt crash

**Comment by GaiaB0t** [comment]
that's a known inertia 1.12 bug I think fixed in 3.2

**Comment by GaiaB0t** [comment]
no solution other than other versions, so rip your salh mod

**Comment by Paralusion** [comment]
duplicate of #618
