### ISSUE TITLE
Auto Armor Ignores Netherite

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#891]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.4

**What's the issue:** Getting netherite armor after wearing diamond armor doesnt replace the diamond armor

*this bug doesnt happen with other armors so it kinda thinks like netherite=diamond*

**Comment by feliscatusmeows** [comment]
revenge of the sad diamond man

**Comment by THEREALWWEFAN231** [comment]
This is added in the next prebuild/3.2, and bruh @feliscatusmeows is everywhere.

**Comment by feliscatusmeows** [comment]
I feel pinged :(
