### ISSUE TITLE
Auto Eat "Prefer Gapples" Does Nothing

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#892]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.4

**What's the issue:** "prefer gapples" in auto eat doesn't do anything and "use gapples" does the job so i think best option is to just remove "prefer gapples"

**Comment by THEREALWWEFAN231** [comment]
It does do something, use gapples will use gapples and food, when you have prefer gapples, it will eat the gapples before other food(IE steak). I honestly don't know why you would want to do that, but it's there.
