### ISSUE TITLE
Auto Tool Doesn't Select the Best Enchantment

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#893]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.4

**What's the issue:** Auto Tool scans from slot 1 to slot 9 so if you have a better pickaxe in your slot 2 and a worse pickaxe on slot 1, it will use the worse pickaxe.

If you have have a better pickaxe on slot 1 and a worse one on slot 2, it will still use the pickaxe on slot 1.

**Comment by THEREALWWEFAN231** [comment]
Added in the next prebuild/3.2.
