### ISSUE TITLE
Inventory Manager

### ISSUE THREAD

**Issue by WannaCry1LoL** [THEREALWWEFAN231/Inertia#897]
Make an Inv manager that drops useless stuff+a setting where you can select what is considered useless

**Comment by AutistEren** [comment]
already a thing, inventory cleaner

**Comment by WannaCry1LoL** [comment]
> already a thing, inventory cleaner
Inventory cleaner drops your whole inv

**Comment by AutistEren** [comment]
it seems u didnt configure it
change it to mode:keep and type .inventorycleaner add itemyouwanttokeep

**Comment by WannaCry1LoL** [comment]
bruh sorry
