### ISSUE TITLE
Suggestion: Boat fly/Elytra+ goto

### ISSUE THREAD

**Issue by ppmaster69** [THEREALWWEFAN231/Inertia#898]
**Minecraft Version(s)** all

**What is the suggestion**add a command similar to baritones @goto <coordinates> and it walks for you but make it compatible with elytra+ mod and boat fly mod 

**Why would this feature be useful**would help people afk for far locations and be able to do other stuff

**Comment by THEREALWWEFAN231** [comment]
This isn't going to be added into Inertia, That's more of a suggestion for baritone.

**Comment by feliscatusmeows** [comment]
baritone has a todo list and this is unforunately at the bottom of it beacause they want to add entity riding and stuff first.
