### ISSUE TITLE
OnGround Speed Hack

### ISSUE THREAD

**Issue by Discusser** [THEREALWWEFAN231/Inertia#9]
**Minecraft Version**
every version
**What is the suggestion**
A speed hack type that's called OnGround, is faster than NCP and Bhop.
**Why it will be useful**
Let's you go up to around 20m/s, if it bypasses 2b2t (like future), you're basically fast as fuck. Now of course, you can't keep onGround on for a lot of time or else you'll get caught by the anticheat.

**Comment by Paralusion** [comment]
There's a reason why other clients don't have this: it's not public and no one knows how to recreate it.

**Comment by Paralusion** [comment]
this can be closed

**Comment by Godeps2891** [comment]
> this can be closed
