### ISSUE TITLE
Unable to scroll in Click GUI when Scroll Sensitivity is low

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#904]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** All
**Operating system:** Windows 10
**Optifine/Other mods:** N/A

**What's the issue:** If you go to Options > Controls > Mouse Settings and lower the Scroll Sensitivity to below 1, you'll be unable to scroll upwards in the Click Gui.

**Comment by THEREALWWEFAN231** [comment]
Fixed in the next prebuild/3.2.

**Comment by feliscatusmeows** [comment]
wwefan do be gruesomely murdering bugs. RIP bugs.

**Comment by feliscatusmeows** [comment]
Wait, I just realized the time. @THEREALWWEFAN231 GO TO SLEEP NOW.
