### ISSUE TITLE
Tamed module

### ISSUE THREAD

**Issue by CZHO404** [THEREALWWEFAN231/Inertia#906]
**Minecraft Version(s)**
1.8+
**What is the suggestion**
Add owner's nametag for tamed mobs
**Why would this feature be useful**
Useful for when exploring bases

**Comment by CZHO404** [comment]
This would be pretty easy to implement, all you have to do is check the entity data of a tameable mob and then check the UUID of the owner.

**Comment by THEREALWWEFAN231** [comment]
There is already .mobowner when you hover over a mob, Nametag is just extra unnecessary work.
