### ISSUE TITLE
Rotations Auto-Snap

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#909]
**What is the suggestion** Ex. I am looking at 35-65 when I turn on rotations It will automatically snap to 45. If I'm looking at -35-35 it will snap to 0 and so on.

**Why would this feature be useful** Saves A LOT OF time

**Comment by THEREALWWEFAN231** [comment]
Bruh what? You basically want it like Future/forgehe*ks? Where it snaps to the nearest cardinal direction? If so I'm not adding that 😳

**Comment by GaiaB0t** [comment]
darn

**Comment by feliscatusmeows** [comment]
please?

**Comment by AutistEren** [comment]
i meant that but i didnt know it was on cringe clients
BUT STILL I NEED THIS BADLY

**Comment by GaiaB0t** [comment]
yea it would be useful

**Comment by AutistEren** [comment]
i guess he wont add it 😔

**Comment by feliscatusmeows** [comment]
:(
