### ISSUE TITLE
Bug: Inertia 1.12 and 1.13 Jumble instruments from OpenNBS files

### ISSUE THREAD

**Issue by Godeps2891** [THEREALWWEFAN231/Inertia#912]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.12 1.13
**Operating system:** Win10
**Optifine/Other mods:** None

**What's the issue:** OpenNBS songs will use wrong instruments even if a song consists only of 1.12/1.13 compatible instruments

Same Songs in 1.12 then 1.16
![image](https://user-images.githubusercontent.com/54289108/100888443-6b128480-34b6-11eb-919e-4d88e6ba0f09.png)
![image](https://user-images.githubusercontent.com/54289108/100888471-72399280-34b6-11eb-81ea-f4a12b7d2be8.png)

![image](https://user-images.githubusercontent.com/54289108/100888549-89788000-34b6-11eb-9bfd-1c9106da9cff.png)
![image](https://user-images.githubusercontent.com/54289108/100888560-8e3d3400-34b6-11eb-84f8-4cef9ca13580.png)

**Comment by THEREALWWEFAN231** [comment]
Fixed in the next prebuild/3.2, I only noticed the bug in 1.12.2, not 1.13.2. 1.13.2 looks the same, as all the versions above.
