### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by baitpl1** [THEREALWWEFAN231/Inertia#914]
**Inertia Utility Mod version:** newest
**Minecraft version:** 1.12.2
**Operating system:** win 10
**Optifine/Other mods:** no

**What's the issue:** crashing game when loading mod inertia

**Crash-report(Would be very useful also please format):**
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (1293 ms)
[Version:1.12.2-Aristois] Resolving...
[Version:1.12.2-Aristois] Inherits from 1.12.2
[Version:1.14.2-forge-26.0.63] Resolving...
[Version:1.14.2-forge-26.0.63] Inherits from 1.14.2
[Version:1.15.2-Aristois] Resolving...
[Version:1.15.2-Aristois] Inherits from 1.15.2
[Version:1.15.2-OptiFine_HD_U_G1_pre30] Resolving...
[Version:1.15.2-OptiFine_HD_U_G1_pre30] Inherits from 1.15.2
[Version:1.16.1-Aristois] Resolving...
[Version:1.16.1-Aristois] Inherits from 1.16.1
[Version:1.16.1-OptiFine_HD_U_G2] Resolving...
[Version:1.16.1-OptiFine_HD_U_G2] Inherits from 1.16.1
[Version:1.16.2-Aristois] Resolving...
[Version:1.16.2-Aristois] Inherits from 1.16.2
[Version:1.16.2-OptiFine_HD_U_G3] Resolving...
[Version:1.16.2-OptiFine_HD_U_G3] Inherits from 1.16.2
[Version:1.16.3-Aristois] Resolving...
[Version:1.16.3-Aristois] Inherits from 1.16.3
[Version:1.16.3-OptiFine_HD_U_G3] Resolving...
[Version:1.16.3-OptiFine_HD_U_G3] Inherits from 1.16.3
[Version:1.8.9-forge1.8.9-11.15.1.1722] Resolving...
[Version:1.8.9-forge1.8.9-11.15.1.1722] Inherits from 1.8.9
[Version:fabric-loader-0.10.0+build.208-1.16.1] Resolving...
[Version:fabric-loader-0.10.0+build.208-1.16.1] Inherits from 1.16.1
[Version:fabric-loader-0.10.1+build.209-1.14] Resolving...
[Version:fabric-loader-0.10.1+build.209-1.14] Inherits from 1.14
[Version:fabric-loader-0.10.1+build.209-1.16.1] Resolving...
[Version:fabric-loader-0.10.1+build.209-1.16.1] Inherits from 1.16.1
[Version:fabric-loader-0.9.2+build.206-1.16.1] Resolving...
[Version:fabric-loader-0.9.2+build.206-1.16.1] Inherits from 1.16.1
[Version:1.12.2-Aristois] Resolving...
[Version:1.12.2-Aristois] Inherits from 1.12.2
[Version:1.14.2-forge-26.0.63] Resolving...
[Version:1.14.2-forge-26.0.63] Inherits from 1.14.2
[Version:1.15.2-Aristois] Resolving...
[Version:1.15.2-Aristois] Inherits from 1.15.2
[Version:1.15.2-OptiFine_HD_U_G1_pre30] Resolving...
[Version:1.15.2-OptiFine_HD_U_G1_pre30] Inherits from 1.15.2
[Version:1.16.1-Aristois] Resolving...
[Version:1.16.1-Aristois] Inherits from 1.16.1
[Version:1.16.1-OptiFine_HD_U_G2] Resolving...
[Version:1.16.1-OptiFine_HD_U_G2] Inherits from 1.16.1
[Version:1.16.2-Aristois] Resolving...
[Version:1.16.2-Aristois] Inherits from 1.16.2
[Version:1.16.2-OptiFine_HD_U_G3] Resolving...
[Version:1.16.2-OptiFine_HD_U_G3] Inherits from 1.16.2
[Version:1.16.3-Aristois] Resolving...
[Version:1.16.3-Aristois] Inherits from 1.16.3
[Version:1.16.3-OptiFine_HD_U_G3] Resolving...
[Version:1.16.3-OptiFine_HD_U_G3] Inherits from 1.16.3
[Version:1.8.9-forge1.8.9-11.15.1.1722] Resolving...
[Version:1.8.9-forge1.8.9-11.15.1.1722] Inherits from 1.8.9
[Version:fabric-loader-0.10.0+build.208-1.16.1] Resolving...
[Version:fabric-loader-0.10.0+build.208-1.16.1] Inherits from 1.16.1
[Version:fabric-loader-0.10.1+build.209-1.14] Resolving...
[Version:fabric-loader-0.10.1+build.209-1.14] Inherits from 1.14
[Version:fabric-loader-0.10.1+build.209-1.16.1] Resolving...
[Version:fabric-loader-0.10.1+build.209-1.16.1] Inherits from 1.16.1
[Version:fabric-loader-0.9.2+build.206-1.16.1] Resolving...
[Version:fabric-loader-0.9.2+build.206-1.16.1] Inherits from 1.16.1
[Version:1.12.2-Aristois] Resolving...
[Version:1.12.2-Aristois] Inherits from 1.12.2
[Version:1.14.2-forge-26.0.63] Resolving...
[Version:1.14.2-forge-26.0.63] Inherits from 1.14.2
[Version:1.15.2-Aristois] Resolving...
[Version:1.15.2-Aristois] Inherits from 1.15.2
[Version:1.15.2-OptiFine_HD_U_G1_pre30] Resolving...
[Version:1.15.2-OptiFine_HD_U_G1_pre30] Inherits from 1.15.2
[Version:1.16.1-Aristois] Resolving...
[Version:1.16.1-Aristois] Inherits from 1.16.1
[Version:1.16.1-OptiFine_HD_U_G2] Resolving...
[Version:1.16.1-OptiFine_HD_U_G2] Inherits from 1.16.1
[Version:1.16.2-Aristois] Resolving...
[Version:1.16.2-Aristois] Inherits from 1.16.2
[Version:1.16.2-OptiFine_HD_U_G3] Resolving...
[Version:1.16.2-OptiFine_HD_U_G3] Inherits from 1.16.2
[Version:1.16.3-Aristois] Resolving...
[Version:1.16.3-Aristois] Inherits from 1.16.3
[Version:1.16.3-OptiFine_HD_U_G3] Resolving...
[Version:1.16.3-OptiFine_HD_U_G3] Inherits from 1.16.3
[Version:1.8.9-forge1.8.9-11.15.1.1722] Resolving...
[Version:1.8.9-forge1.8.9-11.15.1.1722] Inherits from 1.8.9
[Version:fabric-loader-0.10.0+build.208-1.16.1] Resolving...
[Version:fabric-loader-0.10.0+build.208-1.16.1] Inherits from 1.16.1
[Version:fabric-loader-0.10.1+build.209-1.14] Resolving...
[Version:fabric-loader-0.10.1+build.209-1.14] Inherits from 1.14
[Version:fabric-loader-0.10.1+build.209-1.16.1] Resolving...
[Version:fabric-loader-0.10.1+build.209-1.16.1] Inherits from 1.16.1
[Version:fabric-loader-0.9.2+build.206-1.16.1] Resolving...
[Version:fabric-loader-0.9.2+build.206-1.16.1] Inherits from 1.16.1
[Launcher] Minecraft closed with exit code: -1
[Launcher] Launcher exited.

**Comment by feliscatusmeows** [comment]
Try again without using Aristois.

**Comment by Godeps2891** [comment]
wtf even is this log, please join the discord for support

**Comment by baitpl1** [comment]
aristois is not even in mod folder

**Comment by baitpl1** [comment]
all mods i have is only inertia rn

**Comment by Godeps2891** [comment]
like said please join the discord https://discord.gg/invite/ZyMKgSm

**Comment by feliscatusmeows** [comment]
Try deleting .minecraft/versions then reinstalling minecraft

**Comment by baitpl1** [comment]
i have  t launcher

**Comment by baitpl1** [comment]
not normal mc

**Comment by baitpl1** [comment]
im joined dsc

**Comment by feliscatusmeows** [comment]
Tlauncher is not suppourted. They modify the game. This bug report is invalid. Please use the official minecraft launcher or multimc.

**Comment by feliscatusmeows** [comment]
help how close issue
issue closer github 2020 no virus

**Comment by THEREALWWEFAN231** [comment]
You are using aristois, clearly, as said in the log thing you sent, install the fabric loader from https://fabricmc.net/use/ then load inertia, you are using the aritois profile to try loading inertia which is not working.
