### ISSUE TITLE
Inertia 1.15.2 doesn't open with fabric.

### ISSUE THREAD

**Issue by NASAWorker1** [THEREALWWEFAN231/Inertia#915]
Hello i have tried to open inertia 1.15.2 but it doesn't seem to be working for me. I tried using other versions and they worked perfectly. Is there a reason behind this?

**Comment by Godeps2891** [comment]
because wwefan is big dumb



downgrade your fabric loader version to 0.10.3 or below

**Comment by NASAWorker1** [comment]
Thanks! It worked.

**Comment by THEREALWWEFAN231** [comment]
Yes I was stupid and accidently released the 1.15.2 version incorrectly 😔.
