### ISSUE TITLE
Suggestion for Kill Aura 

### ISSUE THREAD

**Issue by SnakyExotic** [THEREALWWEFAN231/Inertia#918]
**Minecraft Version(s)**
1.16.4
**What is the suggestion**
Add a feature where kill aura can hit mobs/players/animals through a shield.
**Why would this feature be useful**
It would be useful so you can use it to kill other players while using a shield. (It works in auto clicker but there isn't a option to turn it off to look more legit.)

**Comment by THEREALWWEFAN231** [comment]
Use Eatting mode, turn it to ignore, to swing when using your Shield.
Yes Eatting is misspelt...
