### ISSUE TITLE
Auto Jump

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#919]
**What is the suggestion** Auto Walk but it jumps instead.

**Why would this feature be added**
- Easy to code
- Possible Anti AFK
- When farming mobs, it can crit hit them because on some servers criticals doesn't work.

**Comment by MLGgamingpro** [comment]
hold space 😎 ez bypass 2020
probably wouldn't be useful anyways 😩

**Comment by AutistEren** [comment]
*ahem* **AFK** mob farming

**Comment by MLGgamingpro** [comment]
put literally anything on your space bar, and there are probably programs that can do that anyways

**Comment by AutistEren** [comment]
but i do other stuff when im afk

**Comment by RocketNinja15** [comment]
pp

**Comment by Paralusion** [comment]
duplicate of #250
