### ISSUE TITLE
Orebfuscator

### ISSUE THREAD

**Issue by RocketNinja15** [THEREALWWEFAN231/Inertia#921]
**Minecraft Version(s)**
alll
**What is the suggestion**
It would bypass the orebfuscator plugin... like many other clients have
**Why would this feature be useful**
because anti-xray is bad....

**Comment by THEREALWWEFAN231** [comment]
"like many other clients have" tell me another client beside future that has it... 😳

**Comment by AutistEren** [comment]
fart client

**Comment by RocketNinja15** [comment]
Still... pls

________________________________

**Comment by RocketNinja15** [comment]
@THEREALWWEFAN231 still doe... its finenenee

**Comment by constantinDev** [comment]
I made a mod for that

**Comment by Paralusion** [comment]
duplicate of  #42
