### ISSUE TITLE
addition to autofishing

### ISSUE THREAD

**Issue by GaiaB0t** [THEREALWWEFAN231/Inertia#925]
**Minecraft Version(s)**
all, or at least 1.9-1.16+
**What is the suggestion**
allow offhand autofishing
**Why would this feature be useful**
because of the 1.16 changes to fishing, you pretty much need to be outside for it to work.
allowing offhand autofishing would allow ka to use a sword or other weapon to defend itself while the other hand has a fishing rod and is fishing
normal fishing works in offhand so it would make sense that autofishing also does

**Comment by GaiaB0t** [comment]
another possible thing would be to add the ability to change the recast timer, like if you have a lure 3 rod you don't need it to wait like a minute or whatever to recast

**Comment by THEREALWWEFAN231** [comment]
I made it so Auto Fish works with the fishing rod in your Offhand, I did not add the lure cast sync thing, I'm not too sure if I want that tbh, maybe I'll change my mind later, but for now I would just suggest turning the delay down when you are using lure.
