### ISSUE TITLE
an addition to autoeat

### ISSUE THREAD

**Issue by GaiaB0t** [THEREALWWEFAN231/Inertia#928]
**Minecraft Version(s)**
alk
**What is the suggestion**
add an actual functional switch back option to autoeat
**Why would this feature be useful**
I like to do overnight autofishing, and I need to be able to eat but still go back to fishing after I finish eating, so that I don't either eat and then never do back to fishing, or not eat and then get killed bc I don't regain health

**Comment by GaiaB0t** [comment]
also offhand eating, 
is there a way to tell it to NOT eat pufferfish? or not eat anything that would cause an infinite loop of eating

**Comment by Godeps2891** [comment]
go all the way and add .autoeat gui

**Comment by GaiaB0t** [comment]
maybe, I just really want it next prebuilds so I can actually do overnight autofishing, without autologging bc I ate pufferfish

**Comment by Paralusion** [comment]
merge with #125
