### ISSUE TITLE
Chat Bot Bug

### ISSUE THREAD

**Issue by DortyTheGreat** [THEREALWWEFAN231/Inertia#935]
**Inertia Utility Mod version:** 3.1.3 
**Minecraft version:** 1.16.4
**Operating system:** Windows 8.1
**Optifine/Other mods:** NONE

**What's the issue:** strange behaviour with CHAT BOT and its coding system
for example:
if i insert message like: ░█████╗░░█████╗░░█████╗░██╗░░██╗
in Chat Bot.json it will be represented as "???????????" (some amount of "?")
that so, it will spam only with "?????", 
but what is more interesting, is that if you first toggle the Chat Bot, and then add the
░█████╗░░█████╗░░█████╗░██╗░░██╗ message, it will be spamming properly
until you close the Chat Bot GUI.
After you close the GUI, the messages will be "????????"

Moreover, if i manually add this message into the file it will be converted ito something very
odd, something like ONE SYMBOL █  will be converted into THREE symbols, like 
[EURO] [STAR] [NUMBER SIX] or somewhat like this. 

The same kinda problem happens with auto-sign.

please fix that

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
File reading didn't work with unicode, this has already been change in 3.2(when it releases).

**Comment by czho** [comment]
3.2 hype
