### ISSUE TITLE
kill aura block.

### ISSUE THREAD

**Issue by Missing-entity** [THEREALWWEFAN231/Inertia#936]
all

kill aura works while blocking. 

i can't remember which client but there was one where kill aura would work while blocking. useful for obvious reasons.

**Comment by Godeps2891** [comment]
in the kill aura options set "eating" to ignore

**Comment by czho** [comment]
I did find a really good client with this but it was 1.8 so not applicable here.

**Comment by GaiaB0t** [comment]
shields didn't exist in 1.8....

**Comment by THEREALWWEFAN231** [comment]
As @Godeps2891 said, mess around with the "Eatting" mode, Ignore mode does what you want.
