### ISSUE TITLE
这是什么问题 使用快捷键x的时候提示这个

### ISSUE THREAD

**Issue by zengkuankuan** [THEREALWWEFAN231/Inertia#938]
![QQ图片20201209111854](https://user-images.githubusercontent.com/53440794/101569974-6dbe2e00-3a10-11eb-9eaf-be9db9c98fe2.png)
Mechanical translation can't tell

**Comment by feliscatusmeows** [comment]
dui bu qi wo mei you zhong wen shu ru fa. wo ye du bo dong zhong wen. ni ke yi yong ying wen ma?

**Comment by czho** [comment]
:( wish someone here spoke chinese

**Comment by feliscatusmeows** [comment]
I speak chinese, but im illiterate.

**Comment by feliscatusmeows** [comment]
good thing google translate is a thing
![image](https://user-images.githubusercontent.com/29553771/101570497-5c7f0e00-398b-11eb-9769-91fe6f41a20c.png)

**Comment by czho** [comment]
well I read the wrong thing and didnt see the other cause im on phone

**Comment by zengkuankuan** [comment]
> good thing google translate is a thing
> ![image](https://user-images.githubusercontent.com/29553771/101570497-5c7f0e00-398b-11eb-9769-91fe6f41a20c.png)

yes！所以要怎么解决这个问题呢！

**Comment by feliscatusmeows** [comment]
![image](https://user-images.githubusercontent.com/29553771/101570661-bda6e180-398b-11eb-9d05-04126891306e.png)

**Comment by czho** [comment]
I hope that works, it could also be optifabric

**Comment by feliscatusmeows** [comment]
![image](https://user-images.githubusercontent.com/29553771/101570799-fe9ef600-398b-11eb-87d1-6364de4a25e2.png)

**Comment by zengkuankuan** [comment]
如何忽略 按x就提示错误 更改快捷键？

**Comment by feliscatusmeows** [comment]
.bind remove xray

**Comment by feliscatusmeows** [comment]
I'm tempted to spam the incident that never happened on the thirty 1st of may on the year (44*44+53) but that seems a bit risky and bad.

**Comment by zengkuankuan** [comment]
现在是无法使用x透视功能了吗 完全关闭掉了

**Comment by feliscatusmeows** [comment]
Yes
to change it back do
.bind add xray x
为进一步支持 use VPN and go to https://discord.gg/ZyMKgSm

**Comment by zengkuankuan** [comment]
绑定快捷键后按x无反应 shift设置回来如主题一样了 论坛进不去不给注册使用了vpn也一样

**Comment by feliscatusmeows** [comment]
welp this person is fricked and stuck on their side of the great firewall of china :/
They say they can't join with vpn :/

**Comment by Paralusion** [comment]
issue not related to inertia: related to the great firewall of china
