### ISSUE TITLE
anchor module for cpvp

### ISSUE THREAD

**Issue by feliscatusmeows** [THEREALWWEFAN231/Inertia#939]
**Minecraft Version(s)**
all
**What is the suggestion**
add an anchor, which stops movment if you are jumping above a hole
**Why would this feature be useful**
This is an important feature for cpvp and helps getting into holes which makes the player take less damage and die less.

**Comment by snoopchallenge** [comment]
#922 incudes this and I think this would be good as even some kb from crystals could push you up if they break obby you are in

**Comment by Paralusion** [comment]
duplicate of #922 and already planned
