### ISSUE TITLE
Coordinates Bug

### ISSUE THREAD

**Issue by PixelGM** [THEREALWWEFAN231/Inertia#940]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.4 
**Operating system:** Windows 10
**Optifine/Other mods:** Baritone, litematica, malilib, optifabric, optifine, phospor fabric

**What's the issue:**
HUD showing overworld coordinates when in the nether or the end. 

**Crash-report(Would be very useful also please format):** No crash.

**Comment by czho** [comment]
Prob wanna give a screenshot or something.

**Comment by THEREALWWEFAN231** [comment]
This isn't a bug? In Hud you can turn Overworld Coords and or Nether Coords off, red is nether, white is overworld...
