### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Zenot1cc** [THEREALWWEFAN231/Inertia#941]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.4 
**Operating system:** Windows 10
**Optifine/Other mods:**  none, just fabric API

**What's the issue:** 
Crashes whenever starting the game
**Crash-report(Would be very useful also please format):**
[crash-2020-12-09_16.46.04-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5667395/crash-2020-12-09_16.46.04-client.txt)

**Comment by THEREALWWEFAN231** [comment]
I answered you on discord, but

Go to your .minecraft folder, Inertia, delete the universal folder.
