### ISSUE TITLE
Prebuilds: an edit to beacon boundaries 

### ISSUE THREAD

**Issue by GaiaB0t** [THEREALWWEFAN231/Inertia#943]
**Minecraft Version(s)**
all
**What is the suggestion**
add an opacity slider to the beacon boundaries
**Why would this feature be useful**
a quad beacon setup makes it a bit too intrusive to see anything with it on 
![image](https://user-images.githubusercontent.com/69175586/101864772-7191a380-3b29-11eb-8609-ee57a99c3c7d.png)

**Comment by GaiaB0t** [comment]
**PART 2:**
add modes such as a box mode
a thing to toggle whether it's filled or not
something to do with changing width of lines?
also depth is odd but idk what to do about it

**Comment by feliscatusmeows** [comment]
note: this has been censored in #github channel

**Comment by THEREALWWEFAN231** [comment]
Somewhat "added" in the next prebuild.
