### ISSUE TITLE
the client needs a way to turn off

### ISSUE THREAD

**Issue by aries773** [THEREALWWEFAN231/Inertia#944]
the client should have a setting in the minecraft menu to disable/enable it 
I like somethings in this client but most things are the same as the client I already  use 
but I would like to switch between the two for instance the other client I use has an on-off switch in the statistics  
so I would love if this client had something similar

**Comment by feliscatusmeows** [comment]
Why would you need that? You could just to .t all_off.

**Comment by constantinDev** [comment]
`.t all_off`

**Comment by Paralusion** [comment]
merged with #1148, a button to disable Inertia entirely

**Comment by Paralusion** [comment]
duplicate of #270
