### ISSUE TITLE
Crawl

### ISSUE THREAD

**Issue by enderson0** [THEREALWWEFAN231/Inertia#951]
Detects if the server is post 1.14, then starts crawling

Could be useful for blast mining i dont know but I cant find any other clients with crawl

**Comment by THEREALWWEFAN231** [comment]
So from my research(looking around in minecrafts 1.16 code) this is not possible, the client does not tell the server what pose the player is in(meaning we can't tell the server we are crawling). Each client calculates each players pose every so often(probably every tick I didn't look), and generally takes "no input from the server". Long story short this is not possible.

![image](https://user-images.githubusercontent.com/21975901/102835453-a1ec0400-43ab-11eb-9fa3-bff58bb190c8.png)

Also this is the answer to #69 rip issue 69

**Comment by feliscatusmeows** [comment]
:crying_cat_face:
