### ISSUE TITLE
Seed X-ray

### ISSUE THREAD

**Issue by Tylerkiller2345** [THEREALWWEFAN231/Inertia#953]
**Minecraft Version(s)**
All Versions
**What is the suggestion**
You can input the seed of a world and it will find ores.
**Why would this feature be useful**
This could be used to get around anti-xray

**Comment by feliscatusmeows** [comment]
This would be quite bad for your cpu, no?
also servers with anti xray probbably also scramble the ores anyways.

**Comment by THEREALWWEFAN231** [comment]
This will not be added, 
1. It would be a pain to make work across all versions, 1.12-1.16
2. Contrary to popular belief ores and some stuff are not 100% generated the same based on the seed, they can be scrambled sometimes, and completely different based on the direction the chunks were generated.
