### ISSUE TITLE
Re-add lyrics to notebot

### ISSUE THREAD

**Issue by snoopchallenge** [THEREALWWEFAN231/Inertia#958]
**Minecraft Version(s)** 
From what I can tell, all, although this used to be a feature

**What is the suggestion**
Re-add lyrics to notebot so it plays in chat while it plays the music

**Why would this feature be useful**
Would help make the song better (placebo) to other people and probably make less people attack you for playing notebot

**Comment by feliscatusmeows** [comment]
wwefan please add to inertia format
