### ISSUE TITLE
.bind clear

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#96]
**Minecraft Version**
all
**What is the suggestion**
Add `.bind clear` to get rid of all binds
**Why it will be useful**
I just had to spend like 6 minutes going through every single setting in the GUI just to look for and unbind the default binds. Would be fantastic if people never had to go through this like I did

**Comment by Paralusion** [comment]
you can do this manually by going into the WWE folder and removing the binds text file

**Comment by SylveonBottle** [comment]
Still would be good to have this as an actual in-game feature rather than having to modify files.

**Comment by Paralusion** [comment]
merged with #966
