### ISSUE TITLE
future bugs

### ISSUE THREAD

**Issue by chixin114514** [THEREALWWEFAN231/Inertia#962]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.12.2
**Operating system:** windows10
**Optifine/Other mods:** future optifine

**What's the issue:** I cant join any server when i use inertia and future

**Crash-report(Would be very useful also please format):**
![image](https://user-images.githubusercontent.com/76463422/102848378-a9fd7f80-444f-11eb-8470-0812335d2536.png)

**Comment by GaiaB0t** [comment]
you ain't getting any help here, that's an issue with future

**Comment by THEREALWWEFAN231** [comment]
We are not fixing this, you can't exactly blame Inertia

I was using Inertia and I added Future and this happened. Future needs to fix this issue!!! 😡 
I was using Future and I added Inertia and this happened. Inertia needs to fix this issue!!! 😡 

It's a conflict that we don't really care about fixing.
