### ISSUE TITLE
Functionality of the word "ALL" in commands

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#966]
**Minecraft Version(s)** All (heh)

**What is the suggestion** Right now we only have .t ALLOFF. But why can't we use this feature in similar commands? For example, being able to clear all binds by doing .bind remove all. 

**Why would this feature be useful**
Convenience, saves time, and I always see people complaining in the discord about having to manually reset binds.

**Comment by Paralusion** [comment]
merged with  #96
