### ISSUE TITLE
Suggestion: Food Farm

### ISSUE THREAD

**Issue by DatSkyr3x** [THEREALWWEFAN231/Inertia#978]
All versions

Needs flint n' steel + weapon to kill animals (preferably). When toggled, animals around you get lit on fire like with Toxic, fire gets extinguished and burning animal gets Killaura'd, allowing a quick way to gather cooked food.

This feature would be good for new players since gathering food always gets in the way of important things like getting ores

**Comment by TheRedHippo** [comment]
just add a subsetting for toxic which makes it automatically target animals
the rest can be done by just enabling KA

**Comment by DatSkyr3x** [comment]
having an extinguish option would be nice though since often times i get food in a forest and burning down all the wood i could still get is worse than just putting out the fire once you don't need it

**Comment by constantinDev** [comment]
These features are already in baritone, which comes with inertia.
