### ISSUE TITLE
Stop drawing Trajectories when it collides with an entity

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#982]
**Minecraft Version(s)** All

**What is the suggestion** Not have the line continue past entities that it passes through, just like how blocks stop it.

**Why would this feature be useful** I'd imagine it would look better and show what's happening more clearly. Adding a highlight to mobs that are in the trajectory could be an option as well.

**Comment by Paralusion** [comment]
merged with #548
