### ISSUE TITLE
GUI Editor

### ISSUE THREAD

**Issue by Cypphi** [THEREALWWEFAN231/Inertia#983]
**Minecraft Version(s)** All

**What is the suggestion** A gui editor

**Why would this feature be useful** A GUI editor will allow us to move modules anywhere we want and customize our client more. It will be really nice if we can change where specific stuff is located. It would also be useful when using 2 clients at the same time so you can prevent modules from overlapping.

**Comment by TheRedHippo** [comment]
#964

**Comment by THEREALWWEFAN231** [comment]
As @TheRedHippo said #964 and 😡 the whole reason it wasn't added yet is to stop people using more clients with inertia 😡

**Comment by feliscatusmeows** [comment]
inkamwursrusalhepgampacttreyroobos+2 premium
