### ISSUE TITLE
Viaversion devs and that ArtFect proxy maker person are not credited

### ISSUE THREAD

**Issue by feliscatusmeows** [THEREALWWEFAN231/Inertia#985]
**Inertia Utility Mod version:** 3.1.3+
**Minecraft version:** all
**Operating system:** all
**Optifine/Other mods:** 
doesn't matter
**What's the issue:** 
The ViaVersion people and the ArtFect person is not credited in https://inertiaclient.com/Credits.php

**Comment by feliscatusmeows** [comment]
oh and also chan and godeps

**Comment by THEREALWWEFAN231** [comment]
Added viaversion & ArtFect, we have different stuff for chan & godeps, later.
