### ISSUE TITLE
.unpack

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#987]
**Minecraft Version(s)** All.

**What is the suggestion**
.unpack command which will unload Inertia Utility Mod from the current game session. An alternative name could be .selfdestruct

**Why would this feature be useful**
So we can join **non-anarchy servers** without having to restart the game, alongside other reasons.

**Comment by feliscatusmeows** [comment]
No. This is injection client. That seems painful to code.

**Comment by constantinDev** [comment]
Why would the client affect joining non-anarchy servers? I had no issues at all with that so far. You probably have a module enabled that triggers a certain type of anticheat.

**Comment by TheRedHippo** [comment]
> Why would the client affect joining non-anarchy servers? I had no issues at all with that so far. You probably have a module enabled that triggers a certain type of anticheat.

This is an **anarchy client**, intended for **anarchy servers**. Inertia isn't for use on servers where it's not allowed, that would be against Discord's TOS.

**Comment by constantinDev** [comment]
> > Why would the client affect joining non-anarchy servers? I had no issues at all with that so far. You probably have a module enabled that triggers a certain type of anticheat.
> 
> 
> 
> This is an **anarchy client**, intended for **anarchy servers**. Inertia isn't for use on servers where it's not allowed, that would be against Discord's TOS.

**discord's** tos..?

**Comment by feliscatusmeows** [comment]
ya what does discord have to do with this?

**Comment by TheRedHippo** [comment]
so the server doesn't get banned?
that would be against mc's tos as well I belive

**Comment by constantinDev** [comment]
> so the server doesn't get banned?
> 
> that would be against mc's tos as well I belive

i dont think discord gives half a fuck about us cheating in mc. + minecraft java version stays unmoderated by the minecraft team, and "utility mods" are never referenced in the eula. looks pretty good to me

**Comment by Paralusion** [comment]
duplicate of #270
