### ISSUE TITLE
Suggestion regarding open source

### ISSUE THREAD

**Issue by constantinDev** [THEREALWWEFAN231/Inertia#989]
**Minecraft Version(s)**
*
**What is the suggestion**
open source the mod
**Why would this feature be useful**
so we can take inspiration and make our own forks of the client to add more features. would also be great for exploring how to make irc chats.

(note to wwefan: you dont have to open source because skids are a valid reason, but it would still be pretty pog if you did)

**Comment by feliscatusmeows** [comment]
Once that happens can you make https://github.com/Tigermouthbear/KamiAutoSkidder but for inertia?

**Comment by constantinDev** [comment]
> Once that happens can you make https://github.com/Tigermouthbear/KamiAutoSkidder but for inertia? 

oh lmao i didnt even know this exists. Im gonna wait for skids to make that one tho so they at least have somewhat of a challenge

**Comment by AutistEren** [comment]
API is coming soon if you really want to add your own features

**Comment by feliscatusmeows** [comment]
#719 #707 Read these please. also 
![image](https://user-images.githubusercontent.com/29553771/103337576-ad38d280-4a30-11eb-9ab6-141d29c827fd.png)

**Comment by THEREALWWEFAN231** [comment]
😳 I didn't even see this was open 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 

.... I don't know what to say for myself.

**Comment by feliscatusmeows** [comment]
~~jk hes just scared of his spaghetti code being released~~

**Comment by JohnShiozo** [comment]
closed source take it or leave

**Comment by feliscatusmeows** [comment]
Everything is open source if you have enough time. See: mcp, yarn.
