### ISSUE TITLE
Enchant Cracker

### ISSUE THREAD

**Issue by RocketNinja15** [THEREALWWEFAN231/Inertia#990]
**Minecraft Version(s)**
All
**What is the suggestion**
To integrate enchant cracker by earth computer. It is an open sourse enchantment cracker. It calculates the enchantment “seed” and when u drop the amount of items that it tells you, you can select exactly what enchantments you want on your sword.... imagine if intertia could could do this automatically 
**Why would this feature be useful**
Yes ... https://github.com/Earthcomputer/EnchantmentCracker

**Comment by feliscatusmeows** [comment]
frick it just add all of clientcommands to inertia

**Comment by RocketNinja15** [comment]
@THEREALWWEFAN231 ???

**Comment by JohnShiozo** [comment]
pong

**Comment by Godwhitelight** [comment]
bruh that is epic

**Comment by Paralusion** [comment]
duplicate of #899
