### ISSUE TITLE
Xray not working at al

### ISSUE THREAD

**Issue by constantinDev** [THEREALWWEFAN231/Inertia#991]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.4
**Operating system:** Linux, Ubuntu (Ubuntu 20.04.1 LTS x86_64)
**Optifine/Other mods:** Tried it without, same results

**What's the issue:** Xray seems to be completely broken, not rendering clouds but blocks still render fine.

**Crash-report(if applicable)(Would be very useful also please format):** -

**Final checklist:**

- [X] I know how to properly use check boxes 
- [X] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [X] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by THEREALWWEFAN231** [comment]
Remove the fabric api and or any other mods you might have.

**Comment by constantinDev** [comment]
> Remove the fabric api and or any other mods you might have.

did that as i stated, didnt work regardless

**Comment by THEREALWWEFAN231** [comment]
The template made it seem like you just removed optifine, well I know 100% xray works on all versions with no other mods...

**Comment by constantinDev** [comment]
> The template made it seem like you just removed optifine, well I know 100% xray works on all versions with no other mods...

Weird... Gotta take a look at how you did the xray then. Maybe i can fix it myself

**Comment by THEREALWWEFAN231** [comment]
😔 You are kind of annoying me ngl/:

**Comment by constantinDev** [comment]
> pensive You are kind of annoying me ngl/:

damn no need to go harsh
