### ISSUE TITLE
New mode to scaffold/a command that allows you to pick which blocks scaffold will not place.

### ISSUE THREAD

**Issue by pleasegivesource** [THEREALWWEFAN231/Inertia#993]
**Minecraft Version(s)**
All, if possible, I use the 1.16.4 version personally

**What is the suggestion**
Make scaffold not place echests because it's really annoying and wasteful.

**Why would this feature be useful**
Because enderchests/chests/soul sand are lower than a full block and it glitches out real bad.

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment]
Surround too, ender chests are not good defense against explosive magic crystals.

**Comment by Godwhitelight** [comment]
yes this is needed

**Comment by Paralusion** [comment]
merged with #1128
