### ISSUE TITLE
Auto Tool Bug

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#997]
**Inertia Utility Mod version:** Latest prebuild
**Minecraft version:** 1.16.4

**What's the issue:** 
Auto tool uses sword to mine beacons.

**Final Checklist**

- [x] I know how to properly use check boxes 
- [ ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by TheRedHippo** [comment]
Beacon has no tool; using your fists will mine it at the same speed as a pickaxe. Autotool simply just goes to your first slot, which happened to be your sword.

**Comment by AutistEren** [comment]
oh... interesting
